### ISSUE TITLE
T-Shock keep crashing?

### ISSUE THREAD

**Issue by PrincessCuddles** [NyxStudios/TShock#1000]
I have been using Tshock for a long time now, and have never had any problems with it crashing until recently. Ever since the 1.3 update, I haven't been able to run Tshock. Upon startup, it gives me a crash report and proceeds to do nothing. I am always using the most up to date version, but still can't use it.
![error](https://cloud.githubusercontent.com/assets/13306404/8641202/8a74bcf8-28cd-11e5-92e5-56b5e97eb6be.png)
Above is the image of my crash message. Any help?

**Comment by nicatronTg** [comment]
https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/
