### ISSUE TITLE
Team dye max stack is limited to 1

### ISSUE THREAD

**Issue by moozaad** [NyxStudios/TShock#1001]
Client happily stacks to many more than that.

You get petrified for breaking the limit.

**Comment by moozaad** [comment]
And team hair dye

**Comment by WhiteXZ** [comment]
What message is provided (logs, console, player) when this happens?

**Comment by moozaad** [comment]
Nothing in tshock/*log but I'm running multiple instance in the same root so it might have been overwritten.

Basically we bought a stack of ten team dyes from the  Dye merchant and were in the process of moving out resources to a tshock server from a local vanilla server, and each time a person tried to log in with it they were petrified (stoned/disabled?) due to the stack being >1. Usual red text in chat window for the player about the stack size and disabled until fixed. We had to log into the vanilla server to get rid of the dye.

**Comment by WhiteXZ** [comment]
https://github.com/NyxStudios/TerrariaAPI-Server/commit/33a2760
