### ISSUE TITLE
Chests dupe/glitch

### ISSUE THREAD

**Issue by Shadou81** [NyxStudios/TShock#1003]
This has only been tested by me on a SSC world, I do not know if this also affects non-SSC worlds. Occasionally when you open a chest, you will not see all of the chest slots. You could see anywhere from 2 to all but 2 of the chest slots, and their contents. When this happens, anything that is taken out of or put into the chest is not saved. Closing and reopening the chest until you can see all of the item slots fixes the issue and makes the chest work normally again, but while the chest is affected by the issue a player can effectively duplicate its contents by taking items out of it, closing it, opening it, and taking the item out again. If the glitch affected the chest on the second opening, they could take the item again, close it again, open it again, and take the item a third time. Additionally, while the chest is affected, anything that is put into the chest is effectively destroyed.

**Comment by jtmal0723** [comment]
I can confirm this does occur on non-SSC worlds. I don't utilize the service and have had this occur with many chests, while attempting to locate the Jungle Temple.

![image](https://cloud.githubusercontent.com/assets/2731183/8673097/e3899bd0-2a01-11e5-99af-0f24548aca22.png)

**Comment by d3x7ro** [comment]
quick stack to chest button is hardly ever where as well

**Comment by ruifung** [comment]
This. Is a really annoying bug,

**Comment by Ijwu** [comment]
Likely an issue with data handlers or packet malformation.

**Comment by withmorten** [comment]
@d3x7ro, that is actually a confirmed (by CenX) Terraria client side bug. You can reset the value that defines if the button shows up or not by talking to an NPC and going into shop mode, thus making it show up.

**Comment by Ijwu** [comment]
Closing issue on grounds of it being a client bug. Up to Re-Logic now.

**Comment by LittleEndu** [comment]
One of my friends is reporting crashes when he opens chest on my server.

**Comment by Shadou81** [comment]
@Ijwu, you closed this issue based on withmorten's confirming to d3x7ro that the quick stack to near chests button is bugged on the client side, but the issue this ticket is open for is not for the quick stack issue; d3x7ro derailed the actual issue with his comment. Could this be re-opened, unless someone can clarify that, specifically, the topic issue of chests not opening all the way is a client side bug?

**Comment by WhiteXZ** [comment]
The chest button disappearing is a client error. The slots disappearing is a server bug that we're working on

**Comment by tylerjwatson** [comment]
Fixed in NyxStudios/TerrariaAPI-Server@703270892fd1f500211ee77bae0d423ca0691cba
