### ISSUE TITLE
chests: Sometimes when you open one, the chest doesn't open all the wa

### ISSUE THREAD

**Issue by d3x7ro** [NyxStudios/TShock#1004]
<+failshadou> @white, there is something seriously wrong with chests. Sometimes when you open one, the chest doesn't open all the way; you don't see all of the slots in the chest. When that happens, you can take things out of or put things into the chest, but the contents of the chest will not change.
<+white> SSC or normal?
<+failshadou> Closing and reopening the chest will usually fix it, but... it effectively dupes anything you take out of the chest
<+failshadou> SSC
<+white> :rip:
<+white> Make a bug report pls
<+white> Turns out http://NPC.ai[3] is a death flag
<+white> set it to 1 and the NPC is killed
<+white> 0 and it's not
<+d3x> normal
<+d3x> im not on scc and chests do the same
<+white> Any plugins?
<+d3x> no stock
<+white> Also that is a huge relief x)
<+white> Okay.. So our data handler is ded somewhere, I assume

**Comment by WhiteXZ** [comment]
https://github.com/NyxStudios/TShock/issues/1003
