### ISSUE TITLE
Server Crash after CheckSunflower()?

### ISSUE THREAD

**Issue by kidoblivious** [NyxStudios/TShock#1005]
After first servercrash, I ran mono -v TerrariaServer.exe, and second servercrash log ended
Method Terraria.WorldGen:UnspawnTravelNPC () emitted at 0x4131afc0 to 0x4131b684 (code length 1732) [TerrariaServer.exe]
converting method Terraria.WorldGen:PlaceDye (int,int,int)
Method Terraria.WorldGen:PlaceDye (int,int,int) emitted at 0x4131b690 to 0x4131c4ae (code length 3614) [TerrariaServer.exe]
converting method Terraria.GameContent.Achievements.AchievementsHelper:set_CurrentlyMining (bool)
Method Terraria.GameContent.Achievements.AchievementsHelper:set_CurrentlyMining (bool) emitted at 0x4131c4b0 to 0x4131c4c9 (code length 25) [TerrariaServer.exe]
converting method Terraria.WorldGen:CheckSunflower (int,int,int)
killed

(I observed Traveling Merchant's leaving a minute or two before server crash, so thought I would cut the output out there)

**Comment by Ijwu** [comment]
Try increasing the amount of RAM you're allowing the process and see if you can replicate.

**Comment by Ijwu** [comment]
No feedback after ~2 weeks. Closing for now. If this issue is still present then this thread will be reopened.

**Comment by kidoblivious** [comment]
Couldn't keep that release up for > 5 mins play, present release seems
stable, I could never find a consistent action set to replicate. The
process was generally using 1.2g of Ram at that time when top was run. I
agree on closing the thread.
