### ISSUE TITLE
World does not render itself properly around spawn locations

### ISSUE THREAD

**Issue by Oni69** [NyxStudios/TShock#1006]
Updated a server to a 1.3.05 build and found that upon logging into the server areas around locations where players can spawn (I.E where the login script places them upon joining the server and their beds) the world does not render itself correctly with horizontal block connections as seen below.

![image](https://cloud.githubusercontent.com/assets/13333844/8675210/87e5d01c-2a3a-11e5-8e61-80d25fc3b8c0.png)

The issue can be fixed by the players themselves by hitting the blocks once with an appropriate tool (Hammer, pickaxe or in the case of ropes putting down a torch) which will restore an area around the hit block. It also appears that the spawn area closest to where the player logs out is not always affected by this issue.

**Comment by WhiteXZ** [comment]
This is a known bug we've been working to fix

**Comment by Oni69** [comment]
Ah ok, I searched through the issues and couldn't find anything related to it so I thought I would be safe and point it out.
