### ISSUE TITLE
Graphics - blocks seperate

### ISSUE THREAD

**Issue by defran** [NyxStudios/TShock#1007]
Sometimes this wierd bug appears where blocks get seperated. Now mapwide, just a small area.

edit: water gets messed up too

![capture 2015-07-14 20_28_36](https://cloud.githubusercontent.com/assets/13337718/8681407/78dc1a54-2a67-11e5-9f94-356729915f07.png)

**Comment by Ijwu** [comment]
Known issue, it's a problem with networking. @tylerjwatson is on it.

**Comment by tylerjwatson** [comment]
Fixed in NyxStudios/TerrariaServerAPI#703270892fd1f500211ee77bae0d423ca0691cba.
