### ISSUE TITLE
World's edge not loading

### ISSUE THREAD

**Issue by Chais** [NyxStudios/TShock#1009]
I created a new medium sized world with -autogenerate. When I arrived at the eastern ocean I suddenly dropped into nothingness. The last half screen of the accessible world wouldn't load. I could drop all the way down to hell and it still wouldn't load.
![screenshot of world's edge](http://images.akamai.steamusercontent.com/ugc/458589695957047192/F2121D33D096B39ABAA1E2F13E5E14F24F1DC3B9/)

**Comment by Ijwu** [comment]
>ijwu [2:49 PM] 
>probably a inconsistency between send WorldInfo packet and actual world size, is my guess

**Comment by darkunderdog** [comment]
I'm having the same problems on my server. Only since updating to the new pre-release versions of tshock. The problem seems to occur after 30 to 45 mins after restarting the server

**Comment by Ijwu** [comment]
@darkunderdog Are you using `-autocreate`?

**Comment by Chais** [comment]
For me it occurred immedeately. Started the server creating the world, flew to the edge. Made a detour over two floating islands though.

**Comment by Chais** [comment]
I just created a world manually, through the interactive interface. It didn't show this behaviour.
I created another world, again with -autogenerate, and got the weird cutoff again. Even after restarting the server. So it's most likely a bug in autogeneration.
