### ISSUE TITLE
SSC not creating chars with custom starting list.

### ISSUE THREAD

**Issue by tomose** [NyxStudios/TShock#1010]
TerrariaAPI Version: 1.19.0.0 (Protocol v1.3.0.5 (153))

Enabled SSC in sscconfig.json, modified starting items, new characters are still being generated with 3 copper items and none of the custom items. New chars connect to server, register, then login and still have standard starting gear and not custom gear. I assume there's nothing else I need to do to make this work?

**Comment by Tygra** [comment]
Just tested with the 4.3.5 release. It works for me.

**Comment by tomose** [comment]
1. Downloaded 4.3.5 release.
2. Extracted.
3. Ran server to generate tshock folder.
4. Exit server.
5. Copy sscconfig.json to new tshock folder. https://put.moe/#4a34126f792b09c8:rosBWDUTPxLK5Q2OXd39WupoF3yID01kiLokgePk
6. Load server
7. Load new world created by server
8. Create new character and connect.
9. Register using /register pass
10. Login using /login pass

No new items. Only the default starter items

**Comment by Tygra** [comment]
remove the - from netid-s.
there are only a few negative ones

**Comment by tomose** [comment]
Ah, I didn't understand the format and assumed the - were needed. Issue is resolved.
