### ISSUE TITLE
Quick stack to neraby chest is hidden

### ISSUE THREAD

**Issue by lzerokoo** [NyxStudios/TShock#1012]
I'm using Tshock 4.3.5, when join in multiplayer, after sometime the button "Quick stack to nearby chest" disappear.

Sorry for my english, mi native language is other.

**Comment by Lunatrius** [comment]
Terraria bug caused by opening Money Trough. Talking to any NPC will bring back the button.

**Comment by lzerokoo** [comment]
Thank you!

**Comment by Ijwu** [comment]
Confirmed client bug. Non TShock issue.
