### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Chais** [NyxStudios/TShock#1013]
I got this esception in a relatively new world after killing the WoF.
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.WorldGen.CheckPot (Int32 i, Int32 j, Int32 type) [0x00000] in <filename unknown>:0 
  at Terraria.WorldGen.TileFrame (Int32 i, Int32 j, Boolean resetFrame, Boolean noBreak) [0x00000] in <filename unknown>:0
```
Seems like something broke a pot with a non-existing item.

**Comment by WhiteXZ** [comment]
Possibly fixed in https://github.com/NyxStudios/TerrariaAPI-Server/commit/bd5c1c6fd76ab917118e19830638057563783c7e

**Comment by Patrikkk** [comment]
No feedback since. So I'm guessing this is fixed?

**Comment by Ijwu** [comment]
Closing due to 12 days without feedback. If this issue is still present then the issue will be reopened.
