### ISSUE TITLE
Bombs/Dynamite & Varieties ignore Region Protection

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1019]
Issue: Sticky Bomb, Bomb, Sticky Dynamite, Dynamite all ignore region protected areas and can be destroyed. This does not apply to Fish Bomb.

**Comment by WhiteXZ** [comment]
Which build?

**Comment by Marcus101RR** [comment]
Both #484 and github branch.

**Comment by WhiteXZ** [comment]
Could you test with [build 476] (http://direct.tshock.co:8085/browse/TERRA-TSHOCK-476) please?

**Comment by Marcus101RR** [comment]
Tested: Was able to destroy blocks in a tshock region.
