### ISSUE TITLE
Flower Boots not making flowers

### ISSUE THREAD

**Issue by ItWasUncalledFor** [NyxStudios/TShock#1021]
When using flower boots on multiplayer, boots will not generate flowers while walking on grass

**Comment by P2Mc28** [comment]
It's permissions related I bet; they work when I log in as Super Admin.

**Comment by Puremin0rez** [comment]
I can confirm this, flowers are not created with flower boots but they are for super admin. Not sure why?

**Comment by WhiteXZ** [comment]
Likely due to superadmin having the 
```C# 
tshock.ignore.sendtilesquare
```
permission

**Comment by DaBomberNTG** [comment]
Tested, as long as the group your in has "tshock.ignore.sendtilesquare" you can create flowers. This can be closed.

**Comment by nicatronTg** [comment]
Do we want to do anything to try and monkey patch this @WhiteXZ?

**Comment by nicatronTg** [comment]
_I am assigned to this issue for monitoring/oversight but am not actively working this issue._
