### ISSUE TITLE
Does not have projectile permission to update projectile. (465)

### ISSUE THREAD

**Issue by niek1414** [NyxStudios/TShock#1022]
(After getting hit?) by the cultist all non-admin players get "disabled".
The console message: Player ** has been disabled for Does not have projectile permission to update projectile. (465).
After respawn of the cultist the problem still exists. This happened multiple times (3) in the same session.
It did not matter if the user is logged in as a registered user.

**Comment by Patrikkk** [comment]
Thanks for the report, this will be fixed in the next release :)
