### ISSUE TITLE
Browsing occupies slots

### ISSUE THREAD

**Issue by Gaegamel** [NyxStudios/TShock#1023]
Hi,
I'm sorry to disturb you. I looked through the issues. Nothing seemed really fitting. The closest was https://github.com/NyxStudios/TShock/issues/947 (because the actual reason might still be unknown. My bad, if it is known already).

TerrariaAPI Version: 1.19.0.0 (Protocol v1.3.0.5 (153))
SendQ edition
TShock 4.3.5.0 (Yoraiz0r R0cks)
(executed with Mono: "mono --server --gc=sgen -O=all TerrariaServer.exe" )

The bug: Connecting to the server via the web browser repeatedly leads to the ip occupying slots and not freeing them, leading to an overall lockdown.

How to reproduce the issue:
1. Start a serverinstance. For example selecting 4 slots and on port 7777 (a default world wouldn't be bad, either).
2. Start your webbrowser and enter the ip+port of your terraria-Server. i.e. 1.2.3.4:7777.
3. Repeat that several times by refreshing the tab/window. Now, pay attention to your server-window. Messages such as:

> x.x.x.x:60869 is connecting to slot 0...
> x.x.x.x:60870 is connecting to slot 1...

should appear (like expected for "normal" behaviour).
After reaching max slots, `Netplay: No more clients can connect!` will appear (ok under normal circumstances).

If you need further information, I would be glad to help.

With kind regards,
Gaegamel

**Comment by Ijwu** [comment]
Oh my god, this is hilarious. Pinging @tylerjwatson. When you fix your sendq fix this too. :P

**Comment by imasonaz** [comment]
This looks like it may also occur in some ways in vanilla.

**Comment by nicatronTg** [comment]
I believe this was fixed, but I'd like confirmation from @tylerjwatson before I close it.

**Comment by tylerjwatson** [comment]
As SendData requires a player slot ID it is not possible to open a socket without it taking up a slot. 

This is impossible to fix. We will investigate ways to work around it shortly.

**Comment by nicatronTg** [comment]
@tylerjwatson is this issue still relevant with the move to OTAPI + Orion?

**Comment by tylerjwatson** [comment]
Unfortunately this is a regression with how Re-logic has written their socket handling, meaning that any Open TCP socket is regarded as a player, even when it has not even attempted a player handshake, thus taking a slot.

It's broken at the very concept. There may be a path around it if we are able to reimplement terraria's network stack and patch it in as an OTAPI modification, however likely that is.

Sent from my iPhone

On 11 Oct. 2016, at 9:27 am, Lucas Nicodemus <notifications@github.com<mailto:notifications@github.com>> wrote:


@tylerjwatson<https://github.com/tylerjwatson> is this issue still relevant with the move to OTAPI + Orion?

-

**Comment by nicatronTg** [comment]
@tylerjwatson should this be kept open, then?

**Comment by tylerjwatson** [comment]
Reopen it in NyxStudios/Orion as it's an API level issue

Sent from my iPhone

On 11 Oct. 2016, at 9:44 am, Lucas Nicodemus <notifications@github.com<mailto:notifications@github.com>> wrote:


@tylerjwatson<https://github.com/tylerjwatson> should this be kept open, then?

-

**Comment by nicatronTg** [comment]
Done.
