### ISSUE TITLE
Expert mode coin dupe

### ISSUE THREAD

**Issue by RedDragonGecko** [NyxStudios/TShock#1024]
In expert mode; creatures pick up dropped coins and re-drop them on death.
If the coins are half a screen away or so(at 1920x1080) creatures dupe the coins as in the don't actually pick the coins up but they still drop them on death.

Was able to accumulate 300+ platinum coins in about 5 minutes at a mob farm.
Tested  4.3.5 although I have noticed the behavior since 4.3.0 without realizing what I was seeing.
Also tested vanilla and it doesn't happen.

**Comment by Smokz** [comment]
Look, i did an afk farm on expert mode, farm for pumpking moon. Well, when the event is over, I go to pick up all the drops, and i collect like all my slots only with 999 Platinum Coins, excuse my bad english.

**Comment by Chais** [comment]
This sounds like it's related to #967 where tiles that are not completely onscreen don't get destroyed by explosives.

**Comment by RedDragonGecko** [comment]
@Chais I had the same thought.

**Comment by Patrikkk** [comment]
Can you test this by setting "RangeChecks" to false in tshock config?

**Comment by RedDragonGecko** [comment]
"RangeChecks" False effectively solves the coin dupe

**Comment by Patrikkk** [comment]
So we still consider this an issue?
If I understood right:  IF RangeChecks is true,  mobs pick up coins out of screen, but the coins actually stay there, so they duplicate.

**Comment by RedDragonGecko** [comment]
Well RangeChecks is set to true by default, so by default you have a very easy and quick way to endlessly dupe coins.
