### ISSUE TITLE
Truffle Worm don't spawn - TShock 4.3.5

### ISSUE THREAD

**Issue by Zignixx** [NyxStudios/TShock#1032]
Hey,

The Truffle Worm can't spawn on TShock. I got the DicemanX Ultimate HUB world v6.0 as Test Map. Terraria Vanilla = Works (just after ~20 secs)
TShock = no Truffle Worms (after 20 mins !)

Can you maybe check it?

**Comment by Puremin0rez** [comment]
I can confirm this, my server of many players have been complaining about this.

**Comment by WhiteXZ** [comment]
Please confirm this still happens on [build 497](https://direct.tshock.co:8085/browse/TERRA-TSHOCK-497)

**Comment by Zignixx** [comment]
Hey,

tested on build 498. Works very nice now. Thank you for the fix! :)

**Comment by Puremin0rez** [comment]
It's fixed

**Comment by Ijwu** [comment]
Closing as multiple reports show this has been fixed.
