### ISSUE TITLE
Superadmin kicked with DrillContainmentUnit

### ISSUE THREAD

**Issue by imthe666st** [NyxStudios/TShock#1035]
Although I have Superadmin permissions I get kicked for using the DrillContainmentUnit. 
The "VeryDangerousDoNotChangeEnableDrillContainmentUnit" is set to false. 
Superadmin and admins shouldn't be kicked for this.

**Comment by nicatronTg** [comment]
That function exists because it was impossible to work with any protection, and in subsequent releases it has been deprecated.

**Comment by nicatronTg** [comment]
(The config option will be removed entirely soon)

**Comment by imthe666st** [comment]
So, there will be a permission to use the DCU? Is it possible to enable the DCU using a command or must I edit the config file?

**Comment by nicatronTg** [comment]
Neither. A plugin will have to implement this.

**Comment by nicatronTg** [comment]
This config option was only added because when we temporarily disabled the DCU because it violated all protection, some users wanted it back on for small servers.
