### ISSUE TITLE
SSC does not affect 6th Accessory slot

### ISSUE THREAD

**Issue by Kromara** [NyxStudios/TShock#1036]
To specify a bit, a player joined my SSC world with a character from his singleplayer. This was his first time joining the SSC world, although he already had the 6th accessory slot unlocked due to it being unlocked on his character from playing in his singleplayer world.

**Comment by Enerdy** [comment]
Intended behaviour would be for him to have it relocked once logged in until he unlocks it within the SSC environment. Might have to store whether they've unlocked it or not somewhere.

**Comment by WhiteXZ** [comment]
This is a planned SSC improvement
