### ISSUE TITLE
superadmin bypassing ssc checks

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1038]
As a super admin, my items arn't saving/updating from SSC, it just loads my single player  char and inventory every time.

**Comment by WhiteXZ** [comment]
Superadmin is meant to bypass SSC checks.

**Comment by tysonstrange** [comment]
never used to and is painful to be forced into doing on an ssc server, as all my items keep resetting every time i join.

**Comment by Enerdy** [comment]
[From the permissions page:](https://tshock.atlassian.net/wiki/pages/viewpage.action?pageId=3047433) https://dl.dropboxusercontent.com/u/31979270/screenshots/2015-07-20_10-46-02.png

**Comment by Enerdy** [comment]
If it didn't before, it must have been a bug. superadmin has every permission, so naturally it'd also have that one.

**Comment by tysonstrange** [comment]
w/e

if you think its a good idea to leave it forced, then good on you.

**Comment by guitarguy1133** [comment]
i have a crazy idea... hear me out... you could always, idk... make a superadmin group with all perms BUT the tshock.ignore.ssc?

**Comment by tysonstrange** [comment]
You're right, that is a crazy idea.

Then I'd have to worry about updating it all the time whenever new updates come out or new plugins are installed.

**Comment by guitarguy1133** [comment]
oh man... you'll have to do some work! heaven forbid. =P it takes like 5 sec to ad perm nodes for a new plugin... "plugin.*"  bam. plugin permission node was added.

**Comment by WhiteXZ** [comment]
/group addperm groupName * !tshock.ignore.ssc
* will provide any permission, regardless of when it's installed.
!tshock.ignore.ssc will prevent the tshock.ignore.ssc permission being applied

**Comment by guitarguy1133** [comment]
^ what he said :3 :+1:

**Comment by tysonstrange** [comment]
Less effort could go into just creating an option for superadmins to ignore the permission, then you'd never have to do that ever again. ever

**Comment by WhiteXZ** [comment]
That goes against the idea of a superadmin group, and as such will never be implemented.
Sorry for any inconvenience, but it is what it is.
