### ISSUE TITLE
Megaphone not dropping?

### ISSUE THREAD

**Issue by zevvex** [NyxStudios/TShock#1040]
Me and some friends killed over 7000 pixies (at spawn rate 5 max spawns 200) and a few hundred dark mummies for a megaphone, it just does not seem to drop anymore in the current release version (playing on expert mode unsure if that may be relevant, i figure it is since most drop rates change between modes), we didnt get a blindfold either but we gave up and went into regular terraria and got multiple megaphones and blindfolds in 30 mins and with only 100 or so enemies, didnt see this anywhere here, on a side note unrelated to this today i compiled the source cause i wanted the vortex armor working right sooner and in that lihzahrd traps we used arent functioning (no spears/super darts) in a grinder we had made (i dont have any other traps so unsure if theyre broken), wondering if anyone here has input on that as well or if i somehow compiled that wrong, there wasn't any issues/warnings or errors compiling so i just want to make sure thats a known thing if it isnt me who messed up.

**Comment by WhiteXZ** [comment]
Temple traps appeared to be broken when I was playing around earlier.

Mob drops may be fixed in build 497

**Comment by Marcus101RR** [comment]
I can confirm it works in BUILD #498
