### ISSUE TITLE
/exit fails to send kick message (lost connection error)

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1042]
Issue: When kicking players, or restarting server. All players who become kicked do not get their kicked message. It results in "Lost connection". Not sure where the issue lies, but it seems to relate to kicking of players.

**Comment by tylerjwatson** [comment]
This is a sendq problem. Will fix in due time.

**Comment by tylerjwatson** [comment]
Fixed in NyxStudios/TerrariaAPI-Server@8725870c0cd15f620b10a27de5c44bf0dc4a6f6d
