### ISSUE TITLE
"AllowHallowCreep" not functioning

### ISSUE THREAD

**Issue by SweetTart** [NyxStudios/TShock#1043]
TShock version: v4.3.5.0
Terraria version: 1.3.0.5

http://imgur.com/a/zqZ9g

Even though I have set "AllowHalloCreep" to false, the Hallow still spreads. I have reloaded the server and restarted multiple times since I changed it.

Upon finding it spreading initially, I also closed and reopened the server. It still spread upon reopening.

Here's what's in my config.json:

  "IgnoreNoClip": false,
  "AllowIce": false,
  "AllowCrimsonCreep": false,
  "AllowCorruptionCreep": false,
  "AllowHallowCreep": false,

**Comment by Patrikkk** [comment]
AllowxxxCreep simply prevents the biome from spreading around map when you trigger hardmode.
(those stripes won't be generated).
There is no feature to prevent actual biome spreading.
