### ISSUE TITLE
Wrong behavior : Javelin

### ISSUE THREAD

**Issue by KrystalCroft** [NyxStudios/TShock#1044]
When equiped and using the throwing-weapon "Javelin" by hitting an single mob, the damage-over-time, which Javelin inflicts after hitting an enemy, displayes the damage, but does not accutally dealt this damage-over-time to that mob.

**Comment by KrystalCroft** [comment]
>> Correction: Bone Javelin

**Comment by Patrikkk** [comment]
Shredded some slimes with it just now. (Damn I like this weapon ^^ badass)
Tested on latest version. (which will be 4.3.7 , released soon).

**Comment by KrystalCroft** [comment]
Awesome. So the Damage-over-time works fine now? :D
