### ISSUE TITLE
Wrong version TShock API latest release

### ISSUE THREAD

**Issue by DrowningElysium** [NyxStudios/TShock#1048]
When starting the server version that is released around 18:30 EST has a wrong version of the Tshock API

Notification: [Server API] Warning Plugin "TShockAPI.Tshock" is designed for a different Server API version <1.19> and was ignored.

**Comment by DrowningElysium** [comment]
Nevermind I was too hasty, has been fixed in the latest commit.

**Comment by nicatronTg** [comment]
https://twitter.com/NyxStudios/status/624261064159399936
