### ISSUE TITLE
Still having issues with tiles being sent to clients improperly

### ISSUE THREAD

**Issue by Kromara** [NyxStudios/TShock#1049]
Still running into the same issue with tiles all being aligned vertically.
Here's a super pretty screenshot to show you some of my discoveries.
Oddly, it seems to be more prominently on the left side of spawn, but after staying in one general area for long enough it corrects itself.
http://puu.sh/ja68Q/f29a02e6c1.jpg

**Comment by blackalegator** [comment]
This happens mostly on spawn points or on last location points (when remember location is enabled). Furthermore once some tiles get bugged they are 'saved' this way and are allways sent improperly to the client. This is not a display or client side bug - rejoining will not fix theese tiles.
