### ISSUE TITLE
-autocreate flag ignored

### ISSUE THREAD

**Issue by CJKay** [NyxStudios/TShock#1050]
```./TerrariaServer.exe -autocreate 1 -world world.wld -port 7777 -ip 0.0.0.0 -maxplayers 16``` gives the error:

```
[Server API] Error Server crashed due to an unhandled exception:
System.Exception: Terraria world at path "world.wld" doesn't exist.
  at Terraria.ProgramServer.InnerStart (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by nicatronTg** [comment]
Can you test with this version of the API? https://dl.dropboxusercontent.com/u/1253613/JaexMadeShareX/2015/07/TerrariaServer.exe

**Comment by CJKay** [comment]
Yep, that seems to do it.

**Comment by CJKay** [comment]
Could you take a look at [https://github.com/NyxStudios/TerrariaAPI-Server/pull/24] this pull request which fixes this issue?
