### ISSUE TITLE
Tshock won't let other people join

### ISSUE THREAD

**Issue by Laith225** [NyxStudios/TShock#1055]
As the title says. Other people can't join my Tshock server. It worked just fine when i was at my old apartment, in April when i moved to a new house i've been starting to get these issues. I have port-forwarded, changed the settings in Windows Firewall and everything. My other open ports work just fine. My Minecraft server, smooth as usual. My website, working as it should work. It's just my Terraria that is having issues. It works fine with the Host & Play option from the Multiplayer tab. The Terraria server that comes packed with Terraria and Tshock won't work. Can somebody please help me?

**Comment by nicatronTg** [comment]
Please [post on the forums](https://tshock.co/xf/index.php).
