### ISSUE TITLE
Pressure plates trigger twice

### ISSUE THREAD

**Issue by travisnewman** [NyxStudios/TShock#1056]
TShock 4.3.7 PreRelease, Terraria 1.3.0.7. Tested on Windows, Mac, and Linux, all three versions are affected.

I have my doors wired with pressure plates so I can run in and out without right clicking to open the door, but in 4.3.7 it triggers twice, so the door opens and then closes. Confirmed to work in single player and on plain Terraria servers without TShock installed.

Tested this with two wire configurations:
1. The plates are two tiles away from the door on either side, connected with a single wire.
2. The plates are two tiles away from the door on either side, and each plate is connected to the door on a different part of the door with differently colored wire.

No server logs or anything seem relevant to this, but let me know if you need more info.

I saw someone report this same bug on twitter, so I know I'm not alone, but Twitter isn't the best place to report bugs so you may not have seen it.

**Comment by gheta** [comment]
I signed up to Github to add to this issue. I do the exact same thing and my pressure plates for my doors also trigger twice, it even makes the sound effect twice every time you step on the plate once- both quickly and if you're just flat out standing on it. Opening doors by right clicking is not giving any issue.

**Comment by Patrikkk** [comment]
Thanks for the report :) It's fixed in future release.

**Comment by travisnewman** [comment]
Woot! Thanks Patrikkk

**Comment by Patrikkk** [comment]
Psst, someone close plz :P

**Comment by xRyanCat** [comment]
I can confirm this is still a issue, the bug has just slightly changed.

TShock v. 4.3.9, Terraria v. 1.3.0.8, Windows 10

Previously, the pressure plate would trigger twice, resulting in a closed door remaining closed.

Now, the pressure plate still triggers twice, but only 50% of the time does the door activates twice. 

A key way to tell the pressure plate is triggering twice, is the pressure plate sound is played twice in rapid succession.
