### ISSUE TITLE
mysql Test

### ISSUE THREAD

**Issue by fizzvr** [NyxStudios/TShock#1057]
my config.json
 "StorageType": "mysql"

I got an error on log file when i try to connect for first time to the server.
```
GetDataHandlers: ERROR: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en TShockAPI.GetDataHandlers.HandleGetSection(GetDataHandlerArgs args)
   en TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)
```
Full log on gist: https://gist.github.com/fizzvr/c5186b26f73d505bcaea

BUT at this point
the database is not created on mysql, i check information_schema and not see any table related to tshock?

Finally the image and cant init terraria map
![Sin titulo](http://img5.uploadhouse.com/fileuploads/21388/2138809557dc086bc67f2b398b8cc7cac0c8b994.jpg)

So i think the builder C:\TShock-4.3.7\TShockAPI\DB\IQueryBuilder.cs

**Comment by WhiteXZ** [comment]
This is not an SQL error.
