### ISSUE TITLE
You can place and use piggy banks on ssc servers.

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1059]
You can place and use piggy banks on ssc servers.

**Comment by Enerdy** [comment]
Piggy banks and safes are now sent to us, and we are now storing their contents alongside a player's inventory in the database. Therefore, there is no need to disable them anymore.

**Comment by tysonstrange** [comment]
Oh good to know.

So they're basically built in SSC containers now?

**Comment by Enerdy** [comment]
Yes. This is what we intended to do right from the beginning, but the lack of information and the fact that they were stored strictly on the client made this an impossibility until now.
