### ISSUE TITLE
Cannot ban any treasure bags

### ISSUE THREAD

**Issue by sammyvsparks** [NyxStudios/TShock#1060]
I banned a "Golem Treasure Bag" and changed to guest and figured out that users (without banned item bypass) can still use the bag.

This is for all treasure bags

**Comment by Enerdy** [comment]
There is no way to stop a player from right clicking a Treasure Bag and opening it -- bans only stop you from using items, and right clicking a Treasure Bag does not qualify as using it. Same with pre 1.3 bags such as Goody Bags.

**Comment by Kromara** [comment]
You can ban items within a treasure bag and I have found that if a player does not have permission to use it, then they will not receive that item at all.
