### ISSUE TITLE
Celestial Sigil not functioning 

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1065]
This is still an issue even with latest build from github or unstable.

**Comment by imp0se** [comment]
To elaborate on this:
Upon using the Celestial Sigil, the boss-summon noise is played, and the item is consumed. However, nothing more than that happens.

**Comment by hastinbe** [comment]
For the Celestial Sigil to function properly the following conditions must be met:

* Lunatic Devote and/or Blue Cultist Archer can't be spawned
* Lunar Events (Celestial Towers) can't be active
* Golem must be defeated in your world
* Can't be another boss summoned

**Comment by Kojirremer** [comment]
I have made sure everything from your requirements is correct, and I still can't use the sigil. For some reason it won't even get consumed or make the boss sound.

**Comment by Xetheriel** [comment]
In the standard (non-Tshock) Terraria, the conditions for the celestial sigil are as follows:

- Lunar event must not be active
- No other boss summoned
- Golem must be defeated
- Lunatic Devote and/or Blue Cultist Archer cannot be visible on the screen (not spawned).

Even when I meet all these conditions, the sigil will not spawn the Moon Lord. It makes the boss sound, is consumed, but nothing happens. This works fine in a non-tshock world.
