### ISSUE TITLE
Colorfull chars in the chat

### ISSUE THREAD

**Issue by Strinkor** [NyxStudios/TShock#1067]
Maybe, issue have wrong name, but problem.
If i will write in the chat [c/ff0000:1234] i will get something like that, look at Valkyrie
![-g0-o56ikjm](https://cloud.githubusercontent.com/assets/6019126/9027886/2728044a-396f-11e5-9c15-482421e4a864.jpg)

**Comment by Enerdy** [comment]
Err, that's not an issue. That's Terraria's new chat manager handling the color tag. You can find documentation in how these work both in our wiki's
protocol documentation and Gamepedia's.
