### ISSUE TITLE
Error while running Expert-Crim World 

### ISSUE THREAD

**Issue by deB4SH** [NyxStudios/TShock#1070]
Hey, my Server is currently running into a reproducable Exception. 
Errorlog: http://paste.phcn.ws/?i=1438780318&nrs=1

This error appears everytime somebody runs "right" on the map into the crimson area, dont know which specific section is causing this issue :(

**Comment by WhiteXZ** [comment]
Please upload the world and server files so we can run tests

**Comment by deB4SH** [comment]
Sure here :)
http://cdn.b4sh.de/terraria/bak.tar.gz

**Comment by tylerjwatson** [comment]
oooooh, that's a good one. assigning myself

**Comment by tylerjwatson** [comment]
Please paste the output of `free -h`, `mono --version` and `uname -a`

**Comment by deB4SH** [comment]
hey @tylerjwatson, here is all the info you requested :)
http://paste.phcn.ws/?i=1438782903&nrs=1

**Comment by tylerjwatson** [comment]
Crikey, a 2.6 kernel?  That is some crusty stuff dude. What is this, a rhel6 box?

Can you please update to mono-4.0.2 and report back? Cheers

**Comment by deB4SH** [comment]
Hey it is stable source from debian jessi :P
Updated now on mono-4 from the mono-repositories and the error seems to be gone

thanks for the tip @tylerjwatson  :+1:

**Comment by deB4SH** [comment]
Hey, got the error again in the deep jungle.
http://paste.phcn.de/?i=1438808882
Same World: the issue just moved from the overworld layer to somewhere in the underground:
http://cdn.b4sh.de/terraria/wldupdate.tar.gz (updated world)


mono --version

Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c Wed Jun 24 10:04:37 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

**Comment by tylerjwatson** [comment]
That code is still using sequencing.  Can you please update to the latest bamboo build (> 518) and report back?

**Comment by deB4SH** [comment]
Sry, bamboo build?

**Comment by WhiteXZ** [comment]
http://direct.tshock.co:8085/browse/TERRA-TSHOCK-519/artifact

Grab the tshock_release build from there

**Comment by deB4SH** [comment]
Ok uploaded the 519build from your Atlassian Instance and started the map - seems that everything is working quite well right now. (i dont get the difference between the builds and my own but its working)
In the area that was crashing all the time we found something "cool" 
(http://cdn.b4sh.de/terraria/15_aug_06_terraria-hole.PNG)
Dont know what the generator wanted to do there, sometimes you collide with some invisible blocks which appear after the collision or is this an another bug?

**Comment by tylerjwatson** [comment]
If you are still having problems please open another issue.  Thanks.
