### ISSUE TITLE
tshock server going down when client tries to connect

### ISSUE THREAD

**Issue by rlech** [NyxStudios/TShock#1071]
log: http://pastebin.com/raw.php?i=aTanExMf
os: Ubuntu 14.04.3 LTS (2GB RAM)

I just was setting up my own server to play with but its going down when I try to connect. I have a clean Ubuntu installed and followed this (https://www.reddit.com/r/Terraria/comments/2a2gjn/how_to_run_a_dedicated_terraria_server_on_ubuntu)
tutorial to install it. Anyone have a clue whats wrong? is this a bug in v1.3.0.7?

I tried to connect with the mac version of terraria (beta branch from steam) to my server

**Comment by rlech** [comment]
ok looks like it has something to do with mono. I´m using Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)

**Comment by tylerjwatson** [comment]
Please upgrade to mono 4.0.2 or later, and install the latest version of terraria.  2GB RAM for a VPS likely isn't enough to run a large world on mono.

Cheers!
