### ISSUE TITLE
Is this suppose to happen?

### ISSUE THREAD

**Issue by MuffinNator** [NyxStudios/TShock#1074]
![pic](https://cloud.githubusercontent.com/assets/13706420/9150266/3712fb84-3dd0-11e5-87f8-38763b26861a.png)

**Comment by WhiteXZ** [comment]
Please ensure you're using Mono 4.x or .NET 4.5

**Comment by MuffinNator** [comment]
How do I know that?

**Comment by MuffinNator** [comment]
Thanks WhiteXZ it Worked :+1:
