### ISSUE TITLE
90% of the newly added monsters in Terraria cause the disconnect/kick (Lost Connection) issue.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1076]
We (as in the Teeria LLC Staff Team) have noticed that almost every newly added monster to Terraria ® Version 1.3 (90%) will eventually cause the nearby players to be disconnection with the reason: "Lost Connection".

Upon having Celestial events a dozen of players always kept losing connection to our server and once we tried spawning new monsters in our arena's throughout the use of commands people also started to disconnect including ourselves.

We have even tried spawning 200 pillars which ended up disconnecting more than 50% of our server population. We hope that this issue could be set to a high priority as this is quite a game-breaking bug. If any more information is needed please do not hesitate to ask.

We are running on the latest stable build (4.3.8 API 1.2.1) where the issue still keeps on happening, we also tried running on the unstable build 522 which didn't change a thing at all.

Regards,
Teeria LLC Staff Team.

**Comment by TeeriaLLC** [comment]
Must also note that disconnections also occur by spawning many monsters on the same place, it's just all a little broken I suppose.

**Comment by TeeriaLLC** [comment]
This issue (can) also occurs randomly. With around 40 players online as well.

**Comment by TeeriaLLC** [comment]
Dump file: http://w.teeria.net/banksweb/download1/TerrariaServer.dmp OR https://mega.co.nz/#!NJEwUDDI!grFsVXMrvV49T0wejrEX4eV2QRGa6q5lo7orDDHGZNY
Obviously has to do with SendQ. (Not trying to be rude here.)

**Comment by tylerjwatson** [comment]
I'm going to need to see the source for the plugin "anti-lag".

**Comment by tylerjwatson** [comment]
There are no less than 47 plugins loaded inside this dump file.  Remove them all apart from TShock, and see if the issue persists.

**Comment by TeeriaLLC** [comment]
Anti-lag is not a plugin, it is set in autobroadcast to clear the drops each few minutes.
And I will set that up right now.

**Comment by TeeriaLLC** [comment]
Not that really, when removing every plugin (which I done before) the issue will be gone.

**Comment by TeeriaLLC** [comment]
File updated at http://w.teeria.net/banksweb/download1/TerrariaServer.dmp

**Comment by tylerjwatson** [comment]
Sendq disconnections have been relaxed.  Please be aware that game abuse (spawning mobs to cap, NPCs to cap, and projectiles to cap) will cause the buffers to overload and a console warning every 5 seconds notifying you which players can't keep up with the sheer amount of packets the server needs to send.

If the server can't send them packets because they can't receive them quickly enough, the server will just drop those packets, which in rare circumstances _may_ cause funny behaviour on that client.

**Comment by TeeriaLLC** [comment]
I do get a lot of these messages

[08/16/15 11:35:42] [Server API] Warning: sendq: WARNING: players Oi are lagging behind the server!
[08/16/15 11:36:12] [Server API] Warning: sendq: WARNING: players Oi are lagging behind the server!
[08/16/15 11:36:22] [Server API] Warning: sendq: WARNING: players Oi are lagging behind the server!

Simply because their connection is bad (Around 300ms ping). Will this cause the CLIENT to lag or the SERVER to lag? Because upon doing the Martians event the server lags quite a bit.

Seems like a lot of issues have been fixed here although I do wonder if the Heap error is fixed and secondly the buffer error (Buffer cannot be null) still exists.

**Comment by TeeriaLLC** [comment]
Oh and the AllocAndSet error still occurs, should implement @Patrikkk his bypass for that.

**Comment by Patrikkk** [comment]
@off Don't forget that my "fixes" are like duct-tape patches on a hole on a ship. :P
It doesn't fix the actual issues. just prevents server from crashing coz of nulls.

**Comment by TeeriaLLC** [comment]
Yeah but that's better than nothing @Patrikkk :P Also @tylerjwatson https://i.gyazo.com/98e9857fa9f96d6545eff3c6de2d290f.png is the buffer error.

**Comment by TeeriaLLC** [comment]
@tylerjwatson https://i.gyazo.com/a9e34df2ee62957ed0f722be3d861b43.png One server crash leads to another server crash (Buffer issue)

**Comment by tylerjwatson** [comment]
Forgot to add the null condition. Will fix later

Sent from my Sony Xperia™ smartphone

---- Teeria Legends wrote ----

@tylerjwatson https://i.gyazo.com/a9e34df2ee62957ed0f722be3d861b43.png One server crash leads to another server crash (Buffer issue)

---
