### ISSUE TITLE
Auto /login does not seem to work.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1080]
As stated in the title, each time you log on the server (With auto login enabled in the config) you still have to /login <password>

If this is intentional, please close it.

**Comment by Angelyss** [comment]
Can confirm that this has been an issue for a couple months already. As mentioned above, players still have to login with their UUID or password.

**Comment by Kojirremer** [comment]
I'll third this issue as well. Have tried a few login-related config tweaks and it still happens. The only accounts that don't require to re-login are from the superadmin group. My current login options on the config are:
"RequireLogin": false,
"DisableLoginBeforeJoin": false,
 "DisableUUIDLogin": false,

I wouldn't mind this too much, but the old issue of HP getting resetted when logging in while taking damage is still there.

**Comment by Kromara** [comment]
I'm running into this same issue.

**Comment by hastinbe** [comment]
When the problem occurs see if any exceptions are shown in your server log

**Comment by fizzvr** [comment]
> When the problem occurs see if any exceptions are shown in your server log

**Comment by Angelyss** [comment]
This issue has been resolved in tShock 4.3.11, you guys can close it now!

**Comment by WhiteXZ** [comment]
>@Angelyss: This issue has been resolved in tShock 4.3.11, you guys can close it now!

Thanks for letting us know :)
