### ISSUE TITLE
Item prefixes reset after relog (server restart).

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1081]
Probably has mentioned before but have not seen it pop-up in here.

After relog (Probably after server restart) the user's prefix(es) from his/her(their) item(s) gets reset to normal.

**Comment by flyingmoose** [comment]
I can confirm this as an issue, one of my players keeps having this happen to his character. Does not require server restart, but does seem to occur rarely (7 days play time, with this only started to happen recently)

**Comment by WhiteXZ** [comment]
Tentatively marked fixed
