### ISSUE TITLE
Item duping on Item Frame (SSC).

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1088]
People can spam right click any stackable item on an item frame which will cause items to be duped.

**Comment by TeeriaLLC** [comment]
Here's a gif.

https://i.gyazo.com/f613b56cea51bb7b32a1b8e8c3017647.gif

**Comment by Patrikkk** [comment]
Duplicate of #1039 :P
<3 the gif tho. DUCKS!44!

**Comment by Ijwu** [comment]
Duplicate of #1039 closing.
