### ISSUE TITLE
Tile data (World pieces) Do not load even with a good connection.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1090]
Do not really know how to reproduce this problem yet, it's basically the same thing if you were to be having a bad connection and the world does not load on your end. This does also seem to be happening on the players end but also with a very good connection at random times.

Relogging might cure this issue but it still is weird.

**Comment by tylerjwatson** [comment]
* No dump
* No version information
* No reproduction steps
* "weird" doesn't constitute a fixable problem

**Comment by TeeriaLLC** [comment]
@tylerjwatson version information is obvious, you should know this. 4.3.9, there are no reproducion steps, there's simply random lag, random world pieces not loading and "Found Server" even with a good connection. And I think it is weird, because this should not happen as it never happened before on TShock in ever. And I would create a dump file if the dumping WORKED with a large world.
