### ISSUE TITLE
Found Server for no reason and good internet speed.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1091]
As shown in the image below, the server is running fine with people on it. And my internet is completely fine and I get stuck on found server, and no this has not only been happening to only me.

https://i.gyazo.com/13b42c2f0de04bd976731994b0fa251f.png

**Comment by TeeriaLLC** [comment]
<22:46:46> "Marcus101RR": lol
<22:46:51> "Marcus101RR": found server
<22:46:53> "Marcus101RR": hanging
<22:47:12> "Marcus101RR": its hanging for me

**Comment by darkunderdog** [comment]
Same issue here
