### ISSUE TITLE
Others' bombs, dynamites, sticky bombs & sticky dynamites are invisible

### ISSUE THREAD

**Issue by MasterYoda69** [NyxStudios/TShock#1095]
https://www.youtube.com/watch?v=JRfNAihsxIo
https://www.youtube.com/watch?v=ztYuSw3ThQM

**Comment by flyingmoose** [comment]
I've seen this with fishing poles as well, you can see the other person's bobber animation when they have something on the line, but not the rod, line, or bobber itself.
