### ISSUE TITLE
ItemBans still seem to cause server lag.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1098]
So back in the day we requested Olink to look into the fact that having a lot of itembans caused lag and he told us he "fixed" the issue but it still seems to exist.

No, there is no way to reproduce this except for banning a ton of items and let a lot of guests log into your server. We do not have this issue on the main server because that hold ClearInvSSC which deletes the items from the guest(s).

Running on Bamboo 532 because main release is less stable. Would be nice if someone could look into this, I also have a .dmp file if needed.

**Comment by tysonstrange** [comment]
Tshock will iterate over all your item bans and compare it to the 25 slots of inventory of each player to check for a match.

Don't expect it to be any better if you have like 2000 banned items.

**Comment by WhiteXZ** [comment]
"Tweak some of the itembans code to be less inefficient." was the actual commit message.

If you have lots of group parents and lots of banned items, item bans will be very slow. This is because the code checks a group's permission to see if that group can use the item. If the group doesn't, it checks the group's parent permissions. If the parent can't, it checks the parent's parent, etc.

As @tysonstrange stated, it will do this for every single inventory slot

**Comment by TeeriaLLC** [comment]
Except for the New slots that were added in the game, but my SSC server has
far more groups and banned items than my nonSSC server which seems odd to
me why it would lag.
Op 26 aug. 2015 06:32 schreef "White" <notifications@github.com>:

**Comment by tysonstrange** [comment]
Errr, well if its you're non-SSC server thats lagging, its clearly not item bans.

If it IS your SSC Server thats lagging, then you just explained why it's slow...

I ahve 800 groups and 200 item bans, my server doesnt lag at all.

**Comment by TeeriaLLC** [comment]
Yeah it is really confusing me why it is lagging, I am looking everywhere for issues but I think I'm quite far away from finding the issue.

**Comment by tysonstrange** [comment]
Could have something to do with running several terraria servers on the same VPS.

Isolate your server and remove all plugins.

**Comment by tylerjwatson** [comment]
Please do not post issues until you have a concrete way to reporoduce it.
