### ISSUE TITLE
[SSC] Passive SSC

### ISSUE THREAD

**Issue by Ijwu** [NyxStudios/TShock#1100]
```
darkunderdog [12:56 PM] 
Is there a plugin for SSC lets people import their Character data from their file into the server?

darkunderdog [1:00 PM]
I like SSC for plugins that use SSC like Jumppads and Forcefields - But also want to offer the flexability for people to keep their character inventories.

darkunderdog [1:00 PM]
Is this possible / does a plugin exist to do this?

ijwu [1:03 PM] 
It is possible, but not in a plugin

ijwu [1:03 PM]
The issue is that they have to somehow get you their player file

ijwu [1:03 PM]
Which is simply not possible in a plugin or within Terraria

ijwu [1:03 PM]
It is possible to have your own service which allows players to upload their file (to a website for example) and then their data is inserted into your DB

darkunderdog [1:07 PM] 
@ijwu: So I know there are plugins like /loadout that @popstarfreas uses that takes a users character data and saves it to a database so they can switch out different loads. couldn't something be implemented prejoin to auto save there character data into the database then use that for SSC?

ijwu [1:07 PM] 
Hmm, didn't think about that. Yeah, possibly.

ijwu [1:07 PM]
I'd have to take a look at SSC more in depth

ijwu [1:08 PM]
But it might be possible to have SSC not clear a person's inventory on join

ijwu [1:08 PM]
and instead just track what they joined with
```

**Comment by tysonstrange** [comment]
Why don't you just turn off SSC or use the Ignore SSC perm?

**Comment by darkunderdog** [comment]
darkunderdog [1:00 PM]
I like SSC for plugins that use SSC like Jumppads and Forcefields - But also want to offer the flexability for people to keep their character inventories.

also Ignore SSC perm while works to allow people to use their Character Inventory it does not allow people to make any changes to their Character Inventory - For example if in game you get a few items then exit - when you come back those items are gone.

**Comment by bippity** [comment]
The awkward moment when you thought this feature already existed ._.

**Comment by nicatronTg** [comment]
Part of #929 maybe? Either way, flagging this as PR wanted too.

**Comment by nicatronTg** [comment]
Unfortunately, this issue title didn't properly help convey what really needs to happen for this fix, which is a semi-passive SSC system with bi-directional data flow. I detailed this more in #929 but I'm going to say that #1321 is still an adequate fix for most server owners, as it enables characters to have their SSC data imported when they join, which lets them start "where they were prior to joining" while still keeping the benefits of SSC.

**Comment by ProfessorXZ** [comment]
I believe @DogooFalchion handled this a few months ago.
