### ISSUE TITLE
[SSC] People randomly losing items for no reason (mainly weapons)

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1102]
People claim to keep losing items with no reason, I checked the drop logs and they have not dropped any items as well. I have no idea to reproduce this because it has never happened to me but this isn't the first time people report this to me so it should be looked into.

Running on TShock Bamboo Build #535.

**Comment by TeeriaLLC** [comment]
People have also claimed that sometimes when items are "suddenly" lost they sometimes just appear back which will end up them having duped items, this could be caused by player/server lag/SendQ.

**Comment by tylerjwatson** [comment]
Please do not post issues until you have a concrete way to reporoduce it.

**Comment by TeeriaLLC** [comment]
Good luck finding out how to reproduce this broken feature.
