### ISSUE TITLE
Using Chat Above Heads breaks Item tags in names

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1104]
If a player prefix or suffix contains an item tag, eg [i:50], the image of the item is only seen by that player, all other players just see the actual text "[i:50]" when Chat above heads is enabled.

Reason, it seems, is because normal chat uses the following code for chat:
Utils.Broadcast(text, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);

Where, chat above heads does this:
tsplr.SendMessage(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);
TSPlayer.Server.SendMessage(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);

Replacing nothing but those 2 lineswith the following seems to fix this without affecting the actual chat above heads:
Utils.Broadcast(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);

Can this please be updated?

**Comment by Kromara** [comment]
Chat Above Heads is actually working at all now!? O.O
It would always mess up chat colors for me during 1.2.4.1 when I last
attempted to use it.

**Comment by TeeriaLLC** [comment]
The chataboveheads function works (and worked) fine for me (ever since). So do the tags in chat above heads.

Proof shown in image below.
https://i.gyazo.com/229ae32cbce8fcafcb893d2fceb9ffb9.png

Format used:
  "ChatFormat": "{1}{2}{3}:\r  {4}",
  "ChatAboveHeadsFormat": "{1}{2}{3}",

**Comment by Kromara** [comment]
I'll have to look into this when I get back home.

**Comment by tysonstrange** [comment]
@TeeriaLLC read the op again.

**Comment by TeeriaLLC** [comment]
You mean basically this, where the user him/herself can see the tag/color.
http://img.prntscr.com/img?url=http://i.imgur.com/TVQ2XBi.jpg

And we see this;
https://i.gyazo.com/1ed12d1f334272974af4d213d335ef4c.png

**Comment by nicatronTg** [comment]
@ProfessorXZ closer at all to anything on this and the other issue?

**Comment by nicatronTg** [comment]
_I am assigned to this issue for monitoring/oversight but am not actively working this issue._

**Comment by ProfessorXZ** [comment]
@nicatronTg No. I've tried numerous ways to fix this over the past few months and nothing worked. So unless someone actually has an idea on how to fix this I think the issue should be closed because it's something we can't handle due to how Terraria works.

**Comment by nicatronTg** [comment]
Okay.

**Comment by tysonstrange** [comment]
yeah, confirmed a while ago that this can't be fixed because of the way the chat above head packet works with tag parsing.

would need to be "fixed" in Terraria itself.
