### ISSUE TITLE
Crash if old worlds are in the player's world folder

### ISSUE THREAD

**Issue by Hexicube** [NyxStudios/TShock#1105]
Server crashes during the sorting logic when populating the existing world list. Issue is caused by a null being passed into the world list, which stopped happening when I removed all the non-1.3 worlds.

Should be easy to re-create, just start an old server and generate a world, then start the new one.

**Comment by nicatronTg** [comment]
[This is not a TShock/TSAPI problem](https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/).
