### ISSUE TITLE
I got this message when my friend joined!

### ISSUE THREAD

**Issue by TemplatePlays** [NyxStudios/TShock#1106]
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException; An attempt was made to access a socket in a way forbidden by its access permissions 198.245.62.104:80 Please help!

**Comment by Ijwu** [comment]
You may not host your server on Port 80 with default user privileges it would seem. Try hosting your server on a more conventional port such as 7777.
