### ISSUE TITLE
multiplayer loopback 127.0.0.1 stuck connecting

### ISSUE THREAD

**Issue by spazfu** [NyxStudios/TShock#1107]
After booting tshock 4.3.9 and attempting to join via loopback with terraria 1.3.0.8 I get stuck connecting to server. There is no firewall enabled and I'm using loopback interface.  Deleting tshock api from plugins folder allows joining the server, obviously without any tshock capabilities.
<img width="682" alt="screen shot 2015-09-09 at 6 40 57 pm" src="https://cloud.githubusercontent.com/assets/5437365/9778263/f18e0272-5722-11e5-99ab-814904d45811.png">
![2015-09-09_00001](https://cloud.githubusercontent.com/assets/5437365/9778266/f4aee19c-5722-11e5-8e8e-0f89f0257ca0.jpg)

**Comment by Ijwu** [comment]
Looks like you're on mac and running mono. If I may ask, preemptively, what OS and Mono versions are you running?

**Comment by spazfu** [comment]
<img width="698" alt="screen shot 2015-09-10 at 6 37 24 pm" src="https://cloud.githubusercontent.com/assets/5437365/9805200/0f02298c-57eb-11e5-8cf9-38055f7ec7af.png">
<img width="682" alt="screen shot 2015-09-10 at 6 36 49 pm" src="https://cloud.githubusercontent.com/assets/5437365/9805206/1f050a0c-57eb-11e5-8cb0-ee79220cee7e.png">

**Comment by 916253** [comment]
I also have this identical issue and have not found any solutions other than simply using a windows pc. any help would be appreciated.

**Comment by tylerjwatson** [comment]
Hi, please run TShock with:

`$ mono --debug --trace=E:ALL TerrariaServer.exe`

And try and replicate the problem, pasting the output here.

Cheers,
T.

**Comment by nicatronTg** [comment]
@916253 were you able to reproduce this issue and or get better debug output for us?

**Comment by WhiteXZ** [comment]
Closing due to lack of feedback. Related discussion continues in https://github.com/NyxStudios/TShock/issues/1143
