### ISSUE TITLE
Everything breaking TShock error.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1109]
Running latest TShock Bamboo 537. No way to reproduce it has happened quite a lot and fills the serverlog to where my SSD cannot longer store and breaks everything as whole.

Please fix this issue.
https://i.gyazo.com/c5f7ea2146e3890167362a30359f8f98.png

**Comment by TeeriaLLC** [comment]
Or make an option to turn off the damn ServerLog.

**Comment by TeeriaLLC** [comment]
And YES it says SEconomy by Wolfje but as Wolfje mentioned it's TShock being a piece of crap and it shows SEconomy because it's being loaded first.

**Comment by Enerdy** [comment]
I'm sorry, but I'll have to be rude: please do NOT run TShock Bamboo Builds right away and tell us to fix it asap.

In other news this does seem interesting, but unless someone else can reproduce it we probably won't be investigating this issue right now.

**Comment by tylerjwatson** [comment]
Duplicate of #1108
