### ISSUE TITLE
OnSecondUpdate() Spam still persists to exist.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1110]
As shown in the image below, it's kinda being spammy.

https://i.gyazo.com/a7738a7cfc12054536668011dca565dc.png

**Comment by TeeriaLLC** [comment]
Nevermind, I saw the config option.

Although the config option does not seem to work, I set the config option to   "DisableSecondUpdateLogs": true, and it still shows up in the cmd.

Unless this is meant to be like that and not logging it in the log file.

**Comment by WhiteXZ** [comment]
DisableSecondUpdateLogs only stops it from logging to file. Messages will still be sent to the console
