### ISSUE TITLE
Players in Temp groups with ignore ssc perms still save over their SSC character

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1112]
If you're running an SSC enabled server and move a player into a temp group that has the permission ignoressc the player's inventory is still periodically saved over as per the SSC Config.

The SSC Save interval checks the following:
if (player != null && player.IsLoggedIn && !player.IgnoreActionsForClearingTrashCan)

IgnoreActionsForClearingTrashCan is set on login if the player has the ignoressc perm, but not periodically when the ssc save occurs.

Coupld the save internal also be set to check for ignoressc perms?

**Comment by tysonstrange** [comment]
if (Main.ServerSideCharacter && (DateTime.UtcNow - LastSave).TotalMinutes >= ServerSideCharacterConfig.ServerSideCharacterSave)
			{
				foreach (TSPlayer player in Players)
				{
                    // prevent null point exceptions
                    if (player != null && player.IsLoggedIn && !player.IgnoreActionsForClearingTrashCan)
					{
                        if ((player.tempGroup != null && player.tempGroup.HasPermission(Permissions.bypassssc)) || player.Group.HasPermission(Permissions.bypassssc))
                        {
                            TShock.Log.ConsoleInfo("Skipping SSC Backup for " + player.Name);
                            continue;
                        }
						CharacterDB.InsertPlayerData(player);
					}
				}
				LastSave = DateTime.UtcNow;
			}

**Comment by tysonstrange** [comment]
Using this code on my server live terraria.tls.id.au and it seems to be working fine.

I use this because of the minigames on my server, I add users to tempgroups and set new inventories dependant on the minigame type and I dont want it overriding the players ACTUAL inventory.

So far its running as expected, the main reason is to prevent inventory loss on server crash while a game is running

As for disconnect/logout, the minigame players dont ahve permission to log out and my minigame plugins handle backup/restore of inventory On game join/end as well as leaving the server, similar to the way the Invsee plugin works.

**Comment by tysonstrange** [comment]
Similar code should be added to savessc command and handled when using /exit

**Comment by Ijwu** [comment]
Thanks for the report an PR. Just letting you know that we're not ignoring you, we've all just got a massive amount _less_ free time since school started for half of us and whatnot. If I get home and remember I'll get right onto checking this out and checking out your PR.

**Comment by tylerjwatson** [comment]
Willing to go +1 after someone else reviews to prevent conflict of interest
