### ISSUE TITLE
Fishing (Modified Terraria source.)

### ISSUE THREAD

**Issue by stefnotch** [NyxStudios/TShock#1113]
Issue: You can modify the Terraria source to get this result: http://steamcommunity.com/profiles/76561198236886004/screenshot/683775065702096390

A way of "fixing" it: Add a check to see if the player caught a fish/crate/etc. If yes: Everything is fine. If no: He cheated...

**Comment by WhiteXZ** [comment]
We can't stop hacked clients from spawning items, and terraria never sends a packet to tell us what someone has fished. Can't fix, sorry

**Comment by TeeriaLLC** [comment]
You can actually tell Re-Logic to look into this shit, because their security is shit.
