### ISSUE TITLE
SSC doesn't work in newest Bamboo build.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1115]
Just point it out there that this should be fixed, SSC is not being recognized in the latest Bamboo build.

**Comment by TeeriaLLC** [comment]
Please fix this ASAP :/

**Comment by TeeriaLLC** [comment]
So basically I think SSC works (somehow?) but it keeps resetting the players inventory to the standart three copper items. So I suggest everyone to not use Bamboo until this game breaking bug is fixed.

**Comment by TeeriaLLC** [comment]
@WhiteXZ @tylerjwatson

**Comment by tylerjwatson** [comment]
Stop posting issues for unsupported bamboo builds.
