### ISSUE TITLE
New branch for bleeding edge

### ISSUE THREAD

**Issue by hastinbe** [NyxStudios/TShock#1130]
I want to propose a new branch for bleeding edge, where greater access and less strict requirements can be given to merge with little to no guarantee. This way we can reduce pull requests from going stale in the general-dev branch while maintaining its integrity, and get what we have out there for trial. I realize many are focusing on Orion so not much activity is happening for TShock or TSAPI, but for the rest of us who wish to continue on without maintaining our own separate fork and losing access to the existing userbase it would be greatly appreciated.

**Comment by nicatronTg** [comment]
I don't understand your reasoning, at all really. We don't approve merges because we have guidelines. An new branch isn't going to make us merge anything any faster.

**Comment by hastinbe** [comment]
I will explain things from my point of view. TShock appears to be on the brink of inactivity as nobody seems to be doing much of anything with it, I'm guessing because eyes are on Orion. Because of that there's little to no feedback on pull requests that aren't small bug fixes. I need pull requests to be tested, but there are no testers because nobody that isn't a maintainer are manually go into the pull requests and try them out. A bleeding edge branch can solve that.

**Comment by nicatronTg** [comment]
No, because nobody's going to setup a CI for random changes that haven't been approved. If you want people to test your work, provide a build and document how it won't break other things.

**Comment by nicatronTg** [comment]
For the record, I don't make all of the decisions. Closing all of your PRs based on my response just shows a lack of willingness to collaborate to come to a constructive solution.

**Comment by hastinbe** [comment]
Good luck with your project, I'm moving on. Thanks guys
