### ISSUE TITLE
SSC doesn't save data

### ISSUE THREAD

**Issue by MythixDino** [NyxStudios/TShock#1132]
When using the ssc (server-side-character) feature, nothing is saved when I leave the server and join again. (I just get an empty inventory with the starting items) I don't know why this is happening, either I'm doing something wrong or it's a bug in the system itself.

**Comment by nicatronTg** [comment]
Please post your help request on the forums for a prompt, knowledgeable response! Read the ultimate help guide, and post away. Alternatively, ask us on Slack!
