### ISSUE TITLE
TSPlayer.SetTeam doesnt work properly?

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1134]
It seems to change the players team client side... but it takes a few moments before the server acknowledges the team change and updates...

Example, I have some mini games on my server, once a game starts the teams are set to red/blue, ect.

First 15~ seconds of the match, everyone will jsut be on neutral team before the game realises they're all on team red/blue..

Can be tested by joining 2 players to a team and noice they can't see each other (the coloured name above head to indicate same teams)

I think it's something to do with the SendData packet it sends not being correct...

**Comment by WhiteXZ** [comment]
@tysonstrange could you test (this)[https://dl.dropboxusercontent.com/u/98954663/ShareX/2015/11/TShockAPI.dll] TShock dll please? Should fix both this and #1131

**Comment by tysonstrange** [comment]
how much dmg does butcher do now?

**Comment by WhiteXZ** [comment]
```C#
Main.npc[i].life + (Main.npc[i].defense*0.5)
```
i.e., all of their current hitpoints

**Comment by tysonstrange** [comment]
Seems to have fixed teams...

what did you change?
