### ISSUE TITLE
TShock crashes when player destroys a tile

### ISSUE THREAD

**Issue by mscansian** [NyxStudios/TShock#1135]
I'm trying to run a Terraria server on a EC2 micro instance. I have set-up an Ubuntu Server 14.04 and a 4GB swap file (micro instances don't have enough ram).

Every time I connect and start digging (or cutting trees), after a few blocks the server crashes, but it does not happens if I just walk around. The only change I made to the config file was setting a password and changing the TileKillThreshold to 1000.

Machine: AWS EC2 micro instance
OS: Ubuntu Server 14.04 LTS
RAM: 0,5GB + 4GB swap
World: Medium world (generated using TShock server)
TShock: v4.3.11

```
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_obj (intptr,intptr) <0xffffffff>
  at (wrapper alloc) object.AllocSmall (intptr) <0xffffffff>
  at TerrariaApi.Server.TileProvider.GetTile (int,int) <0x00035>
  at TerrariaApi.Server.TileProvider.get_Item (int,int) <0x0009e>
  at Terraria.WorldGen.UpdateWorld () <0x06187>
  at Terraria.Main.Update () <0x07ebe>
  at Terraria.Main.DedServ () <0x0272d>
  at Terraria.ProgramServer.InnerStart (string[]) <0x00223>
  at Terraria.ProgramServer.Main (string[]) <0x00018>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	mono() [0x4b73d8]
	mono() [0x50f13b]
	mono() [0x423d22]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7fe0dc223340]
	mono() [0x5d6487]
	mono() [0x5d93d2]
	mono() [0x5dd6f3]
	mono() [0x5de3b9]
	mono() [0x5f4719]
	mono() [0x5f47e4]
	[0x415bacae]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted (core dumped)
```

**Comment by tylerjwatson** [comment]
Hi,

Swap files on Linux are not a get-out-of-ram-free-card - they do not modify the amount of physical memory the machine has, and the kernel may still deny a process memory at its own prerogative. 

 Mono is crashing because the kernel is denying the garbage collector memory. 

On Linux, we don't recommend you run TShock with under 2GB of physical RAM.

**Comment by AndrewGraber** [comment]
Question: is there a way to allocate more ram specifically to the process?

**Comment by nicatronTg** [comment]
@AndrewGraber you could define `MONO_GC_PARAMS` as described [in this stackoverflow post](http://stackoverflow.com/questions/19362898/mono-gc-max-heap-size-isnt-documented-is-it-safe-to-use-in-production) but generally this type of thing shouldn't be necessary at all. If you have enough physical RAM, Mono will happily allocate it.
