### ISSUE TITLE
Hardened Sand (Possible permission issue)

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1138]
Corruption / Crimson / Hallowed counterpart of Hardened Sand isn't changing back to normal when contaminator / purification powder is used upon it. ( It will change back during world reset ) [ MIGHT only occur only in our server ].

However, when a "superadmin" used it it changed back, when a normal user used it, it would not change. As if the Hardened Sand block requires special permission. Be advised, other blocks around do change biomes by the users. Leading to believe it may be a permission issue, or another issue in tshock definition regarding a user changing block types.

![image](https://cloud.githubusercontent.com/assets/8344293/11453691/8fda4334-95e2-11e5-90ad-e3be9d04b9ba.png)

**Comment by WhiteXZ** [comment]
Are you using any plugins that 'blacklist' a tile such that normal users cannot place/destroy it?

**Comment by Marcus101RR** [comment]
They can replace and destroy it, no plugin is used that controls block placement, and I am not using TShock BanItem to prevent them from placing, destroying or using these blocks. Neither is TileBan using their Ids.

I'll continue to attempt to figure out why it won't change their biomes.

**Comment by Raventhalos** [comment]
Little experimenting, found that **tshock.ignore.sendtilesquare** is what is preventing the hardened sand from converting.

**Comment by WhiteXZ** [comment]
Thank you @Raventhalos 
I'm going to assume this issue is only effecting sand because of the nature of the grief checks against sand that TShock has. It's something I can look in to, but I doubt it will be 'fixed'

**Comment by nicatronTg** [comment]
Honestly not sure what to say about this. @WhiteXZ should this remain open?

**Comment by nicatronTg** [comment]
_I am assigned to this issue for monitoring/oversight but am not actively working this issue._
