### ISSUE TITLE
Request: /setdungeon command to change cultists/old man's spawning area

### ISSUE THREAD

**Issue by Kojirremer** [NyxStudios/TShock#1140]
Just what the tin says. I want to be able to move the dungeon map point to somewhere a bit more difficult to reach, since just anybody can go and cause the lunar events nonstop.

I had in mind something like the already-existing /setspawn command, but that deals with the dungeon location instead (just the location point, not a whole freshly-generated dungeon).

TEdit has this feature, but it's a bit hard to use on already-live maps, and bad things happen if you try to use TEdit on InfiniteChests-powered maps.

**Comment by loohney** [comment]
Would love to see this too. 
We had players triggering the lunar event over and over again which is actually pretty annoying.

I've prevented this by selecting the region where the cultist spawns with worldedit and filled the selection with a solid block. He won't spawn anymore, also you can make this block of maybe dirt look naturally and creating a new entrance into the dungeon manually.
It's not a fix but it does the job.

**Comment by Marcus101RR** [comment]
Moving the spawnpoint of dungeon won't do much good, as you would need to build a custom dungeon for cultists to spawn properly. That in fact, means unmodified dungeon walls...

**Comment by Kojirremer** [comment]
And what would be the problem? WorldEdit can set unsafe dungeon walls. I've already tested moving the spawn point with TEdit and it works, but as I said before, it's not easy to do when the world is already live (and "tainted" by InfiniteChests).

**Comment by Marcus101RR** [comment]
My world Regeneration moves dungeon spawn, and loads the dungeon at the new location. Cultists work, so yes, if you move the dungeon you need to move the physical dungeon too.
