### ISSUE TITLE
[Bug] Spear Trap does not function

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1149]
This is the oddest thing I have seen, Spear Traps the one used from the Temple do not function at all when hitting switches or timers. I am using this current TShock build:

TShock Build: Build #575
Completed 28 Dec 2015, 4:00:32 PM – 3 days ago

I would like to know if anyone else is having this issue at this time? I'll double check my version and update if needed.

**Comment by tylerjwatson** [comment]
As someone who doesn't play the game, what exactly do I need to do to reproduce this?

**Comment by Marcus101RR** [comment]
Nevermind, fixed, I need to stop running a server and replacing the module when its running. It was running an older version. Argh. Spear Traps work. Close this crap.
