### ISSUE TITLE
Problem with loading worlds with Mono in OS X El Capitan

### ISSUE THREAD

**Issue by XeserSpectr21** [NyxStudios/TShock#1150]
Hello.
I am Xeser, a hardcore TShock user. :)

I recently upgraded to OS X El Capitan, and I do understand that Apple reorganized their Terminal system, but this issue is making TShock nearly impossible to use.

I use the Mono framework, and ever since Apple did the reorganization, Mono was broken, BUT I managed to fix it. (Hard work.)

I know one thing, Mono is working, and my Terminal WILL BOOT TShock but there is still an existing problem, this:
![screen shot 2016-01-01 at 5 57 00 pm](https://cloud.githubusercontent.com/assets/16512760/12072792/183305ac-b0b1-11e5-8fd3-e439413ca452.png)

First things first, I don't understand it.

This is the problem that has held me back for SO LONG. I use TShock in the way it came, and I have made no modifications to the server config or anything with it.

Thank you.
-XeserSpectr21

**Comment by tylerjwatson** [comment]
I unfortunately don't have el cap because of how terrible it performs. 

@deathcradle - can you help me out bro? Run a vanilla version of tshock on el cap and see what it does? Cheers

**Comment by nicatronTg** [comment]
@tylerjwatson cannot reproduce?

![screen shot 2016-01-01 at 10 19 13 pm](https://cloud.githubusercontent.com/assets/532647/12073308/bf42dcc2-b0d5-11e5-8457-d5c10f25c145.png)
![screen shot 2016-01-01 at 10 18 59 pm](https://cloud.githubusercontent.com/assets/532647/12073309/bf44eaee-b0d5-11e5-8b2b-3edf595e59d0.png)
![screen shot 2016-01-01 at 10 18 07 pm](https://cloud.githubusercontent.com/assets/532647/12073307/bf42b738-b0d5-11e5-83be-943d6e563e63.png)

**Comment by XeserSpectr21** [comment]
That's weird. Is it my path? :\

**Comment by nicatronTg** [comment]
@XeserSpectr21 see here: http://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

**Comment by nicatronTg** [comment]
[Closed, but feel free to ask more questions about running in OS X here]

**Comment by XeserSpectr21** [comment]
I am still getting the same error, and what exactly should I be doing there? I really don't understand.

Maybe this will help?
![screen shot 2016-01-02 at 12 05 17 pm](https://cloud.githubusercontent.com/assets/16512760/12075777/2bb06c1c-b149-11e5-897a-57ae3e48df94.png)

I cannot get it to run because of this exact same error every time now. Is it the system or something else?

**Comment by DeathCradle** [comment]
@tylerjwatson I get the same results as @nicatronTg 
However, looks like @WhiteXZ may have answered this before: https://tshock.co/xf/index.php?threads/tshock-crashes-on-start.3902/#post-41475

![screen shot 2016-01-03 at 8 46 18 am](https://cloud.githubusercontent.com/assets/776327/12076407/847dc418-b1f6-11e5-8f95-8db8c2d7502d.png)
