### ISSUE TITLE
Stuck on Found Server Issue (Includes DMP file)

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1153]
tSHock Version: TShock 4.3.12 for Terraria 1.3.0.8 (API v1.22)
Dump File: http://74.91.127.178:8080/FastDL/TerrariaServer.DMP
ZIP FILE: http://74.91.127.178:8080/FastDL/TerrariaServer.rar
Cause: Unknown, we were online and the whole server stopped, then we logged out and back in, it was stuck on Found Server.

**Comment by nicatronTg** [comment]
![screen shot 2016-01-09 at 7 33 05 pm](https://cloud.githubusercontent.com/assets/532647/12219604/d605b74e-b707-11e5-9e28-1675239664d2.png)

**Comment by nicatronTg** [comment]
(Please upload dump file elsewhere, thanks!)

**Comment by tylerjwatson** [comment]
And do us the courtesy of compressing it, please. Nobody wants to download 1.1GB in lieu of a 90MB zip being available.

**Comment by Marcus101RR** [comment]
You can ignore the Google message, or you can just believe it. I did my job and followed the requirements to make this report to the T. Can't be bothered to upload it somewhere else cause everything requires an account. Provide me with some site and I'll gladly do it, if its free and no registration or size restriction. That is why I chose HFS.

Choices:
@nicatronTg Just click the bottom option "visit this site". Its HFS, yes its, you know who, but seriously if I had my own money and vps, I would gladly do it. I don't have that luxury sadly.

@tylerjwatson Compressed, choose the rar file.

**Comment by tylerjwatson** [comment]
If you can't be bothered to follow instructions I can't be bothered to look at the issue. Closed.
