### ISSUE TITLE
Drill Containment Unit not breaking blocks

### ISSUE THREAD

**Issue by BStorm888** [NyxStudios/TShock#1155]
The drill containment unit will not break certain blocks in certain biomes, such as ebonstone in the corruption or sand in the desert.

However all blocks can be broken if a pickaxe is held while in the drill.

**Comment by tylerjwatson** [comment]
Isn't this by design?  The DCR inherits the properties of the object you are holding?

**Comment by WhiteXZ** [comment]
I believe in testing many months ago we discovered that a vanilla DCU can break any (or almost any) blocks regardless of equipped item, but I will have to retest to confirm

**Comment by Marcus101RR** [comment]
So basically we need to determine if this is a vanilla issue or tshock issue? I'll test it out in my spare time.

**Comment by Xetheriel** [comment]
This is a tshock issue. In the steam version on a non-tshock environment (single or multi-player), the drill containment unit will break any block no matter what I'm holding in my hand. On TShock, I have to hold a pickaxe in order to get through certain blocks. Definitely a difference in behaviour.

**Comment by WhiteXZ** [comment]
Thank you for the feedback. Should make this easier to fix

**Comment by Marcus101RR** [comment]
This could also be related to #1138

**Comment by Xetheriel** [comment]
Confirmed, this is fixed. Thanks, guys! :D
