### ISSUE TITLE
Adding sub ID's to tshock.

### ISSUE THREAD

**Issue by loohney** [NyxStudios/TShock#1156]
I would love to see sub ID's for monsters and other stuff like banner buffs who don't have an internal ID from vanilla tshock so you can summon them over the sub ID for example instead of writing: /sm "red slime" you can just do /sm 1:3.

So plugins that dont support using monster or item names as the ID in the configs using the sub ID's instead for monsters without an internal ID.

In my opinion it's a core feature, sure you can probably create a third party plugin for this but you also have to modify the other plugins to accept the sub ID's or item names. So adding sub ID's into tshock would be a lot more easier.

Thank you!

**Comment by WhiteXZ** [comment]
Any plugin that doesn't support a monster name in its config would not be able to accept something like "1:3" either. Change the plugin's config to take strings rather than ints, then use the monster name
