### ISSUE TITLE
Announcing who summoned an eclipse always shows an empty !

### ISSUE THREAD

**Issue by Kojirremer** [NyxStudios/TShock#1158]
It's a really minor issue that I guess everybody has noticed by now, but since it does not appear to be submitted, here it goes.

When annonymous boss invasions are set to false, whenever people use a boss/invasion spawner the game shows a notification like:
"xxxx has summoned the Eye of Cthulhu!"
...right? But when you use the solar tablet, you instead get a blank where the event name is supposed to be:
"xxxx has summoned the !"
It's not really important since immediately below, the "A solar eclipse is happening!" line will appear, but it's good to know just in case.

**Comment by nicatronTg** [comment]
Thanks for reporting this bug!
