### ISSUE TITLE
[Regions] Statues & Mannequins calculated wrong

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1159]
TShock Bamboo Build: #585
Issue: When attempting to place Mannequins/Statues on a area that is not protected, but are not atleast 1 blocks above the protected area will fail.

RED AREA: Protected Region
GREEN AREA: Unprotected Region Z'd over Protected Region
YELLOW AREA: Placing statue or Mannequin on this platform shows error message of protected region, but allows you to place it anyway. SIDE NOTE: Mannequin becomes indestructible after placement, and must remove the block standing on it to remove it!
BLUE AREA: This height is safe for placing statues and Mannequins without error message.

FINAL NOTE: Attempting to place either of these directly on the asphalt platform which is protected, results in automatic destruction of the placed statue or mannequin.

Picture:
![image](https://cloud.githubusercontent.com/assets/8344293/12764825/af8ea880-c9c9-11e5-93ce-49c0e4627190.png)

**Comment by WhiteXZ** [comment]
Is this still an issue?

**Comment by Marcus101RR** [comment]
Yes, this is still an issue. User's still cannot place them directly on the platforms. The screenshot is still valid that explains where one can place them / remove them.
