### ISSUE TITLE
Item duping with item update packes and latency?

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1162]
I dont know why or how this happens... but I can't seem to get it to do it on a local lan server with jus a few local clients, but can on my live server. Both exactly the same.

https://www.youtube.com/watch?v=aKas2GLnXHQ

**Comment by Gummin** [comment]
I watched the video a couple times and frankly didn't understand it, I came back to check it out again and now It's been removed.
We need to know at least what happened and what you/others were doing when it happened.

**Comment by sammyvsparks** [comment]
May be something to do with her server itself. Since LAN cannot achieve it.

**Comment by Gummin** [comment]
Well you cannot perform the item frame duplication bug on LAN, or at least with extremely low ping, but having a normal or above ping will have it work just fine so I'd say it isn't too far fetched.
I remember in the video you were falling, there are a lot of issues with off-screen entities.
Like in expert mode mobs off-screen will duplicate dropped coins into the thousands of platinum if left there long enough, and bombs will supposedly not explode properly off-screen .
Setting RangeChecks to false seems to fix the issues I mentioned above.
Could possibly be related?

**Comment by tysonstrange** [comment]
i dont know, might be that there jus wernt any other player slots needing updating or whatever..

Basically... find somewhere with a big drop, throw an item, let it fall off screen, quickly jump off, fall about 1 screens length, catch the item on the way down, fall another couple screen lengths or further than the item would have been if you didnt catch it falling down, then when you stop falling, the same item feel falling down and appears again

noticed this if there are items on the ground off screen and you're using a hacked client with infinite grab range (Where items slowly drift towards you) items drift in, you pick them up, then they suddenly apepar again and start drifting towards you..

**Comment by tysonstrange** [comment]
heres some vidios i made

one using pickup range hacks to simulate the behaviour, another using the drop item method (and latency? idk)

Couldn't get it to happen in vanilla terraria with either method...

https://youtu.be/7Q77lJ8W9IE
https://youtu.be/AETa41ssJ_M

**Comment by Gummin** [comment]
Quite strange behavior like I've never seen before, I'll have to test it tomorrow morning.

**Comment by tysonstrange** [comment]
sure

i just used these client hacks coz its a lot easier to reproduce than having a bunch of ppl on the server and falling... easily grabs from off screen this way.

**Comment by Gummin** [comment]
I am unable to test this in the proper conditions unfortunately, and it is currently impossible for me to experience lag on my own server without intentionally creating artificial lag, which oddly enough proves difficult.
Using "client hacks" is questionable but I would assume would hardly affect the results in this case.

If someone could try this but with RangeChecks set to false that would be lovely.
Although I doubt that will fix a issue like this.

**Comment by ProfessorXZ** [comment]
Is this still an issue with the latest bamboo? The video isn't available anymore.
