### ISSUE TITLE
Unable to chop tree, break tile.

### ISSUE THREAD

**Issue by Strinkor** [NyxStudios/TShock#1164]
When I or someone else trying to chop tree - tree dissapears for a monent, drops Wood Block and appers again. Breaking block doesn't drops block. No exceptions or errors.
Rollback to older releases, like 4.3.9 don't have such problem.
Tshock: latest
OS: Windows Server 2012

**Comment by Strinkor** [comment]
So, can someone help me?

**Comment by nicatronTg** [comment]
Are you in a spawn protected area, not logged in, etc?

**Comment by Strinkor** [comment]
Logged in, away a from spawn protected area, now i trying unstable build, it seems fine. I think problem in a buggy WorldEdit plugin, sorry for disturbing.
