### ISSUE TITLE
Other People cant join my server

### ISSUE THREAD

**Issue by SilentDeathTheSeal** [NyxStudios/TShock#1165]
ISP: Sky
Tshock version: 4.3.12.0

I have Port forwarded to 7777 and have added the firewall rules,
Yet people still can't join and when I check if the port is open or not it shows this:
https://i.gyazo.com/d6329f63a4705376a2714577e7bb9add.png

I can provide more pictures if needed

**Comment by WhiteXZ** [comment]
If other 3rd party services are having problems with accessing your IP/checking your port, this is not a TShock issue.
Make sure your IP is accessible and your port is open

**Comment by SansThePunslinger** [comment]
And how do I do that? I mean checking if my IP is accessible and if my port is open.
