### ISSUE TITLE
I keep getting the same error

### ISSUE THREAD

**Issue by Soudon** [NyxStudios/TShock#1167]
I am using the terraria leveled tshock plugin works fine until I add a plugin I want to use permabuffs and or essentials+ but they both throw the following error I have a backed up copy of  terraria 1.3.0.6 using it along with this still no luck and in the code below you will see why I specified 1.3.0.6 also a screenshot of the tshock folder.

[Screenshot](http://i.imgur.com/AyHJSki.png)

`TerrariaAPI Version: 1.22.0.0 (Protocol v1.3.0.8 (156))
SendQ edition
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "Permabuffs V2.dll". ---> System.TypeLoadException: Could              not load type 'TerrariaApi.Server.TerrariaPlugin' from assembly 'TerrariaServer, Version=1.3.0.6, Culture=neutral,              PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)`

**Comment by tylerjwatson** [comment]
Hi,

We cannot provide support for third party or derivative works based on TShock.  We also cannot provide support for plugins.  Please seek support via the support channels for the custom server implementation.

If I was to give you some advice though, it would be to make sure that all your components are up to date, because 1.3.0.6 is an old version of Terraria.

Cheers!

**Comment by Soudon** [comment]
Thanks for that everything is updated just tried the backup to be safe. Creator doesn't respond thats why I tried here thank you though I'll remember for the future.
