### ISSUE TITLE
Problem while creating region.

### ISSUE THREAD

**Issue by Strinkor** [NyxStudios/TShock#1169]
OS: Windows Server 2012
Tshock: latest

When i trying to define region it returns me error that displayed on a screenshot.
![bug](https://cloud.githubusercontent.com/assets/6019126/13709978/5dac86cc-e7bf-11e5-8a6d-98d116c20a4f.png)
But, this region not exist in database.

**Comment by sammyvsparks** [comment]
Did you check all area's of the database and make sure the server is shutdown while making modifications to the database.

**Comment by Strinkor** [comment]
All is correct, all fields in database correct. Also, region creates, but doesn't protect.

**Comment by loohney** [comment]
Is it possible for you to post the error message from the logs instead of just a screenshot?

**Comment by Strinkor** [comment]
Sorry about incorrect information, this bug found in a latest unstable build, but in a latest stable release it's seems okay.

**Comment by Zaicon** [comment]
I'd like to mention that this is a definite bug within the latest build (not release, but latest commit). Even with no regions in the database, any attempt to use _/region define_ will result in an "already exists" error.

**Comment by nicatronTg** [comment]
Uh oh. Sounds like a regression.

**Comment by WhiteXZ** [comment]
I'll fix it when I get home

**Comment by nicatronTg** [comment]
White,

Oh white.

My passion burns for thee. You are my heart, my soul, and my tea.

I hope you are doing well, for you are very swell.

Please, give me your love, for free.

**Comment by WhiteXZ** [comment]
Cannot reproduce on latest general-devel (built from source) or Bamboo 593. Are you running a clean install?

**Comment by nicatronTg** [comment]
Apparently this still exists -- a potential fix is #1171.
