### ISSUE TITLE
[SSC] By Pass SSC don't work

### ISSUE THREAD

**Issue by dark22** [NyxStudios/TShock#1170]
The latest stable release works well, but the current development version even if the player has superadmin or the permission "tshock.ignore.ssc", the inventory is replaced by the SSC only while connected to the server.

Taking a quick look, i see that the error occurs after changes to:
"[Add PlayerPermission hook, replace p.Group.HasPermission by p.HasPermission](https://github.com/NyxStudios/TShock/commit/aa419283a962ed95e011223d75797cdb0008363a)"

Just change the file **"GetDataHandlers.cs"** on line **1479**:

**if (!group.HasPermission(Permissions.bypassssc))**
_Changed by:_
**if (!args.Player.HasPermission(Permissions.bypassssc))**

The previous code is a user group research through:
**var group = TShock.Utils.GetGroup (user.Group);**

The current does not seem to work well, since changing the line everything works as it should.

**Comment by nicatronTg** [comment]
Cc @enerdy

**Comment by nicatronTg** [comment]
cc @enerdy again

**Comment by WhiteXZ** [comment]
The behaviour for a superadmin in SSC is defined as such:
User's local inventory is preserved on joining the server.
Modifications to this inventory are lost upon leaving the server.

https://github.com/NyxStudios/TShock/commit/72ccd34ae674ca83dc6481145619f0595a373b06 enforces this behaviour.

If you need an all-powerful administrative account that can also play the game, use permissions `*, !tshock.ignore.ssc`
