### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Brinefilip** [NyxStudios/TShock#1173]
Hello, i have issues with open Tshock, i have .net framework and win 10
heres the text when i open it:

SendQ edition
TShock was improperly shut down. Please use the exit command in the future to prevent this.
TShock 4.3.12.0 (Yoraiz0r R0cks) now running.
AutoSave Enabled
Backups Disabled
Welcome to TShock for Terraria. Initialization complete.
[Server API] Info Plugin TShock v4.3.12.0 (by The TShock Team) initiated.
Exception during world metadata load.
If you are using -autocreate, it is safe to ignore this.
[Server API] Error Server crashed due to an unhandled exception:
System.InvalidOperationException: Fehler beim Vergleichen von zwei Elementen im Array. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   bei System.Array.FunctorComparer`1.Compare(T x, T y)
   bei System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   bei Terraria.Main.LoadWorlds()
   bei Terraria.Main.DedServ()
   bei Terraria.ProgramServer.InnerStart(String[] args)

and i looked everywhere but i couldn't find a solution

**Comment by Gummin** [comment]
Possibly the specific world your trying to load is causing this?

**Comment by Brinefilip** [comment]
no its directly on the start

**Comment by nicatronTg** [comment]
> and i looked everywhere but i couldn't find a solution

https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/
