### ISSUE TITLE
Can't get the "Ice Scream"-achievement

### ISSUE THREAD

**Issue by ThexXTURBOXx** [NyxStudios/TShock#1175]
I did it, I made it to wave 15 in Frost Moon (even wave 16), but I didn't unlock the achievement. I was playing on a TShock-Server (alone). I only used the heal-command once. Is that the reason, is it a bug or aren't you going to add support for achievements?

**Comment by ProfessorXZ** [comment]
There are many achievements that get unlocked only if completed in singleplayer, and this is one of them. Not a TShock issue.

**Comment by ThexXTURBOXx** [comment]
[Proof 1](http://forums.terraria.org/index.php?threads/terraria-1-3-0-4-is-live-changelog-included.24197/):
![Proof 1](http://femtopedia.de/sda.jpg)
[Proof 2](http://terraria.gamepedia.com/Achievements):
![Proof 2](http://femtopedia.de/das.jpg)
Are you sure?

**Comment by nicatronTg** [comment]
Could be serverside, but I doubt it. Someone should check this...?


On April 10, 2016 at 4:17:01 PM, Nico (notifications@github.com) wrote:

Proof 1:

Proof 2:

Are you sure?

**Comment by WhiteXZ** [comment]
It's likely that we never did a full diff of changes for 1.3.0.4 (due to the massive amount of changes we'd already done), meaning we missed that. Most of our changes after the 1.3 release were based on specifics we were told were changing.

However, it would be much appreciated if someone could test this in the Re-Logic vanilla server (**NOT** our TerrariaAPI server) and see if it's a bug on our end or theirs.

**Comment by ThexXTURBOXx** [comment]
I will test it today (since I don't have the achievement right now ^^ ).

**Comment by Gummin** [comment]
When I was going through my Vanilla Playthrough with TShock I never got the achievement even though I made it to wave 15 multiple times,
but when I went on my Modded Playthrough with it's server I got the achievement first try no problems at all.

**Comment by WhiteXZ** [comment]
@ThexXTURBOXx could you try with [Build 599](http://direct.tshock.co:8085/browse/TERRA-TSHOCK-599/artifact/shared/tshock_release.zip/tshock_release.zip) as well please?

**Comment by ThexXTURBOXx** [comment]
I can't test both, if the first of them unlocks the achievement. I will test the new build of TShock first and then (if it doesn't work) I will test the Vanilla Server

**Comment by ThexXTURBOXx** [comment]
One question: Do commands influent this or can I just use Godmode and the time command to speed this up a little bit (it wasn't that easy to get to wave 15 :/ )

**Comment by WhiteXZ** [comment]
You should be able to use godmode.
Time commands won't change anything, but /butcher might progress waves faster

**Comment by ThexXTURBOXx** [comment]
Ok, and should it work when i use the /invade command and start the event at wave 14?

**Comment by WhiteXZ** [comment]
Assuming our /invade command is written properly, yes

**Comment by ThexXTURBOXx** [comment]
Ok, I will try every method now :D

**Comment by ThexXTURBOXx** [comment]
Got it!
I used your build 599 with only the /godmode and 1 /time night command.
Nice work! ^^
![Yay](http://www.femtopedia.de/yay.jpg)
Another 1 question: Could I help translating TShock to German? If I could, how?

**Comment by WhiteXZ** [comment]
Translation packs are a goal for TShock 5. The current implementation makes it very difficult to support localization. Feel free to discuss it further with us in slack :)

**Comment by ThexXTURBOXx** [comment]
I will do this ^^
AND: I tested the /invade command with a Pumpkin Moon now (I let it start at wave 14). It worked, too. So the command is coded the right way. Thanks for your help and your awesome software :)
