### ISSUE TITLE
Can't connect to server if started from terminal

### ISSUE THREAD

**Issue by Tank-Missile** [NyxStudios/TShock#1176]
Using Linux Mint 17.3 with Mono version 4.2.3. If I attempt to start a server by clicking on the executable, everything works as intended. However, if I attempt to start it using the mono command in terminal, connecting to it is impossible. I also noticed that when using terminal, a yellow message is displayed welcoming me to tshock. I don't get the message when clicking the executable. Using the terminal leads to error below when the server is started, where as clicking the executable yields no errors.

UpdateManager Exception: System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x409e3220 + 0x0018f> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x409ddac0 + 0x00053> in <filename unknown>:0 
  at TShockAPI.Utils.GetResponseNoException (System.Net.HttpWebRequest req) <0x409dd830 + 0x0004e> in <filename unknown>:0

**Comment by nicatronTg** [comment]
That message isn't related to anything you can control. That's because [the stat tracking system is down](http://status.tshock.co/incident/9).

How are you invoking the server by "clicking on the executable" in a Linux environment?

**Comment by Tank-Missile** [comment]
I double click TerrariaServer.exe and it opens up in a terminal using mono-runtime. When I open it using the command "mono TerrariaServer.exe", that's where the problems start. I'm aware the Stats server was down a couple days ago from doing research, but I don't get the error unless I start the executable from terminal.

**Comment by nicatronTg** [comment]
I don't really understand how the terraria server is starting when you double click and it just disappears or just vanishes or something? You should look into how Mint executes mono when you double click the server and see if you can get the command line parameters it sends.

**Comment by tylerjwatson** [comment]
> I don't really understand how the terraria server is starting when you double click

@nicatronTg This would be `wine-mono` if binfmt is set to run win32 PEs with wine when you shell it.  Wine-mono acts quite a bit differently and wine has enough support for win32 APIs that Microsoft's .NET framework can be installed on it and work without most of the drama.  Since the binary is compiled for, and tested on Windows, then it would make sense that it would work properly under this scenario.

Running TShock with `mono TerrariaServer.exe` interprets it under plain Mono, which has been shown to have significant problems ever since Xamarin removed the boehm garbage collector from their product.

There is a significant known issue running TerrariaServerAPI on newer versions of mono; I can't seem to reproduce the problem locally no matter how hard I try, however this issue is very common on other people's machines.

@Tank-Missile - Could you please tell us more about your target environment?

* Output of `lsb_release -a`
* Output of `uname -a`
* Output of `free -h`
* Output of `mono --version`

**Comment by tylerjwatson** [comment]
Also `cat /proc/meminfo` and `cat /proc/cpuinfo`.

**Comment by nicatronTg** [comment]
@tylerjwatson thanks for the info! I didn't know that Linux Mint shipped with wine-mono (or that such a thing existed in the first place).

**Comment by tylerjwatson** [comment]
Quite often popular distros will install it as part of the `wine` package since so much stuff is .NET now, which usually comes with a binfmt.d rule to run all win32 PEs with Wine so people can just double-click exe files and have them work.  It's also possible to install netfx45 directly under Wine, or with Winetricks.

**Comment by Tank-Missile** [comment]
lsb_release -a output:

> No LSB modules are available.
> Distributor ID:	LinuxMint
> Description:	Linux Mint 17.3 Rosa
> Release:	17.3
> Codename:	rosa

uname -a output:

> Linux XPS-8700 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015           > x86_64 > x86_64 x86_64 GNU/Linux

free -h output:

>              total       used       free     shared    buffers     cached
> Mem:          7.8G       7.2G       609M       128M       221M       2.3G
> -/+ buffers/cache:       4.6G       3.1G
> Swap:           0B         0B         0B

mono --version output:

> Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>	TLS:           __thread
>	SIGSEGV:       altstack
>	Notifications: epoll
>	Architecture:  amd64
>	Disabled:      none
>	Misc:          softdebug 
>	LLVM:          supported, not enabled.
>	GC:            sgen

cat /proc/meminfo output:

> MemTotal:        8126472 kB
> MemFree:          592704 kB
> MemAvailable:    3351724 kB
> Buffers:        226668 kB
> Cached:          2439108 kB
> SwapCached:            0 kB
> Active:          5463516 kB
> Inactive:        1395516 kB
> Active(anon):    4195868 kB
> Inactive(anon):   140516 kB
> Active(file):    1267648 kB
> Inactive(file):  1255000 kB
> Unevictable:           0 kB
> Mlocked:               0 kB
> SwapTotal:             0 kB
> SwapFree:              0 kB
> Dirty:               164 kB
> Writeback:             0 kB
> AnonPages:       4193280 kB
> Mapped:           700832 kB
> Shmem:            143124 kB
> Slab:             528696 kB
> SReclaimable:     489776 kB
> SUnreclaim:        38920 kB
> KernelStack:       10800 kB
> PageTables:        50620 kB
> NFS_Unstable:          0 kB
> Bounce:                0 kB
> WritebackTmp:          0 kB
> CommitLimit:     4063236 kB
> Committed_AS:    9137932 kB
> VmallocTotal:   34359738367 kB
> VmallocUsed:       54552 kB
> VmallocChunk:   34359671292 kB
> HardwareCorrupted:     0 kB
> AnonHugePages:   1789952 kB
> CmaTotal:              0 kB
> CmaFree:               0 kB
> HugePages_Total:       0
> HugePages_Free:        0
> HugePages_Rsvd:        0
> HugePages_Surp:        0
> Hugepagesize:       2048 kB
> DirectMap4k:      235124 kB
> DirectMap2M:     7055360 kB
> DirectMap1G:     2097152 kB

cat /proc/cpuinfo output:

> processor	: 0
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 60
> model name	: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
> stepping	: 3
> microcode	: 0x9
> cpu MHz		: 3193.121
> cache size	: 6144 KB
> physical id	: 0
> siblings	: 4
> core id		: 0
> cpu cores	: 4
> apicid		: 0
> initial apicid	: 0
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
> bugs		:
> bogomips	: 6185.98
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 39 bits physical, 48 bits virtual
> power management:
> 
> processor	: 1
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 60
> model name	: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
> stepping	: 3
> microcode	: 0x9
> cpu MHz		: 3293.992
> cache size	: 6144 KB
> physical id	: 0
> siblings	: 4
> core id		: 1
> cpu cores	: 4
> apicid		: 2
> initial apicid	: 2
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
> bugs		:
> bogomips	: 6185.98
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 39 bits physical, 48 bits virtual
> power management:
> 
> processor	: 2
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 60
> model name	: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
> stepping	: 3
> microcode	: 0x9
> cpu MHz		: 3131.968
> cache size	: 6144 KB
> physical id	: 0
> siblings	: 4
> core id		: 2
> cpu cores	: 4
> apicid		: 4
> initial apicid	: 4
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
> bugs		:
> bogomips	: 6185.98
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 39 bits physical, 48 bits virtual
> power management:
> 
> processor	: 3
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 60
> model name	: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
> stepping	: 3
> microcode	: 0x9
> cpu MHz		: 3212.253
> cache size	: 6144 KB
> physical id	: 0
> siblings	: 4
> core id		: 3
> cpu cores	: 4
> apicid		: 6
> initial apicid	: 6
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
> bugs		:
> bogomips	: 6185.98
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 39 bits physical, 48 bits virtual
> power management:

**Comment by nicatronTg** [comment]
Forgive me, but you are indeed selecting a world, player count, etc. when you start TShock on both methods of opening the server?

**Comment by Tank-Missile** [comment]
Yes. Both methods ask for the same parameters.

**Comment by tylerjwatson** [comment]
Ah, it seems you're running it on bare metal.  That throws out a lot of my initial assumptions.

**Comment by Tank-Missile** [comment]
Any update on this issue? I'd like to know if there is a solution, or if I'll have to just wait.

**Comment by tylerjwatson** [comment]
We believe this issue is related to #1172.  Please check there for updates.
