### ISSUE TITLE
v4.3.12.0 Will not correctly load world

### ISSUE THREAD

**Issue by MisterNoGo** [NyxStudios/TShock#1177]
There is a huge block of my world missing when I load with tshock, v4.3.12.0.  Everything missing is player created.  Blocks were laid in-game, the wiring was done with tEdit.  The vanilla server and single player modes load the world without issue.

Edit:  There is a teleporter in part of the world not affected by this glitch that is connected to a teleporter that is affected by this glitch.  I can still use the teleporter, though it sends me to nothing.  Also, it is raining NPCs in the area affected by the glitch as the game/server repeatedly tries to spawn them where they belong and they drop off onto the world below, only to respawn again into the air.  Restarting the server, rejoining the server, and restarting the game do not work in any combination, no matter how many times I try.

**Comment by nicatronTg** [comment]
Can't test this without the actual worldfile.

**Comment by MisterNoGo** [comment]
Easiest way to send you the world file?  I'm new to github.

**Comment by MisterNoGo** [comment]
I think I did this right.
[Styx.zip](https://github.com/NyxStudios/TShock/files/233940/Styx.zip)

**Comment by Tank-Missile** [comment]
Using the solution from issue #1172 did the trick for allowing my server to start, but now I'm having the same issue as this guy when loading existing worlds. Newly generated worlds, as far as I have tested, work perfectly fine. A large chunk of the world around where I spawn is completely missing, but it gets stranger. I see npcs falling to the bottom of the missing chunk, then reset back up to where they were initially. If I move around the chunk and left click, a piece of the missing world loads around me. Relogging resets any pieces I loaded.

**Comment by nicatronTg** [comment]
Have you guys tried increasing amounts of threads? What happens when you
set the size to 100, 150, 200?

**Comment by Tank-Missile** [comment]
I tried all 3 of the numbers you suggested, but I'm still getting the same issue.

**Comment by Tank-Missile** [comment]
Any progress on this issue? It may be because the world I'm trying to load has a lot of details (props, manually placed blocks, etc) that tshock can't correctly send to the client.

**Comment by WhiteXZ** [comment]
Corrupted signs have cause chunk issues before. Try removing all signs in singleplayer, then loading again with TShock

**Comment by ProfessorXZ** [comment]
Seeing noone replied to this issue in a long time, is there any reason for it to stay open? If you are having issues with missing chunks you should take a look at https://tshock.co/xf/index.php?threads/endlessly-falling-and-other-issues.4811/#post-46763

**Comment by nicatronTg** [comment]
Please re-comment if this issue persists with @WhiteXZ and @ProfessorXZ's suggestions completed.
