### ISSUE TITLE
TShock was improperly shut down. Please use the exit command in the future to prevent this.

### ISSUE THREAD

**Issue by SevenSeasWinds** [NyxStudios/TShock#1178]
Hi guys. I am having the error "TShock was improperly shut down. Please use the exit command in the future to prevent this." .

Running over Centos and using the zip "tshock_4.3.12.zip"

Any idea?

**Comment by nicatronTg** [comment]
Don't ctrl c the TShock terminal?

**Comment by fizzvr** [comment]
`Exit` much better!

**Comment by SevenSeasWinds** [comment]
Just installing TSHOCK + terraria for the very first time under Centos 6.6
64 bits..... with Mono..... and the problems regarding SQLite arising
everywhere.

2016-05-03 16:02 GMT-03:00 Vladimir Rodríguez <notifications@github.com>:

> Exit much better!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NyxStudios/TShock/issues/1178#issuecomment-216632031>
>



-- 
Martin D. Cernadas
Cel. CABA                +54-9-11-6432-1586
Blogger   http://www.martindcernadas.com.ar/
Linkedin  ar.linkedin.com/in/martindcernadas
Twitter    http://twitter.com/SevenSeasWinds

**Comment by tylerjwatson** [comment]
Please do not post more than one issue per thread.  It appears that your query was resolved in this one, and if you are having further troubles please create a new issue with more details.

_ps. "problems arising everywhere" isn't a well structured report._
