### ISSUE TITLE
Spear Traps do not work.

### ISSUE THREAD

**Issue by BStorm888** [NyxStudios/TShock#1182]
Spear traps do not function in the latest version, the spear traps however did function in v4.3.12.

**Comment by WhiteXZ** [comment]
Are you using Mono?

**Comment by BStorm888** [comment]
Mono? What is that?

**Comment by nicatronTg** [comment]
I guess that's a no.

**Comment by g1zstar** [comment]
I had the same problem on the last version and I found that change #587 (context: https://bamboo.tshock.co/browse/TERRA-MB) of the old version fixed them but they're back to not working in the latest version.

I think this is something that doesn't have to do with versions. Target Dummies don't work for me either and they were working before but then out of the blue stopped working.

**Comment by ProfessorXZ** [comment]
Can anyone confirm this is still broken?

**Comment by Patrikkk** [comment]
This is surely fixed by now.  "Target Dummies don't work for me either and they were working before..."
I remember entity related fix which should have fix these.
Can't confirm tho coz didn't test :D (yet)

**Comment by nicatronTg** [comment]
@Patrikkk since I don't have a copy of Terraria available, can you test this?

**Comment by Patrikkk** [comment]
![ss 2016-10-11 at 03 20 45](https://cloud.githubusercontent.com/assets/5616692/19255808/c57fead8-8f61-11e6-8370-c727c2a0788c.jpg)

Seems to be functioning perfectly.
