### ISSUE TITLE
Wires protection ignored with new tools

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1190]
As the topic title says. The new tools such as The Grand Design, and MultiWrench ignore the protection of TsHock regions and allow wires to be edited or removed.

**Comment by mistzzt** [comment]
People who dont have permissions to build can also THE GRAND DESIGN modifing the world.

**Comment by cracker64** [comment]
New packet type 109 (MassWireOperation) needs to be handled.
I've done some similar handling of this already over at History
https://github.com/MarioE/History/commit/9a1c4577250b30378d35d1d16af291fe8cc4616f
This might be useful for someone trying to restrict this packet properly.

**Comment by Marcus101RR** [comment]
Figures its a new packet.
