### ISSUE TITLE
Gem locks not protected in Regions.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1198]
Basically there's nothing to add here, Gem Locks are not protected in Regions.

Using latest TShock build 4.3.15.0

**Comment by Enerdy** [comment]
Those are used for games, right? Why would you want a flag (gem) that cannot be taken?

This is more like a feature request than a bug, considering Gem Locks aren't actual tiles, and region protection is only meant to protect tiles from being altered (and to a further extent, signs and chests, if the option is enabled in the config). Could take a config option, perhaps?

**Comment by ProfessorXZ** [comment]
This issue was fixed and merged.
