### ISSUE TITLE
Pressure plates don't work in the latest release

### ISSUE THREAD

**Issue by jacky8399** [NyxStudios/TShock#1199]
Pressure plates stopped working in the latest release.
![image](https://cloud.githubusercontent.com/assets/7542810/15674472/8004c8f2-276f-11e6-99b7-7953a87a3a10.png)
The flame trap didn't get triggered when I stepped on both pressure plates, one being player-only, and the other being generic. There were no stack traces or error log.
**Steps to reproduce**
![image](https://cloud.githubusercontent.com/assets/7542810/15674522/c83188b8-276f-11e6-90b7-98fabedd6b8f.png)
1. Connect a pressure plate to a random mechanism and it doesn't work.

PS:
![image](https://cloud.githubusercontent.com/assets/7542810/15674547/f549fd3a-276f-11e6-8980-d8f7d01323b1.png)
Other animals stepping on it does work, though. Probably related to the new pressure plate changes in 1.3.1?

**Comment by cracker64** [comment]
Weighted pressure plates do work, I would test those again.
The regular pressure plate issue is confirmed and I will fix it shortly

**Comment by recon88** [comment]
I just tried the recent update. The seem to be semi-working.
If you walk normally, they trigger. If you run, for example with the highest Boots upgrade, they don't seem to trigger always.

**Comment by Enerdy** [comment]
Pressure plates not triggering when you run too fast is not a TShock/TSApi issue, it's a Terraria issue by itself, and it's always been like this. Please read http://terraria.gamepedia.com/Pressure_Plates.

**Comment by Gummin** [comment]
`If Players travels fast enough, faster than 95 mph, over the Pressure Plate Track it is possible for it not to trigger.`
You can't run anywhere near 95mph.

**Comment by recon88** [comment]
Didn't notice that yet. Thanks

**Comment by recon88** [comment]
After investigating further, this actually seems to be a TShock issue.
It randomly happens on Vanilla when moving too fast BUT it happens every 2nd try on TShock when moving slow(!). I had no gear on and was moving with base speed. It only triggers 50% of the time. Vanilla triggers 100% of the time when trying with no gear.

**Comment by cracker64** [comment]
When the door fails to open, do you hear a pressure plate noise from the client?
I think this may be a -door- specific issue and not pressure plates. Try placing a torch on the same wire as the door+plate and see if they stay the same.

**Comment by recon88** [comment]
You are indeed right. It's an issue with the doors. I do hear the noise but the door doesn't trigger. Torch does.
