### ISSUE TITLE
Another language?

### ISSUE THREAD

**Issue by MdbM** [NyxStudios/TShock#120]
Hello
I am a player from Russia. I have my own project on the game Terraria.
The first thing I want to thank you for your contribution to the development of game servers Terraria =)
I have a few questions:
1 - Is it possible to change the game language (or add another one)?
2 - Is it possible to support the Russian language in the chat?

PS - Pre-sorry for my English. I do it less than ideal + use a translator.

**Comment by nicatronTg** [comment]
Okay, so, we're gonna close this issue again because @WhiteXZ hasn't sent any code or anything for this.

**Comment by WhiteXZ** [comment]
Yeah cbf
