### ISSUE TITLE
not sure server runs fine i install tshock now i get this 

### ISSUE THREAD

**Issue by beals1pt0** [NyxStudios/TShock#1200]
Missing method .ctor in assembly /home/tcagame/rebel/33/TerrariaServer.exe, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /home/tcagame/rebel/33/TerrariaServer.exe mtoken: 0x0a000074
* Assertion at class.c:5597, condition `!mono_loader_get_last_error ()' not met

**Comment by nicatronTg** [comment]
This appears to be a mono issue. Please try installing the latest version of mono and executing it from there.
