### ISSUE TITLE
Deadlock for Hardmode

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1201]
SCREEN: http://i.imgur.com/Nm796YJ.png
DUMP: http://74.91.127.178:8080/files/TerrariaServer.zip

Deadlock automatic on Hardmode with command or WOF.

**Comment by WhiteXZ** [comment]
Looks like WorldGen is probably a bit broken then

**Comment by Marcus101RR** [comment]
Update: Server came back online, but everyone was kicked (Left the game).

**Comment by WhiteXZ** [comment]
Brief testing shows that enabling hardmode causes a period of spanning ~10 seconds on a small world. On a large world with multiple players, I can see this causing disconnection issues

**Comment by Marcus101RR** [comment]
UPDATE: This bug causes you to end up with someone else's inventory, highly dangerous! This bug has to be fixed asap.

**Comment by tlworks** [comment]
@WhiteXZ Correct, on a Large world (With 2 players) the server Deadlocks upon using /hardmode or killing the WOF. Upon typing /save into the console will trigger "setting hard mode" and will continue to deadlock until the world has finished setting hard mode and saved.

**Comment by tlworks** [comment]
@WhiteXZ I believe this was fixed?
