### ISSUE TITLE
Item Frames

### ISSUE THREAD

**Issue by cracker64** [NyxStudios/TShock#1202]
I thought I'd make an issue to be clear we know about this problem.
These work great for superadmins, unfortunately most users aren't superadmins.

This problem is extremely deep and derives from issues in TShock, Server-API, and user Clients.

Server-API : Possible desyncs and leaves invalid tile placements caused by not fully killing these when it should. (This problem exists in vanilla, but we could fix it here anywhere)

Client: When sending a new Frame, it sends the packets in a really strange order, confusing TShock into a desynced state. A superadmin will bypass this problem and keep sync. (We can't fix this)

TShock: Needs additional code to properly handle PlaceObject of item frames, which can prevent the desync with Entities+Tiles from happening. (Should fix main problem)

**Comment by tlworks** [comment]
Just ban item frames, items can easily be duplicated by simply spam-adding items on a frame which are more than 1 quantity.

Item frames are just bad, same goes for dummies.

**Comment by gyrodrill** [comment]
Try use /tileban add 395
This will prevent player from placing this tile to the map.

**Comment by nicatronTg** [comment]
I'm assuming this is still an issue, so I'm tagging this is a PR wanted. @WhiteXZ if you have an immediate fix, that's appreciated too, but I doubt it.

**Comment by Ijwu** [comment]
Has this issue been fixed?

**Comment by ProfessorXZ** [comment]
@Ijwu It seems it was. See https://github.com/NyxStudios/TShock/issues/1160

The conversation we had in Slack:

> white [2:34 PM]  
> tshock gets confused because of the order in which item frame packets are sent
> 
> professorx [2:34 PM]  
> Ok, and that means
> 
> white [2:34 PM]  
> @cracker64 figured it all out and we never got around to fixing it
> 
> professorx [2:34 PM]  
> I still don't get your point :neutral_face:
> 
> [2:35]  
> what is the issue here
> 
> [2:35]  
> what is caused by the "confusion"
> 
> white [2:35 PM]  
> item frames don't place properly and duplicate items
> 
> professorx [2:35 PM]  
> uhh
> 
> [2:35]  
> I fixed that
> 
> [2:35]  
> lol
> 
> [2:35]  
> https://tshock.slack.com/archives/tshock/p1476275384004340
>  professorx
> And was it related to this https://github.com/NyxStudios/TShock/issues/1160
> Posted in #tshockToday at 2:29 PM 
> 
> white [2:36 PM]  
> o ok
> 
> professorx [2:36 PM]  
> Aaand since noone reported anything in the past 2 months I consider it fixed

**Comment by Ijwu** [comment]
Let's make sure these conversations are documented in the relevant issues on GitHub. Thanks for the update, @ProfessorXZ!
