### ISSUE TITLE
`AllowCorruptionCreep` and similar config options do nothing

### ISSUE THREAD

**Issue by Enerdy** [NyxStudios/TShock#1204]
Corruption, Crimson and Hallow will still spread even if the `AllowCorruption/Crimson/HallowCreep` option is set to false in the config.

**Comment by tlworks** [comment]
This issue existed ever since 1.2 and never really got fixed (To my attention), all you can do is limit the regions off with clay blocks.

**Comment by Sakata-MC** [comment]
I think we can add "disablehardmode" to that list.  hardmode still happens with it turned off
