### ISSUE TITLE
Ice Rod can cause server crashes.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1205]
?????: Alrighty listen
?????: You can ask even me_skrub
?????: anyways
?????: You place 3 ice rod blocks
?????: and place on it teleporter and dresser
?????: once u break the ice blocks the server gets crash.

So basically, that's the whole deal. It IS considered an Terraria issue/bug but maybe furniture/teleport placement on these tiles can be disallowed by TShock.

Just a heads up.

**Comment by cracker64** [comment]
Unrelated to ice, breaking anything under a teleporter+dresser does the same thing.

**Comment by Kojirremer** [comment]
I think ice placement from the Ice Rod can be disabled via TShock's config file.

**Comment by Strinkor** [comment]
@Kojirremer But the bug won't dissapear.

**Comment by Kojirremer** [comment]
@Strinkor I know that, but it's an alternative to "but maybe furniture/teleport placement on these tiles can be disallowed by TShock" said by @tlworks .

**Comment by tlworks** [comment]
@WhiteXZ Latest Bamboo build regarding this fix breaks SSC.
