### ISSUE TITLE
Is this supposed to happen upon Restart?

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1206]
Assuming the cause is that the user shown in the image 'PGC' leaves after the server is already shut down?

https://i.gyazo.com/358e495037555904ee9fe46d8cd272a7.png

Don't really know what the cause is of this.

**Comment by Enerdy** [comment]
That is, in fact, the probable cause of that exception. Still, there should be a way of avoiding this.

**Comment by tlworks** [comment]
It's simple, disallow people/players to join after the command /restart (or well, /exit) is executed as back in 1.2.4.1 the servers saved the world rather quick where people didn't even had the time to join back before it actually restarted. Ever since 1.3 the world saving takes quite a while so people can simply join back in while the restart (shut down) is executed.

**Comment by Patrikkk** [comment]
Couldn't reproduce :/
I started up server (0 players)
I execute restart and quickly join the server. It joins server and then I get kicked once world finished saving.

**Comment by tlworks** [comment]
Would still suggest to prevent joining after the command /exit is issued, as joining after using /exit would be irrelevant to begin with or KICK the player with the message that the server has been shut down or is shutting down, it also seems that is has to be 'perfectly timed' in order to reproduce properly.

Depending on the amount of players online, CPU usage & the world size, the saving after /exit could take longer, making it able for people to join back on.

Issues mostly happens when the user surpasses the part where it should KICK the user upon finished world saving.

**Comment by tlworks** [comment]
Also error log:

[07/05/16 11:09:48] [TShock] Error: 2016-07-05 11:09:48 - Utils: INFO: Broadcast: Gbvkhfkauj has left.
[07/05/16 11:09:48] [TShock] Error: 2016-07-05 11:09:48 - TShock: INFO: Gbvkhfkauj disconnected.

**Comment by nicatronTg** [comment]
If the server is going down, I think this is a non-issue/"exception normal." It's not something I expect _anyone to pick up_ but I'm going to flag it as PR wanted, because why not. Don't expect this to be fixed any time soon.
