### ISSUE TITLE
Server "startedr"??? Only 99%?

### ISSUE THREAD

**Issue by TerrariaLover22** [NyxStudios/TShock#1209]
Every time I load up the TerrariaServer.exe file it says "Server Startedr" with the bar at 99% after selecting my world and it loading stuff. I did port forward to 7777, and i picked my player amount to 28. Did i enter the IP address wrong while port forwarding? I got Verizon FiOS, if that helps.

**Comment by TerrariaLover22** [comment]
![proof](https://cloud.githubusercontent.com/assets/19787002/15840883/f691027e-2c1a-11e6-9918-631048d82c85.PNG)

**Comment by Enerdy** [comment]
Sounds like an issue with your world to me. Could you try generating a new world (preferably with your Terraria client, since TerrariaServerAPI currently generates worlds /very/ slowly) and then loading it to see if you still get that error?

**Comment by TerrariaLover22** [comment]
Just tried, but did not work. I might make a world then open it in terraria as a server (steam multiplayer on) and then load it with TShock. think it might work?

**Comment by TerrariaLover22** [comment]
btw i am using tshock 4.3.16

**Comment by TerrariaLover22** [comment]
?????????????????????????
It stays there with "found server" doing nothing

**Comment by TerrariaLover22** [comment]
Some details that could help

- i am using Windows 10
- I tried using 4.3.15
- My intel thing is a Core I5
- Wifi router is Verizon FiOS

**Comment by mistzzt** [comment]
I think you should change the port and try again.

**Comment by Zaicon** [comment]
I got this issue when I tried running a second server on the same machine using a different IP.

**Comment by TerrariaLover22** [comment]
How do i port forward my server (since i probably did it wrong but with the right port)
- Do i set it to TCP, UDP, or both?
- what ip adress should i use? IPV4, Gateway, IPV6, or mix them up?

**Comment by Enerdy** [comment]
Terraria only functions on IPv4.

I don't think you need both TCP and UDP for Terraria but I forgot which one it was.

**Comment by TerrariaLover22** [comment]
so how would i enter my IPv4 IP into port forwarding (just an example not anyones actual IP)

**Comment by TerrariaLover22** [comment]
i port forwarded again (i literally changed nothing) and it worked

**Comment by scott-franklin** [comment]
Also having this issue - Running TShock 4.3.19 on Ubuntu Server 16.04.1. Strange because it ran for a while fine and then now I can't get this issue to disappear for whatever reason...

**Comment by daredev** [comment]
Just be PATIENT. Server will finally load. I encounter the same thing. Just takes a little bit more time to get to 100%.
