### ISSUE TITLE
HandleBuff error.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1210]
![2e77368fd6656c6531bc97a612dc7951](https://cloud.githubusercontent.com/assets/19647337/15876094/9bf1237a-2d0b-11e6-9ee7-47be9649d4c6.png)

No idea why it happens, but this has been there for a long long time.

Obviously using latest 4.3.16.0, if dump needed please do ask.

**Comment by Patrikkk** [comment]
You have a dump when that is happening?
If so please upload and share? :) Might be able to find the problem with that.

**Comment by ProfessorXZ** [comment]
Would be nice if anyone else could confirm that this really is happening. I made a quick-fix that seems to fix the exception @tlworks was receiving, but I won't PR anything unless there are more reports since it seems noone has reported this ever.

**Comment by WhiteXZ** [comment]
@ProfessorXZ PR would be appreciated
