### ISSUE TITLE
NpcStrikeEventArgs Player.Name is null

### ISSUE THREAD

**Issue by GNR092** [NyxStudios/TShock#1215]
Hi all first sorry for my English, I wanted to tell you when they damage an NPC I get all right

Damage
KnockBack
HitDirection
Critical
NoEffect

but there is a problem in Player.Name returns null, in the 4.3.13 Version it worked fine.
a greeting and thank you.

**Comment by tlworks** [comment]
Could you provide either logs, images or a dump file? Can't really make anything out of this without that.

**Comment by WhiteXZ** [comment]
It looks like our NpcStrike hook got changed and the `Player` object is never provided to it now.
At this point, if you want to find out who's hitting an NPC you should listen for packet 24s (NpcItemStrike) and pull the player ID and NPC ID from that

**Comment by GNR092** [comment]
could you give me an example please.
thank you for responding

**Comment by WhiteXZ** [comment]
```
//main
ServerApi.Hooks.NetGetData.Register(this, OnGetData);
//end main

void OnGetData(GetDataEventArgs args) 
{
    if (args.MsgID != PacketTypes.NpcItemStrike)
    {
        return;
    }

    if (args.Msg.whoAmI < 0 || args.Msg.whoAmI > Main.maxNetPlayers)
    {
        return;
    }

    using (MemoryStream ms = new MemoryStream(args.Msg.readBuffer, args.Index, args.Length - 1))
    {
        short id = ms.ReadInt16(); //npc ID
        byte playerId = ms.ReadByte(); //player ID
    }
}
```
