### ISSUE TITLE
Odd behavior of the /region command

### ISSUE THREAD

**Issue by Kojirremer** [NyxStudios/TShock#1218]
So today I did some region management and while moving/deleting regions, I noticed that using /region delete gives an error message, yet the command actually worked despite the message, as the region targetted for deletion has indeed dissapeared.

Plugins that are a frontend of the /region command like House Regions also detect this error, as doing /house delete gives an "Internal Error" warning, but just like with /region delete the region is succesfully deleted despite the error.

Using the latest stable build for 1.3.1.1.

**Comment by mistzzt** [comment]
Didnt it show that "check logs for more details"? 
You should upload your log.

**Comment by Kojirremer** [comment]
It didn't. It just said there was no such region when trying to delete it, as if you made a typo. But as I said, it still went and deleted it as intended, so the command is still fully functional.

2016-06-18 23:46:02 - RegionManager: ERROR: System.MissingMethodException: Método no encontrado: '!!0[] System.Array.Empty()'.
   en DieMob.DieMobMain.onRegionDelete(RegionDeletedEventArgs args)
   en TShockAPI.Hooks.RegionHooks.OnRegionDeleted(Region region)
   en TShockAPI.DB.RegionManager.DeleteRegion(String name)

**Comment by mistzzt** [comment]
Based on your log, i think the problem is caused by plugin "DieMob". As it has nothing to do with TShock,  You should create issues for it.

**Comment by Kojirremer** [comment]
Yes, you are right.
I didn't notice until I saw the log. Took Diemob down and it worked as usual.
Sorry for the trouble.

*Closes*
