### ISSUE TITLE
Separate permissions for /give and /item.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1220]
Players will be able to give someone else items through the /give command while the /item command only gives the player the desired item, due to this I think it would be better to add a separate permission for /item and /give to prevent players on non-SSC servers to spam someone else's inventory full with tons of items and prevent group abuse on SSC servers by using /give to give players items which they are not allowed to do so.

**Comment by mistzzt** [comment]
#1221

**Comment by mistzzt** [comment]
#1222
