### ISSUE TITLE
[TShock for v1.3.1.1] TShock freezes when entering hardmode

### ISSUE THREAD

**Issue by matemate01** [NyxStudios/TShock#1230]
(Whoever read my old thread, I'm still the guy who's running TShock on debian jessie with mono JIT v3.2.8)

I'm sorry, but the logs don't say anything and I don't know how to start TShock verbosely.

**So, here's my problem:**

After defeating the Wall Of Flesh, the server just freezes (killed mobs respawn, can get negative HP levels, etc.), and restarting the server causes the world to return to 'normal'/pre-hardmode. Also, the WOF's loot disappears.
When entering `/save`, the server ONLY says `Save successful` (without saving world progress), but it doesn't seem to be.

Also, after entering a second `/save`, it freezes completely (can't enter any more commands, so I had to terminate the process).

Any help is appreciated.

**Comment by Patrikkk** [comment]
Thank you for the report :) The problem has been confirmed and issued before. #1201
The fix is coming shortly. Please be patient ^^

**Comment by matemate01** [comment]
Oh, I'm sorry. Searched for it multiple times, but the word 'deadlock' totally skipped my mind :P

**Comment by Patrikkk** [comment]
No worries mate :)
