### ISSUE TITLE
Skipping Mobs & Time Skipping.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1231]
Probably has been addressed before but it has come to my attention that the monsters in Terraria Multiplayer skip a lot (Teleport from one place to another or get backtracked to previous location as they try to move to the next). I was wondering if this could be fixed (At all) if possible as the npcstream function in the config doesn't seem to improve anything (If it wasn't deprecated to begin with).

The second issue is regarding the time skipping (Just like mobs, but less frequent and not as bad). The time sometimes skips back in hour (in-game time, that is). The frequency of the time skipping mostly depends on the amount of players online (or CPU usage?), the most easy way to reproduce this issue is to use a sun-dial with around 25~30 players online.

**Comment by Nepoxx** [comment]
I've experienced the same issue. Seems to be slightly relieved with decreased CPU load.

**Comment by Nightreaver** [comment]
I havew that with even less player (2-3) and cpu is a six-core xeon :/

**Comment by Enerdy** [comment]
Terraria runs on a single core anyways so that is irrelevant.

**Comment by ProfessorXZ** [comment]
I'd like to point out this is an issue in vanilla too, so it is caused by TSAPI itself, not TShock. I've posted a short video confirming this in Slack a few days ago.

**Comment by nicatronTg** [comment]
Because this is an API issue, this has been moved to https://github.com/NyxStudios/TerrariaAPI-Server/issues/101.
