### ISSUE TITLE
Hardmode not triggering unless command /save is issued.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1232]
So basically after using /hardmode or defeating the Wall of Flesh, hardmode will never trigger unless you type the command /save (Don't know whether it does this by automatic save). But you can see if you use /hardmode and have it wait, the CPU usage will simply stay the same until you issue the /save command (You can even see after using it, it'll say: setting hard mode).

Don't know if this can be fixed because Vanilla Terraria works the same way, but if it can it'd be highly appreciated.

**EDIT:** So apparently using /save causes the process to be terminated and will also cause the server to deadlock? All in all I think the whole hardmode process is kind of odd.

**Comment by Kojirremer** [comment]
I've been doing /hardmode on several maps due to setting up WorldRegen and didn't need to use /save a single time for it to register.
I just used /hardmode on console, then left it alone for about 3 or 4 minutes until the "Server is now in Hardmode" green message appeared.

**Comment by webmilio** [comment]
The server isn't put in deadlock, the save is simply queue'd. Like Kojirremer said, you have to wait 3 to 4 minutes.

**Comment by Patrikkk** [comment]
this is already fixed in  ec33752131674b209f14d1bf08e6bb7d25e42508 :)
This is not an issue anymore.
