### ISSUE TITLE
Kicked for 'Lost Connection'.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1237]
Don't know this was intended, simply because back in the day upon kicking a player who lagged the whole server would lag. But as of now every time you kick someone or have the server restart (/exit) it will kick everyone for 'Lost Connection' making it look like the server died or something.

Don't know if this can be fixed either, but it's been there for a while now.

**Comment by WhiteXZ** [comment]
Does not occur for me locally

**Comment by Kojirremer** [comment]
I've too noticed that when doing /exit and being kicked out of the server, instead of the server kick message I often get the Timeout warning. Only remotely though. Can't tell if it works locally.
Didn't really bother me too much. Just adding my two cents.

**Comment by ProfessorXZ** [comment]
Cannot reproduce locally.

**Comment by nicatronTg** [comment]
I can't reproduce this on OS X, but Windows users might try [clumsy](https://jagt.github.io/clumsy/index.html) to reproduce.
