### ISSUE TITLE
Error on server start up

### ISSUE THREAD

**Issue by Aestrocorp** [NyxStudios/TShock#1245]
I start it on Administrator and this is what happens:
[Pastebin (so it's easier to read.)](http://pastebin.com/RhCaU7Sp)
> [07/24/16 17:13:43] [Server API] Verbose: TerrariaApi - Server v1.23.0.0 started.
> [07/24/16 17:13:43] [Server API] Verbose: 	Command line: "C:\Users\*Username Redacted*\Documents\Terraria\TerrariaServer.exe" 
> [07/24/16 17:13:43] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
> [07/24/16 17:13:43] [Server API] Verbose: 	Mono: False
> [07/24/16 17:13:43] [Server API] Info: Plugin TShock v4.3.16.0 (by The TShock Team) initiated.
> [07/24/16 17:13:44] [Server API] Error: Server crashed due to an unhandled exception:
> System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
>    at System.Array.FunctorComparer`1.Compare(T x, T y)
>    at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
>    at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
>    at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
>    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
>    --- End of inner exception stack trace ---
>    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
>    at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
>    at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
>    at Terraria.Main.LoadWorlds()
>    at Terraria.Main.DedServ()
>    at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by Xandershark1** [comment]
Server's aren't up to date with the Terraria version, need to wait until they come out with a new API code for the servers

**Comment by ProfessorXZ** [comment]
Remove all your worlds and start adding them one by one to see which one causes the exception.

**Comment by XGhozt00** [comment]
I had this problem, it's one of the world files. Not sure if they are corrupt or not, I deleted the old ones and the error went away.
