### ISSUE TITLE
Validation on UpdateItemDrop

### ISSUE THREAD

**Issue by MarioE** [NyxStudios/TShock#1261]
Presumably this can be used to crash clients by sending invalid item IDs.

**Comment by ProfessorXZ** [comment]
That is correct, but it is already handled by our GetDataHandler :+1:

**Comment by MarioE** [comment]
That seems to only handle packet 21 and not packet 90. I might be mistaken, though.

**Comment by ProfessorXZ** [comment]
Ah, my mistake. Forgot packet 90 is UpdateItemDrop. Fixing it now...
