### ISSUE TITLE
Command /setdungeon needs the permission 'tshock.world.setspawn' rather than 'tshock.world.setdungeon'

### ISSUE THREAD

**Issue by OnsenManju** [NyxStudios/TShock#1263]
(TShock 4.3.17)
/group addperm default tshock.world.setdungeon --> /setdungeon : Failed
/group addperm default tshock.world.setspawn --> /setdungeon : Succeeded

-- Maybe this line?
https://github.com/NyxStudios/TShock/blob/general-devel/TShockAPI/Commands.cs#L515

**Comment by WhiteXZ** [comment]
Oh wow, that's my bad. Made a typo on the release thread. Thanks for notifying us.
`tshock.world.setspawn` is correct, `tshock.world.setdungeon` is my mistake

**Comment by OnsenManju** [comment]
Is that so? I thought that's a typo for `dungeonposition`..
https://github.com/NyxStudios/TShock/blob/general-devel/TShockAPI/Permissions.cs#L312

**Comment by WhiteXZ** [comment]
I feel silly now. Good catch, I will fix this asap

**Comment by OnsenManju** [comment]
Ah that's my bad, I should have reported more in the first post.
Thanks!
