### ISSUE TITLE
не даёться суперадминка

### ISSUE THREAD

**Issue by belaz178** [NyxStudios/TShock#1275]

**Comment by Simon311** [comment]
Привет, тебе на [русский форум](https://tshock.co/xf/index.php?threads/%D0%94%D0%BB%D1%8F-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2.1038/page-18)

**Comment by Ijwu** [comment]
Simon has this under control. Please direct all your thank you gifts to him in the form of bottles of vodka.
