### ISSUE TITLE
The server auto shutdown in mono.

### ISSUE THREAD

**Issue by Kastino** [NyxStudios/TShock#1278]
System : CentOS 7.2 x64
I use mono to start the server and it success , but when it receives a request such as "#wget localhost:7777" it will give the request a response and shutdown! In the Terraria PC , the performance is I begin to fall and there is no LAND!!! After a moment , connection lost.

**Comment by nicatronTg** [comment]
Could you be more specific? Are you speaking HTTP to the Terraria server and it's shutting down after receiving it "#wget localhost:7777"? What exactly is happening here?

**Comment by nicatronTg** [comment]
Closing for lack of detail + reproduction steps. If you have these, feel free to comment to get this reopened.
