### ISSUE TITLE
Feature Request: Reduced event bosses (limited).

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1279]
Even though TS4 development is on a hold, because obviously Orion.. I would still like to request for bosses during events (Such as Pumpking & Frostmoon) to be limited to stop the ridiculous amount of useless lag it produces.

Regards (:

**Comment by ProfessorXZ** [comment]
![tshock__tshock_for_terraria_slack_-_google_chrome_2016-10-09_14-11-43](https://cloud.githubusercontent.com/assets/7541476/19220289/6bb52d98-8e2a-11e6-9498-26a7dd815c3c.png) And with that, this should be closed.

**Comment by nicatronTg** [comment]
This issue was closed per my instructions.
