### ISSUE TITLE
Standardize release naming

### ISSUE THREAD

**Issue by DaneEveritt** [NyxStudios/TShock#1285]
Hey there.

Just had a small request that releases all be named with the same style. I'm trying to use a script that takes a version input and downloads the corresponding version from Github, however that is made impossible because some releases are called `tshock_release.zip` while others have the version in the file name.

Would appreciate if they were all standardized. 👍

**Comment by WhiteXZ** [comment]
This is definitely something I meant to do but keep forgetting. I will try and make sure this happens in future, and will look at renaming what's up already :)

**Comment by WhiteXZ** [comment]
Everything back to 4.2.2 is now standardized to `TShock.v1.v2.v3.zip`. Note that where there are multiple releases on the same v3, a v4 is included (eg `TShock.4.2.2.3.zip`)

**Comment by DaneEveritt** [comment]
Excellent, appreciate it!

**Comment by nicatronTg** [comment]
Sorry about that! You could try going based on tag to get the release instead of filename? We try to tag everything consistently with releases.

**Comment by nicatronTg** [comment]
I believe this has been incorporated to the release docs internally. Closing this issue, but if it happens again we'll have to find some other way to prevent it.
