### ISSUE TITLE
NullReferenceException in non-SSC mode.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1286]
Considering people forget every time I bring this up, this error keeps on being spammed in the log (Not in console), even with a clean TShock.

`2016-09-19 07:57:54 - GetDataHandlers: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at TShockAPI.GetDataHandlers.HandlePlayerUpdate(GetDataHandlerArgs args)
   at TShockAPI.GetDataHandlers.HandlerGetData(PacketTypes type, TSPlayer player, MemoryStream data)`

**Comment by ProfessorXZ** [comment]
Can anyone else confirm this happens with a clean build? If it does, can you tell us when it happens/what you were doing at the time of the error?

**Comment by nicatronTg** [comment]
Assigning responsibility to @ProfessorXZ; if this issue has no more information + reproduction steps, feel free to close. Also tagging in @WhiteXZ to see if he has input other than it's a confirmed problem.

**Comment by nicatronTg** [comment]
_I am assigned to this issue for monitoring/oversight but am not actively working this issue._

**Comment by nicatronTg** [comment]
Ding dong @ProfessorXZ what's the ring wrong on this issue?

**Comment by ProfessorXZ** [comment]
Leave it open for a few more days.

**Comment by DogooFalchion** [comment]
There must be some sort of specific trigger or action, leaving the server on and connecting to it with two clients for an hour and nothing happened.

**Comment by ProfessorXZ** [comment]
No replies have been made in the past 3 weeks, so I'm just gonna close this. Re-open the issue in case someone can actually reproduce this.
