### ISSUE TITLE
Quickstack to nearby chests

### ISSUE THREAD

**Issue by adiran** [NyxStudios/TShock#1287]
Hey everyone,

since this new update (and also in the earlier unstable builds of this update) it is not possible to quick stack from my inventory to nearby chests. If i open a chest and then click quick stack everything is finde.
Maybe this is because i'm running it on gentoo linux or does any windows user has the same problem? I tried to register in your forum but the captcha didn't work so i had to post this here.

**Comment by WhiteXZ** [comment]
Tagging in @ProfessorXZ

**Comment by ProfessorXZ** [comment]
Make sure to check the following:
1) If `RegionProtectChests = true` and if you have the right permission to build inside the region (in case the chest in fact is in a protected region)
2) Whether the chest is approximately half the screen away from you and `RangeChecks = true` in config.json. I'll ask more people to confrm this later, but please try to report these issues before a new version is officially released so we can fix it if it actually is an issue :)

**Comment by adiran** [comment]
i checked if RegionProtectChests is true (it is) and i am the superadmin on my server so i should have all permissions right?

as you can see on the attached screenshot i'm hanging right above the chests and tried to quickstack. But nothing happend.

![screenshot_20160923_132536](https://cloud.githubusercontent.com/assets/4189176/18784267/4d3ba5ae-8191-11e6-9725-4db7161b704c.png)

**Comment by ProfessorXZ** [comment]
There seems to be an issue with Quick Stack (unrelated to the hook we added). I've tried this on both TShock and the vanilla server, and both failed to Quick Stack to nearby chest. I don't want to jump to any conclusions so I'd like to ask you to test this too and report back.

**Comment by ProfessorXZ** [comment]
Confirmed that this is not caused by TShock or TSAPI. @Patrikkk has also tested this using the vanillla server ReLogic provides and still couldn't quick stack. Additionally, I opened the world in Singleplayer and tried quick stacking but nothing happened there either.

**Comment by ProfessorXZ** [comment]
Okay ignore this, apparently I have no idea how Terraria works :/ @Patrikkk also says this is an issue so I'll look into it.
