### ISSUE TITLE
[v4.3.17 onwards, maybe earlier] Small typo in RestManager.cs

### ISSUE THREAD

**Issue by williamjcm** [NyxStudios/TShock#1292]
I'm developing an app that allows remote management of a TShock server, and I used RestManager.cs to get all the REST API endpoints.

When I arrived at the "/v2/groups/update" endpoint, one of the parameters ([line 1000 for v4.3.18](https://github.com/NyxStudios/TShock/blob/v4.3.18/TShockAPI/Rest/RestManager.cs#L1000), found below) is "permisisons", instead of "permissions". 
```csharp
[Noun("permisisons", false, "The new comma seperated list of permissions.", typeof(String))]
```
I don't know when this typo first occurred, but I noticed it in 4.3.17's RestManager.cs, and is still present in 4.3.18, when the file got updated.

**Comment by nicatronTg** [comment]
Looks like it's still reading a properly spelled "permissions" argument, though: https://github.com/NyxStudios/TShock/blob/v4.3.18/TShockAPI/Rest/RestManager.cs#L1011

**Comment by williamjcm** [comment]
The typo disturbed me so much that I forgot to read further. Sorry.

**Comment by nicatronTg** [comment]
@williamjcm I'm not 100% sure whether or not that param gets passed, but you should report back and see if it works correctly spelled. I'm not 100% on the functionality myself (it's been ages and I haven't retracted myself through the code fully).

**Comment by williamjcm** [comment]
@nicatronTg It works when spelled correctly, so I think that line 1000 (in v4.3.18's RestManager.cs) is only when you call TShock with the command line parameter that dumps the REST endpoints' info.

**Comment by nicatronTg** [comment]
@williamjcm thanks.
