### ISSUE TITLE
Kirbyrocket's suggestion: Display password in plain text back at a user via email

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#1296]
> Do you think email confirmation, password confirmation, or at least a message telling you your password after you register could be added (if isn't done already)? I gave birth to this idea when I saw users struggling to register with the same password that they thought they put in.

My two cents: this is easy to just drop in as a minor tweak/config option to echo the password back after registration. [Definitely not email though]. Echoing the password back is easy, emailing is bad/dangerous/a worst practice.

**Comment by ProfessorXZ** [comment]
Don't we echo back the password upon registration already?

**Comment by DaBomberNTG** [comment]
![image](https://cloud.githubusercontent.com/assets/5866651/19303439/4c83b358-902e-11e6-9559-882e8ebbdf4c.png)

**Comment by Simon311** [comment]
Yeah, this issue should be closed

**Comment by ProfessorXZ** [comment]
Thanks @DaBomberNTG. Since this complies with the original idea, it should be closed as @Simon311 previously said. Cc @nicatronTg

**Comment by nicatronTg** [comment]
@ProfessorXZ you're right I'm an idiot

**Comment by nicatronTg** [comment]
@ProfessorXZ @Simon311 @DaBomberNTG @Patrikkk please discuss this issue in the context of sending an *email notification* now not echoing back

**Comment by Simon311** [comment]
@nicatronTg As you said, this is a bad practice. Besides, Marcus already made a plugin for resetting password via e-mail, which should resolve the issue.

**Comment by nicatronTg** [comment]
@Simon311 did maru update it to the latest api / does it work in the latest api with `-ignoreversion`?

**Comment by Simon311** [comment]
@nicatronTg no idea

**Comment by nicatronTg** [comment]
@Simon311 ok

**Comment by DaBomberNTG** [comment]
Plugin is on latest api & initializes, if that is still relevant.

**Comment by nicatronTg** [comment]
@DaBomberNTG neat

**Comment by nicatronTg** [comment]
[Plaintext via email is not a best practice and a plugin accomplishes 99% of the goal easily]
