### ISSUE TITLE
Password Confirmation Prompt

### ISSUE THREAD

**Issue by ProfessorXZ** [NyxStudios/TShock#1299]
Kirbyrocket's suggestion from Slack:
>@nicatrontg: I probably should've posted this on the GitHub page sooner, but I think that a password confirmation could be used when registering to ensure that there aren't any typos in said password.

Users would be given a chance to redo their password before confirming it.

**Comment by ProfessorXZ** [comment]
The way I see it we could just add a `confirm <password>` subcommand to the `/register` command.

**Comment by WhiteXZ** [comment]
Alternatively a response command:
``` 
private static void RegisterUser(CommandArgs args)
{
    ...
    args.Player.AddResponse("confirm", ConfirmCallback);
}

private void ConfirmCallback(object o)
{
    CommandArgs args = (CommandArgs)o;
    ...
}
```

**Comment by Simon311** [comment]
Not sure how this is an issue. We already echo back the password at the user, and login does not happen automatically after registration. This means even if a user made a typo - he/she will be not be able to login until they look at the echoed password and become aware of the typo. After they do login, they can easily change their password.
This particular suggestion will do nothing but add extra overhead to registration process.

**Comment by ProfessorXZ** [comment]
Wow, I completly forgot about `/password`. @Simon311has a point and I agree with him. There is no need for this. Thanks for pointing it out.

**Comment by nicatronTg** [comment]
Well, okay. Reality 101 fail here.
