### ISSUE TITLE
"Invalid command entered" when no command entered

### ISSUE THREAD

**Issue by OnsenManju** [NyxStudios/TShock#1309]
Maybe this was caused by fixing security issues(?), error message is also displayed when I just pressed 'Enter' key (or whitespace only). It's a bit annoying.
![2016-10-17](https://cloud.githubusercontent.com/assets/16373401/19434946/3a30f0fc-94a3-11e6-8f9b-4d33b76b06bc.png)

Is there any way to avoid this, something like

if (cmdText.Trim() == "")
{
    return true;
}

at HandleCommand() in TShockAPI/Commands.cs?

**Comment by ProfessorXZ** [comment]
I do not see this as an issue honestly, if you're using the command specifier you want to enter a command by some logic, and if you don't type the command correctly or specify the command at all it returns an "Invalid command" message.

**Comment by nicatronTg** [comment]
@ProfessorXZ that's the console, though which expects a command on any line with no specifier at all

**Comment by ProfessorXZ** [comment]
If it doesn't cause problems on the client what's the issue? Isn't this how the console always worked?

**Comment by Simon311** [comment]
@ProfessorXZ Empty commands were ignored.
Though I am not sure how this is an issue.

**Comment by Simon311** [comment]
I will include this fix in an upcoming pull request.

**Comment by OnsenManju** [comment]
Thanks everyone for considering this.
I was using "null line" for separating logs displayed on console screen in order to making clearly understandable when examining behavior of plugin (e.g. testing commands one by one) etc. so far.

So this is not critical at all, just 'a bit' inconvenient.

**Comment by Simon311** [comment]
@OnsenManju If this is of any urgency - you may grab the build with this fix here https://travis.tshock.co/general-devel/1321/tshock_release.zip

**Comment by OnsenManju** [comment]
@Simon311 I have tried that. (Though there is no urgency regarding this, of course)
- null line doesn't display any errors

- simple "Invalid command" message for whitespaces

- red "Invalid command entered" error for actual invalid commands

![2016-10-17_2](https://cloud.githubusercontent.com/assets/16373401/19444277/be7e2790-94ca-11e6-9287-6b4dd880fe14.png)

That's very legitimate, thanks so much!

**Comment by nicatronTg** [comment]
The "Invalid command." is probably a vanilla message.

**Comment by OnsenManju** [comment]
Oh, that's exactly right. It's same as the original TerrariaServer.exe (not TShock). I have never hosted a server with it.. ^_^;;
