### ISSUE TITLE
Butterfly Statue spawns catchable butterflies

### ISSUE THREAD

**Issue by levi-middleton** [NyxStudios/TShock#1311]
Tested in 4.3.19 and 4.3.20, butterfly statues spawn butterflies that can be caught with either bug net. According to the wiki, critters spawned by critter statues should disappear instead of being caught. I have not yet been able to test this against stock TerrariaServer or with other statues.

**Comment by levi-middleton** [comment]
Just tested 4.3.20 bunny statues against stock. In stock, spawned bunnies go poof when catching them with a bug net. In 4.3.20, you get bunnies.

**Comment by Ijwu** [comment]
@WhiteXZ or @Enerdy I think you know more about our current packet handling than me. Do we swallow statue spawn packets and just spawn the NPC ourselves? That could cause this if we are spawning incorrect NPCs.

**Comment by levi-middleton** [comment]
I notice that TerrariaServerAPI.Terraria.Wiring line 1926 sets SpawnedFromStatue to true, but I don't see this field being read from anywhere (except TerrariaServerAPI.Terraria.NPC line 61193, where it's stored as a temp value and then rewritten onto the NPC object after defaults have been set).

**Comment by Simon311** [comment]
Our decompile is at fault. I've compared current TSAPI NPC.cs against my DotPeek 1.3.3.3 decompile and I can confirm TSAPI is completely missing any checks associated with SpawnedFromStatue.
Now let's blame someone for this

**Comment by nicatronTg** [comment]
Reopning because changelog wasn't updated.
