### ISSUE TITLE
Not properly displaying ManageUsers command exceptions to the user.

### ISSUE THREAD

**Issue by Patrikkk** [NyxStudios/TShock#1315]
For example,  `/user group` command. 
No proper error message is being displayed to the user. No matter whether user or group does not exist, users always get the `User XYZ could not be added. Check console for details.` exception

They only get displayed in Console as an error. With stacktrace and all. 
Is that necessary? A simple TSPlayer message and a LOG line in console would suffice. 
The code is there to send the player the correct error message, but exception does not catch properly. 
```
				try
				{
					TShock.Users.SetUserGroup(user, args.Parameters[2]);
					TShock.Log.ConsoleInfo(args.Player.Name + " changed account " + user.Name + " to group " + args.Parameters[2] + ".");
					args.Player.SendSuccessMessage("Account " + user.Name + " has been changed to group " + args.Parameters[2] + "!");
				}
				catch (GroupNotExistsException)
				{
					args.Player.SendErrorMessage("That group does not exist!");
				}
				catch (UserNotExistException)
				{
					args.Player.SendErrorMessage("User " + user.Name + " does not exist!");
				}
				catch (UserManagerException e)
				{
					args.Player.SendErrorMessage("User " + user.Name + " could not be added. Check console for details.");
					TShock.Log.ConsoleError(e.ToString());
				}
```

**Comment by nicatronTg** [comment]
_Assigned for monitoring, not directly working this issue._

**Comment by nicatronTg** [comment]
Working this.
