### ISSUE TITLE
Issue Starting server. Server claims there is another one running when there is not.

### ISSUE THREAD

**Issue by CausticLasagne** [NyxStudios/TShock#1339]
I don't know what is happening, but I've downloaded and run the latest mintaka release and this error
popped up when finished loading.

**_Settling liquids 78%
Settling liquids 84%
Settling liquids 99%
Starting server...
Tried to run two servers on the same PC
Server started
[Server API] Warning Plugin "TShock" has had an unhandled exception thrown by one of its ServerLeave handlers:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TShockAPI.TShock.OnLeave(LeaveEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in C:\Users\luke\Downloads\TS\TSAPI\TerrariaServerAPI\TerrariaApi.Server\HandlerCollection.cs:line 109_**

I don't have a user called luke on my machine so........ Someone needs to fix this, proto because whoever luke is, I suggest they change their username.

I should also mention, that no plugins were installed, and it was only everything that was included in the zip file.

CausticLasagne

**Comment by WhiteXZ** [comment]
Hi, please check that your config.json doesn't have the REST API enabled on the same port that you're running the server

**Comment by CausticLasagne** [comment]
No Idea what REST is, but it's disabled and on a different port.
  _**"RestApiEnabled": false,
  "RestApiPort": 7828,**_

**Comment by WhiteXZ** [comment]
Do you have any other programs running on the default port (7777) or the port you're attempting to run it on?

**Comment by CausticLasagne** [comment]
Changed the server port on running the server from 7777 to a new port. It appears that a server may be already running. I'll restart my computer and confirm this, unless it's the default port causing issues.

**Comment by WhiteXZ** [comment]
The following stackoverflow answer may help you diagnose if another process is consuming port 7777: http://stackoverflow.com/questions/1960750/how-to-find-which-program-is-using-port-80-in-windows#1960759

**Comment by nicatronTg** [comment]
If you need further assistance, please drop in Slack or create a forum thread. Thanks!

**Comment by tlworks** [comment]
Using the following option might solve this issue, try using **-ip 0.0.0.0**.
