### ISSUE TITLE
Fishing Quests

### ISSUE THREAD

**Issue by Kirbyarm** [NyxStudios/TShock#1345]
This has been a major problem for TShock for about a year now. Fishing quests do not properly save or load to and from the database for server sided characters. Server sided characters and lockable chests are the primary reason I enjoy TShock, but it has the nasty side effect or ruining fishing by resetting everyone's quests to a seemingly random low number.

Quests completed is a stat much like max health and max mana. It grants the angler hat, vest, pants, fuzzy carrot, and most importantly, the golden fishing rod (best rod in the game) at the 30th quest completed. But with this bug, requires not logging out of the server for 12 hours and successfully completing the quest every 24 minutes which is extremely inconvenient. Even if you did manage this, you'd be reset back to usually less than 10. The odds for you getting good prizes (like the three key required components for a Cell Phone, one of the best pre-hardmode items you can get in the game) increases dramatically after you've completed 50 and 100 quests... but if you're constantly mudstomped by the TShock bug you can never reliably get anywhere without resorting to cheating and spawning the prizes in for the players myself.

Is this known and under investigation? Could anyone explain how (if at all) the TShock software saves and loads server sided fishing quests? (like does it only update the database every game day or something?). Any workaround I could inform my players of would be appreciated.

**Comment by Kirbyarm** [comment]
I have some further information.

Viewing the database, it does seem to be  properly recording the quests, but it appears to be improperly loading (and setting) the quests.

The database has it at 30 now, as I earned the golden fishing rod. But after a relog, it reset my actual in-game character back to 24 completed quests (Using process memory viewing software to confirm this). The database counter continues to climb, but does not reflect the client side completed quests. I realized that this number, 24, is how many quests I completed on that character prior to getting TShock installed and working. So if I take this (naked because of the server sided mechanic) character and play in single player with it or on another non-TShock/non-SSC server, I can raise the quest counter that way and when I rejoin the TShock server, it seems to load the client side character's completed quests, and not the TShock database's.

So say I have 24 completed on the local file's character, I complete 2 on the TShock, and then jump into single player with that character. The character loads with 24 quests. Complete 2 quests here in single player, save and exit, the character now has 26 completed quests. I jump into TShock server with that same character, where in the database it shows 30 quests completed, the player actually only has 26 completed quests in memory (verified, if I set the memory address to 29 it will always give a golden fishing rod as the 30th static quest prize), but yet the TShock database merrily proceeds to save the counter but refuses to load it.
Hopefully this helps with the investigation.

**Comment by WhiteXZ** [comment]
Thank you for providing in-depth information :)
We'll look into this as soon as a dev has time.
I shall set a reminder for myself to look at it on Sunday if no one else has before then

**Comment by Kirbyarm** [comment]
Much appreciated! As a longtime fan and user of TShock, I absolutely love it. It would be nothing short of perfect were this one bug ironed out, at least from my perspective. Thanks for your time. ^^;

**Comment by ProfessorXZ** [comment]
I got really lost here. Here's a question: does TShock update the database properly when you finish a quest?  E.g you've completed 25 quests, does the database show 26 upon completing another one?

**Comment by Kirbyarm** [comment]
Sort of. It doesn't seem to update the moment the quest is finished. It updates the database every time the database 'saves' which is whatever the auto-save interval is. If database shows 25 and you do one quest, it will show 26 on the next in-game morning at 4:30 AM.

It seems to save and track the number of completed quests accurately, the problem is loading from the database. When you join the TShock server or relog, it doesn't set the client's fishing quests number to what is in the database, it just ignores that and uses the client's player file. So TShock isn't setting the SSC quests number from the database.

**Comment by Kirbyarm** [comment]
Any luck with this one yet, team?

**Comment by DogooFalchion** [comment]
I've identified the bug, a workaround until a solution is devised is to set "DisableLoginBeforeJoin" and "DisableUUIDLogin" to __true__ in config.json, and manually run the /login command.

**Comment by nicatronTg** [comment]
Finally.

**Comment by Kirbyarm** [comment]
Awesome, the workaround works! Thanks!

Hopefully those working on it can fix this soon as having to login manually as causing a bit of an issue for people on my server that have forgotten their password because they've never used it since their initial /register and /login.

Is there any way I can reset a password for someone?

**Comment by WhiteXZ** [comment]
`/user password username newpassword`

Fishing fix should be included in the next release :)

**Comment by Kirbyarm** [comment]
Sweet, thank you to everyone contributing to this wonderful project! ^^;
