### ISSUE TITLE
Toggles state not updating properly (cosmetic)

### ISSUE THREAD

**Issue by deadsurgeon42** [NyxStudios/TShock#1346]
**Version:** Mintaka#1414
**How to reproduce:**
+ Place toggle, wire it to a lamp
+ Toggle the toggle

**What happens:** | **Expected:**
------- | -------- |
![](https://media.giphy.com/media/3oz8xHYJmEGfhUU0DK/giphy.gif) | ![](https://media.giphy.com/media/11iz59hVFseBmE/giphy.gif)

**Comment by ProfessorXZ** [comment]
Please confirm that there are no plugins involved and that it happens only with TShock.

**Comment by WhiteXZ** [comment]
Cannot reproduce on latest Mintaka build

**Comment by ProfessorXZ** [comment]
I second that ^

**Comment by WhiteXZ** [comment]
Closed for now, please reopen if you find a way to reproduce this issue
