### ISSUE TITLE
remove /status from api documenation

### ISSUE THREAD

**Issue by kinvaris** [NyxStudios/TShock#1348]
`/status` should be removed from the documentation because its deprecated, now this should be used: `/v2/server/status`.

https://tshock.readme.io/reference#rest-api-endpoints

**Comment by nicatronTg** [comment]
I believe /status is not being removed because it contains information that isn't sent through /v2/server/status. cc @WhiteXZ 

The documentation is versioned and if a route removal occurs, the route removal will happen in the next documentation version, by the way.
