### ISSUE TITLE
Server won't start after update manager error. 

### ISSUE THREAD

**Issue by BillCipher1** [NyxStudios/TShock#1351]
So I'm not sure if this is the right place to report this but, everytime I start my Terraria Server on this version of TShock for Terraria 1.3.4.4 on the Pre-Release 2 I get the following error:
`UpdateManager Exception: System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x423082b0 + 0x00197> in <filename unknown>:0
  at System.Net.HttpWebRequest.GetResponse () <0x42302590 + 0x0005a> in <filename unknown>:0
  at TShockAPI.Utils.GetResponseNoException (System.Net.HttpWebRequest req) <0x423022e0 + 0x0004e> in <filename unknown>:0`
And the terminal locks up and I have to kill the task. Running on Ubuntu 16.04 and this is the output of mono --version
`Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen`

I tested this on the last stable build for Terraria 1.3.3.3 and it worked just fine. Any help or feedback would be nice. 
Regards.

**Comment by Marcus101RR** [comment]
You should update to Terraria 1.3.4.4.

**Comment by BillCipher1** [comment]
I'm using the pre-release for 1.3.4.4 and it does this. Sorry I didn't specify. 
Also after about an hour or so of just leaving the server running, it just keeps spamming the UpdateManager error.

**Comment by BillCipher1** [comment]
**UPDATE**
I was able to get the server to start by running this command:
`MONO_THREADS_PER_CPU=50 mono TerrariaServer.exe`

**Comment by ProfessorXZ** [comment]
The UpdateManager shouldn't cause any issues except for the spam. What is the issue here?

**Comment by BillCipher1** [comment]
The issue was that it just spammed the error and no one could connect. But I did get it started using the above start command
