### ISSUE TITLE
Rope coils don't work?

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#1352]
https://twitter.com/IraJacobs/status/810366162391470080

**Comment by IraJacobs** [comment]
I mentioned this in the Slack during the previous pre-release.  There's no details, they just don't appear when they hit the target block, and inconsistently drop pieces of rope "sometimes"

**Comment by tanpro260196** [comment]
Yep, this bug happen on my server as well, lucky that almost noone use rope coil these days anymore lol...

**Comment by ProfessorXZ** [comment]
Can someone please elaborate on this? What does this mean? @IraJacobs are you saying the rope just vanishes  once it hits a solid block?

**Comment by axel37** [comment]
You can craft/throw rope coils, you see the thrown rope coil as normal, but when they hit a block, no ropes appears (sometime only one rope (block) appear), and they sometime drop 9 ropes (item)

**Comment by Marcus101RR** [comment]
![image](https://cloud.githubusercontent.com/assets/8344293/21400965/7900903e-c780-11e6-8daa-f45172d096ab.png)

Release: https://travis.tshock.co/mintaka/1413/tshock_release.zip

Confirmed it is an issue, the Rope Coil appears quickly as if it worked, and then suddenly disappears as if Tile Permission is not allowed or other permission issues perhaps. Either that, or something else is preventing the tile placement.
