### ISSUE TITLE
TShock_mintaka_prere_2: can't input at command line, stuck at found server

### ISSUE THREAD

**Issue by LoganDark** [NyxStudios/TShock#1362]
I can't input any commands into the server, Control+C does nothing, and my client gets stuck on "Found server".

![Screenshot](https://puu.sh/t0qEQ/599cff6b33.png)

None of these issues appeared in the stable release, however it doesn't support my client. (Sadly)

**Comment by WhiteXZ** [comment]
What OS are you running on?
If *nix, what mono version?

**Comment by LoganDark** [comment]
```
1 ubuntu@SenzuBean:~/.local/share/Terraria/Worlds⟫ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by hendrik386** [comment]
I had the same problem. 
I've solved the problem by updating Mono to the current stable version (4.6.2.7).
I followed the 3 installation steps of Mono for Ubuntu from the Mono site:
http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

After adding Mono to the update list, I updated Mono with the Software Updater and now it's working fine for me.

**Comment by WhiteXZ** [comment]
Thanks @hendrik386.
@LoganDark could you try the above suggestion and see if it helps?

**Comment by LoganDark** [comment]
Actually I fixed it with the `MONO_THREADS_PER_CPU=50` thing but forgot to mention it sorry
