### ISSUE TITLE
Two bugs from the second prerelase.

### ISSUE THREAD

**Issue by VinnieSift** [NyxStudios/TShock#1364]
So I tried the pre relase 2 of the 4.3.21 and all the trapdoors stopped working. We can't close them and open them makes them dissapear. I taked out the mod and they worked again and the dissapeared trapdoors appeared again.
Also, we used the Super Absorbant Sponge, but the mod detected it as a cheat.

**Comment by Exeden** [comment]
I can second the trap door issue.  First trap door worked.  Second trap door kept disappearing every time I action it.  Had to stop using trap doors, couldn't get it to work.

**Comment by WhiteXZ** [comment]
Confirmed that trapdoors are broken without the `tshock.ignore.sendtilesquare` permission

**Comment by ProfessorXZ** [comment]
Increase TileLiquidThreshold to fix the sponge issue.
