### ISSUE TITLE
Startup problems

### ISSUE THREAD

**Issue by Dxhs** [NyxStudios/TShock#1370]
Fresh Manjaro Linux server.
Followed the Getting Started guide.
After monostarting the server executive and world is done loading i get:

`Starting server...
Tried to run two servers on the same PC
Server started
[Server API] Warning Plugin "TShock" has had an unhandled exception thrown by one of its ServerLeave handlers: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at TShockAPI.TShock.OnLeave (TerrariaApi.Server.LeaveEventArgs args) [0x0000b] in <61d4d61f0c2d4f2f993255610c6c3f9f>:0 
  at TerrariaApi.Server.HandlerCollection`1[ArgsType].Invoke (ArgsType args) [0x00058] in <1a6696e4b5d845b1a2510c7f6d9338e3>:0`

Afterwards nobody can connect. Can i get some guidelines as to what's going on?

**Comment by WhiteXZ** [comment]
Are you actually running two servers at once? If so, what's your process for doing so? It's possible they are conflicting somehow

**Comment by Dxhs** [comment]
No, despite the message. Only one instance. Fresh fresh install. Happens on my private PC as well. That one also running Arch Linux.

**Comment by JimangoYT** [comment]
im have that problem too, i can give screenshot of this

**Comment by jasonswearingen** [comment]
i also see this on 1.3.4.4 running on a new  ubuntu 16.0.4  vm with 1gb ram.  new install + world generated by tshock,  both small and normal size worlds.

**Comment by WhiteXZ** [comment]
The ServerLeave issue should be fixed in the next release :)

The "Tried to run two servers on the same PC" is the result of attempting to run 2 servers on the same port (or on a port already in use). Please note that the -port startup argument *does not work* at this point in time
