### ISSUE TITLE
HealOtherThreshold issue

### ISSUE THREAD

**Issue by rafaelzo** [NyxStudios/TShock#1372]
hey, i dunno if it's the right place to ask about it but...

a friend of mine is getting disable by the server  by '' HealOtherPlayer''
http://prntscr.com/drsddf

i'm pretty sure that he's not cheating
He's just wearing the Spectre Set with the Nebula Blaze, the spectre set heals the player with the lower hp while the owner of the set is attacking with any magic weapon...

i already tried to modify the ThreshHold in the config.json but nothing changed...
HealOtherThreshold
Type: Int32
Description: Disables a player if this number of HealOtherPlayer packets is sent within 1 second.
Default: "50"

**Comment by ProfessorXZ** [comment]
/reload the config if you haven't. This was added to prevent modified clients from sending a bunch of HealOther packets.

**Comment by rafaelzo** [comment]
@ProfessorXZ I just tried to attempt /reload the config and nothing changed, he still getting disabled ....  In the config.json should i Lower the default or Higher it?

**Comment by ProfessorXZ** [comment]
Increase the value. The lower it gets the faster he will get disabled.
