### ISSUE TITLE
Prevent authentication commands if there's a space/char in front of the command

### ISSUE THREAD

**Issue by ProfessorXZ** [NyxStudios/TShock#1373]
Kirbyrocket's message from Slack: I was thinking of a way to prevent a user's message from being broadcasted on register and login if there is a space or any character in front of the forward slash

In other words: typing `a/register <password>` or ` <whitespace> /register <password>` should warn the user to remove the spacing before executing the command.

**Comment by nicatronTg** [comment]
It's a fair enough point, but I mean, you aren't gonna use ```<password>``` after you see it chatted to the entire server, so I think it serves as its own warning.

The only real way to do it would be to just match the string "/register" when sent through chat which would be hilarious for causing people to not be able to help other users.

```
Shank: How do I play on the server?
gc: Just type / r e g i s t e r <password>
Shank: /r e g i s t e r <password>
<Unknown command>
gc: Without spaces.
Shank: /register<password>
<Unknown command>
gc: No with a space between register and hunter2.
Shank: Thanks!
<Registered>
gc: Np!
```

**Comment by deadsurgeon42** [comment]
Maybe only check for group `guest`?

**Comment by ProfessorXZ** [comment]
@deadsurgeon42 not sure what you mean, the user also asked for the same thing to be applied to /login. The way I see it @nicatronTg has a fair point. He said the same thing I did; you're not gonna use the same password after you've let the whole server see it. Surely you can think of something else.

And as for login, users can always use the /password command.

**Comment by WhiteXZ** [comment]
I agree with shank. Closing unless anyone has a brilliant solution
