### ISSUE TITLE
Right clicking a campfire destroys it

### ISSUE THREAD

**Issue by gwkunze** [NyxStudios/TShock#1379]
I've ran 4.3.22 on two different machines (one windows and one linux), on both right clicking a campfire makes it disappear, even when in a protected region.

**Comment by rautamiekka** [comment]
Do you see the destruction animation or does it just vanish ?

**Comment by Enerdy** [comment]
This could be a visual glitch. Does the campfire actually get destroyed or can you still see it there after reloading the tile section? The best way to test this would be to reconnect and check back on the affected area.

**Comment by OnsenManju** [comment]
> This could be a visual glitch.

I suppose so. Maybe it only affects the doer and lasts until logout.
https://tshock.co/xf/index.php?posts/47634/

**Comment by gwkunze** [comment]
As far as I can tell it just disappears, I can build a new one in it's place ao it's not purely visual (also the healing affect disappears). A sound affect plays similar to when you remove a torch for example. I'll try with a couple of users logged in and see if it also happens when someone else does it (probably later today)

**Comment by gwkunze** [comment]
I just tested it, yes, logging out and back in restores the campfire so it's not permanently gone.
