### ISSUE TITLE
Monster summons are broken, some monsters cannot be spawned by command.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1380]
Since this has been noted about a million times, it's self explanatory. All summons can be summoned by the Server itself, for example you can let the Cultist, Dune Splicer or Eater of Worlds summon on it's own but these cannot be spawned by command.

Pre-1.3.4.4 you could spawn all of these monsters by the use of the `/spawnmob` command, this also includes the Moon Lord's Core. This is now impossible and this issue has been there ever since Terraria updated, I think this should be set high priority right about now.

**Comment by Marcus101RR** [comment]
https://github.com/NyxStudios/TShock/issues/1350

**Comment by WhiteXZ** [comment]
Tracking in #1383
