### ISSUE TITLE
Fixing and improving /spawnmob command

### ISSUE THREAD

**Issue by OnsenManju** [NyxStudios/TShock#1383]
As reported #1350 and #1380, current `/spawnmob(/sm)` command can't summon mobs that have segmented bodies (like worms) and multiple types with single name (like big mimic) properly.

**1st issue:**
Segmented-mob should be summoned by its head part (e.g. "eater of worlds head") and multiple typed mobs should be summoned by its specific name (e.g. "crimson mimic", not "big mimic").
`/sm` is using [`TShock.Utils.GetNPCByName()`](https://github.com/NyxStudios/TShock/blob/b4f37a60c90e114781ce5e983ffced4b30b50363/TShockAPI/Utils.cs#L423-L426) for searching by mob's name, but it uses `npc.name`, so
- `/sm "eater of worlds"` returns ambiguous error
- `/sm "crimson mimic"` returns invalid error
- `/sm "big mimic"` returns only the first hit, but won't summon any mob in reality (see the 2nd issue)
```
[Eater of Worlds]
type NPC.name              NPC.displayName
13   Eater of Worlds Head  Eater of Worlds
14   Eater of Worlds Body  Eater of Worlds
15   Eater of Worlds Tail  Eater of Worlds
```
```
[Big Mimics]
type NPC.name   NPC.displayName
473  Big Mimic  Corrupt Mimic
474  Big Mimic  Crimson Mimic
475  Big Mimic  Hallowed Mimic
476  Big Mimic  Jungle Mimic
```

I propose using `npc.displayName` instead of `npc.name` in `GetNPCByName()` to improve that, and also it becomes able to summon by its union name (like `/sm "eater of worlds"`, because the head part will be found at first when searching).

**2nd issue:**
In [`TSPlayer.Server.SpawnNPC()`](https://github.com/NyxStudios/TShock/blob/b4f37a60c90e114781ce5e983ffced4b30b50363/TShockAPI/TSServerPlayer.cs#L156), `name` is set for new mob intensionally.
Maybe this was added for the variety of "blue slime" (type=1),
```
[Special Slimes]
type NPC.name
1    Jungle Slime
1    Yellow Slime
1    Red Slime
1    Purple Slime
1    Black Slime
1    Baby Slime
1    Green Slime
```
but it causes
- general name (e.g. "big mimic") will be set instead of desired name (e.g. "crimson mimic"), even if specified by ID (e.g. `/sm 474`) =fail to summon
- mobs that have same names and different IDs (and forms, like scarecrow) can be summoned only 1 type
- Wyvern will be summoned when executed `/sm 558` (558="etherian wyvern"`)
```
[Scarecrows]
type NPC.name   NPC.displayName
305  Scarecrow  Scarecrow
306  Scarecrow  Scarecrow
307  Scarecrow  Scarecrow
308  Scarecrow  Scarecrow
309  Scarecrow  Scarecrow
310  Scarecrow  Scarecrow
311  Scarecrow  Scarecrow
312  Scarecrow  Scarecrow
313  Scarecrow  Scarecrow
314  Scarecrow  Scarecrow
```
```
[Wyverns]
type NPC.name       NPC.displayName
 87  Wyvern Head    Wyvern
 88  Wyvern Legs    Wyvern
 89  Wyvern Body    Wyvern
 90  Wyvern Body 2  Wyvern
 91  Wyvern Body 3  Wyvern
 92  Wyvern Tail    Wyvern
558  Wyvern         Etherian Wyvern
559  Wyvern         Etherian Wyvern
560  Wyvern         Etherian Wyvern
```

So, how about like this?
```
// This is for special slimes
if (type == 1)
{
	Main.npc[npcid].SetDefaults(displayName);
}
else
{
	Main.npc[npcid].SetDefaults(type);
}
```

I'd appreciate if the devs consider it.

**Comment by OnsenManju** [comment]
Sample plugin for testing (API 2.0)
https://github.com/OnsenManju/SpawnTest

command:
`/findmob(/fm) <name>`
`/spawntest(/st) <mob ID or name> [amount]`

**Comment by Kojirremer** [comment]
Just curious, but is this issue related to birds spawned with /sm always being the basic type, even when using Blue Jay and Cardigan's IDs?

**Comment by tlworks** [comment]
@Kojirremer Yeah, same goes for Salamanders and Slugs.

**Comment by OnsenManju** [comment]
@Kojirremer, @tlworks
Probably.

Birds are similar as big mimics.
```
/findmob bird
Search result:
type=74 Main.npcName="Bird" NPC.name="Bird" NPC.displayName="Bird"
type=297 Main.npcName="Blue Jay" NPC.name="Bird" NPC.displayName="Blue Jay"
type=298 Main.npcName="Cardinal" NPC.name="Bird" NPC.displayName="Cardinal"
```
Salamanders are same as scarecrows. (I'm not sure about slugs(snails?) though)
```
/findmob salamander
Search result:
type=498 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=499 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=500 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=501 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=502 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=503 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=504 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=505 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
type=506 Main.npcName="Salamander" NPC.name="Salamander" NPC.displayName="Salamander"
```

Sample plugin can spawn them by its ID separately. Have a try if interested.

**Comment by tanpro260196** [comment]
Seem to me that /item command also have this problem. For example: you can't spawn treasure bag of any bosses except Slime King.

**Comment by OnsenManju** [comment]
@tanpro260196 Perhaps so.
Created new issue. #1398

**Comment by WhiteXZ** [comment]
Hi guys, we haven't forgotten about this issue, but it likely will not be worked on until the next Terraria update due to reasons.

**Comment by OnsenManju** [comment]
@WhiteXZ Thanks for your comment.
Then I'll keep maintaining SpawnTest plugin as a temporary workaround until those issues are resolved.

**Comment by hakusaro** [comment]
@WhiteXZ it's worth pointing out that uh, our source says that the next update won't drop for quite some time.

**Comment by OnsenManju** [comment]
@WhiteXZ Thanks a lot!
Now we can summon most of mobs by their basic name and specific ID!

All of the following worked successfully on new TShock 4.3.23:
- worm-type mobs
`/sm "eater of worlds"`, `/sm "giant worm"`, `/sm "dune splicer"`
`/sm wyvern`
- different name with same ID
`/sm "jungle slime"`, `/sm "yellow slime"`, `/sm "red slime"` and so on
- different ID with same (internal) name
`/sm "crimson mimic"`, `/sm 474`
`/sm "etherian wyvern"`, `/sm 558`, `/sm 559`, `/sm 560`
`/sm bird`, `/sm "blue jay"`, `/sm cardinal`
`/sm scarecrow`, `/sm 305`, `/sm 306`, `/sm 307` and so on
`/sm salamander`, `/sm 498`, `/sm 499`, `/sm 500` and so on

**Comment by WhiteXZ** [comment]
If you find any more that don't work, feel free to reopen this and tag me :)
