### ISSUE TITLE
"AllowIce" option gets ignored. Users can generate ice blocks regardless of its state

### ISSUE THREAD

**Issue by Kojirremer** [NyxStudios/TShock#1384]
Not much else to say. I have it set to False, yet people still spam ice blocks.

**Comment by Zaicon** [comment]
I'm unable to reproduce this locally.

**Comment by OnsenManju** [comment]
@Kojirremer:
If you're planning on removing `tshock.world.modify` permission from `default` group, it will be reverted soon unless you remove it from its parent group (=`guest`) first.
