### ISSUE TITLE
args.Player.TPlayer.hostile is always False.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1385]
`args.Player.TPlayer.hostile` is always False no matter the hostile status, this breaks pvp features and plugins who use this option.

**Comment by tlworks** [comment]
Most likely missing in OTAPI, can close if this is the case.

**Comment by Zaicon** [comment]
![Image](http://i.imgur.com/WC3YeoD.png)

```
private void TestPlugin(CommandArgs args)
{
	args.Player.SendInfoMessage("Hostile: " + args.Player.TPlayer.hostile);
}
```

Appears to be working fine for me.
