### ISSUE TITLE
TShock's automatic port-forwarding doesn't work

### ISSUE THREAD

**Issue by OnsenManju** [NyxStudios/TShock#1387]
(TShock current release 4.3.22)
If answer "y" to "Automatically forward port? (y/n)" at startup, stock (vanilla) server registers its port mapping to UPnP-enabled router after loading the world, but TShock doesn't.

- [filtered packet contains "Terraria" (stock server)](http://i.imgur.com/JDbf2rZ.png)
- [filtered packet contains "Terraria" (TShock)](http://i.imgur.com/uBJaBud.png) -- there is only packet for checking update

(Maybe it multicasts to 239.255.255.250 beforehand in order to discover the router, but that's too noisy because other applications also do the same way)

If TShock disables this feature intensionally, it would be better to hide such an option.
(related: [the forum post](https://tshock.co/xf/index.php?threads/ip-need-help-hurry.4918/#post-47707))

**Comment by nicatronTg** [comment]
Does this work on Vanilla Linux servers through mono?

**Comment by OnsenManju** [comment]
Hmm, vanilla server's port forwarding doesn't work on Linux.
During the server was running, no SSDP packet regarding Terraria seemed being sent.

On Linux, I'm using GOG version of Terraria and launched it as follows:
`~/GOG Games/Terraria/game$ ./TerrariaServer -x64`
It looks like vanilla server uses MonoKickstart to run, but I'm not sure what version of Mono is used (4.0?).

BTW, TShock on Mono 4.8.0/Linux had the same result as Windows.

**Comment by OnsenManju** [comment]
?
Did you mean running Windows binary on Linux by using Mono?

**Comment by nicatronTg** [comment]
If it doesn't work in the Linux Terraria server, I don't think we'll be investigating fixing or implementing this functionality. There is definitely a UPnP plugin on the forums.
