### ISSUE TITLE
v4.3.22 Does not run on ubuntu

### ISSUE THREAD

**Issue by justinmchase** [NyxStudios/TShock#1390]
I followed [these steps](https://turtlesaur.wordpress.com/2015/07/14/setting-up-a-terraria-server-on-ubuntu/) but when I went to run tshock it would just fail at about 70% of resetting objects with the error "Aborted" or something like that.

I downgraded to version 4.3.20 and now its working. Just an FYI.

**Comment by nicatronTg** [comment]
Next time, please follow [our official documentation](https://tshock.readme.io/docs/getting-started) when installing TShock and read the [ultimate help guide](https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/).

We'd love to help you out, but you haven't given us anything to help you out with -- we need log files, version numbers, and verification that you've followed our mono suggestions before we can help.

Thanks!

**Comment by nicatronTg** [comment]
You appear to be a very sensible developer (based on your Github profile) and I'm actually quite confused here. If you do have reproduction steps, log files, and the like, we'd be happy to help -- but you don't and I don't really get why.

**Comment by justinmchase** [comment]
I didn't have much time and I see that the release was fairly new and no new bug was reported on this yet so I wanted a starting point. I also don't have a useful log file for you, looking into it shows virtually nothing. No crash dump, no log data, just sudden 'Killed'.

Usually a bug like this gets created then if others experience it they find it and add clues to the puzzle until we have enough to act upon. You may want to add a bug template to github if you want specific questions answered first.

I'm now wondering if the machine I provisioned is running out of memory, if I create a medium or small world it gets a little further. What are the memory requirements? I don't seem to see that in the documentation anywhere.

Screenshot
<img width="300" alt="screenshot 2017-01-31 12 15 16" src="https://cloud.githubusercontent.com/assets/10974/22478392/3fcbae94-e7af-11e6-9194-106aae8dd23b.png">

ServerLog.txt
```
ubuntu@ip-172-31-31-60:~/tshock$ cat ServerLog.txt
[01/31/17 18:14:42] [Server API] Verbose: TerrariaApi - Server v2.0.0.0 started.
[01/31/17 18:14:42] [Server API] Verbose: 	Command line: /home/ubuntu/tshock/TerrariaServer.exe
[01/31/17 18:14:42] [Server API] Verbose: 	OS: Unix 4.4.0.53 (64bit: True)
[01/31/17 18:14:42] [Server API] Verbose: 	Mono: True
[01/31/17 18:14:43] [Server API] Info: Plugin TShock v4.3.22.0 (by The TShock Team) initiated.
```

**Comment by justinmchase** [comment]
I reprovisioned a machine with 2GB of memory and its getting further so it seems like it was hitting a memory issue.

**Comment by justinmchase** [comment]
It worked! It may be worth putting into the [Official Documentation](https://tshock.readme.io/docs/getting-started):

> You'll need:
> * Microsoft .NET Framework 4.5 (on Windows)
> * Mono 4+ (on Linux/BSD/UNIX derivatives)
> * **At least 2GB of memory**

**Comment by nicatronTg** [comment]
Good idea!

**Comment by nicatronTg** [comment]
@justinmchase we've made the [change on the docs](https://tshock.readme.io/docs/getting-started)!
