### ISSUE TITLE
command "/region define [name]" not work

### ISSUE THREAD

**Issue by wolskiCN** [NyxStudios/TShock#1391]
- sorry. That's not bug. My fault.

**Comment by ProfessorXZ** [comment]
This produces unwanted behaviour, so yes; it is an issue caused by null `User` objects in /region define because TShock simply assumes the player is logged in.

**Comment by nicatronTg** [comment]
Hiyas @wolskiCN @ProfessorXZ.

I'm really confused as to what the issue is here. Was something in the original issue body that was since removed?

**Comment by OnsenManju** [comment]
Here it is.
https://tshock.co/xf/index.php?threads/tshock-4-3-22-for-terraria-1-3-4-4.4921/page-2#post-47821
