### ISSUE TITLE
Can't spawn Traveling Merchant with /sm

### ISSUE THREAD

**Issue by tanpro260196** [NyxStudios/TShock#1392]
- /sm or /spawnmob command does not work with traveling merchant. When I type the command, the chat say: "XXX has spawn Traveling Merchant 1 time(s)" but actually nothing happened.
- I tried the command with both name and id, same result.
- I tried both the lastest general-devel and stable build (100% clean), same result.

Also, some players on my server report that no matter how long they wait, traveling merchant never spawn naturally (latest general-devel build). Properly just unlucky though.

**Comment by OnsenManju** [comment]
[Traveling Merchant](http://terraria.gamepedia.com/Traveling_Merchant)'s name is misspelled as "Trave**ll**ing Merchant".
```
type NPC.name            NPC.displayName
368  Travelling Merchant Traveling Merchant
```
TShock uses `NPC.name` when spawning mobs (mentioned at #1383), so I guess the traveling merchant won't emerge due to that.

**Comment by tanpro260196** [comment]
So if I type "Travelling Merchant", will it work then?

**Comment by tlworks** [comment]
Whatever you do it will not work, ever.

**Comment by hakusaro** [comment]
For the record, if the Terraria team wasn't already aware of that @OnsenManju, it's been sent in as a bug report and will probably be acted on in the future.

**Comment by OnsenManju** [comment]
@hakusaro (nicatronTg) Ah thanks! That misspelling is definitely Terraria's bug.
But I think this is still TShock's issue that using `NPC.name` as default will cause several problems when spawning mobs.

**Comment by WhiteXZ** [comment]
Fixed in https://github.com/NyxStudios/TShock/commit/90505435bafefac46b50dee49513fc48d96530de
