### ISSUE TITLE
autosave hang?

### ISSUE THREAD

**Issue by TimVNL** [NyxStudios/TShock#1395]
Hi, 
I just installed tShock and I getting this 5 times in a row 

tShock Version: 4.3.22.0

Plugins: only the defaullt ones

Log: https://gist.github.com/TimVNL/86e4bb8e7729d521e2f783c6c821ce54
Config: https://gist.github.com/TimVNL/c3b4f2863de455b166e48743e34dd9b1

is this normal? Here is my config.json
https://gist.github.com/TimVNL/c3b4f2863de455b166e48743e34dd9b1

**Comment by nicatronTg** [comment]
I'm sorry -- you're saying that you get this 5 times repeatedly? Can you upload logs and the version of TShock you're using (and specifically any plugins too)?
