### ISSUE TITLE
/item & /give command can't spawn certain items correctly

### ISSUE THREAD

**Issue by OnsenManju** [NyxStudios/TShock#1398]
Such as ["Treasure Bag" or "Strange Plant"](http://terraria.gamepedia.com/Item_IDs_Part12), items that have the same name with various IDs are spawnable only the single type even if different ID is specified.

e.g. Both `/item 3318` and `/item 3319` will spawn King Slime's treasure bag.
(And that is an expert mode item even if performed in normal world.)

Maybe this happens because new item will be set default by its name at `TSPlayer.GiveItem()`.
https://github.com/NyxStudios/TShock/blob/master/TShockAPI/TSPlayer.cs#L898-L899
```
// This is for special pickaxe/hammers/swords etc
Main.item[itemid].SetDefaults(name);
```

**Comment by Kojirremer** [comment]
Deathweed Planter's two variants (corruption & crimson) also have this issue. Only one type will spawn.
