### ISSUE TITLE
Ban list in the proper order.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1400]
Basically all bans show randomly in the list, bans do not get shown in the list on date. This is rather annoying and confusing if you banned someone and their name just ends up randomly in the list to be forgotton forever.

**Comment by tlworks** [comment]
I'd also like to add upon this; Please make temp-bans remove their data entry upon expiring.

**Comment by WhiteXZ** [comment]
Temp-bans should be removed when the banned user attempts to rejoin, and the ban has expired.
If that isn't working then I'll have a look at fixing it

**Comment by hakusaro** [comment]
I think his point is that they should be removed after expiration, not
after an attempted join. Possibly because the database gets large?

**Comment by Enerdy** [comment]
On the other hand, keeping temp-bans in the system even after they've expired allows us to keep track of a player's "criminal record". Perhaps this should be configurable?

**Comment by WhiteXZ** [comment]
Tracking and deleting temp-bans (potentially across sessions) sounds far more resource intensive than is practical

**Comment by hakusaro** [comment]
They're deleted when a player joins. That's hardly a "criminal record."

**Comment by Enerdy** [comment]
@hakusaro that's current behaviour? Hmm...

**Comment by hakusaro** [comment]
@Enerdy https://github.com/NyxStudios/TShock/issues/1400#issuecomment-281322725?

**Comment by tlworks** [comment]
Perhaps change the banning method for ID's as well? If a user has numbers in their name and you try to short-ban them (Not filling in their whole names) You'll end up banning another person which is using that ID. Now this seems a little bit much but it might be an idea for those who don't understand. '/ban addid' or something, same goes for XID (I believe?).

And temp bans don't seem to be deleted once expired. If a user is banned and their ban expired you can still check their banned status and it'll tell the ban has expired but the data entry remains.

**Comment by WhiteXZ** [comment]
Closing unless defined behaviour is shown to not be functioning correctly (i.e., temp ban data removed once user rejoins after expiration)
