### ISSUE TITLE
[ITEM] Prevent spawning of 3828.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1402]
`ID 3838, Eternia Crystal.`

Now I do understand you can disallow that item from being spawned by setting a certain option in the config, but this option is out of the question when you're on a free item server where people may use the '/item' command to get their desired items. Turning this option on would disallow the player to spawn any required banned items in the Server to make it playable and not very much griefable.

I want this item to be disabled from spawning because if a user spawns 999 of these during the OOA (Old One's Army) they can summon an infinite amount of minions which could be highly abused.

**Comment by hakusaro** [comment]
I'll implement this in a plugin if you [ship me one pavlok](https://pavlok.com/) that can be controlled by users in Slack.

I'm not joking.

**Comment by OnsenManju** [comment]
@hakusaro lol What habit you want to break?

Btw I think it isn't already suitable for "ordinary" multiplay at the point of "item free server"...
So players in such a server should be stripped any permissions about summoning invasions/bosses rather than banning certain items.

**Comment by hakusaro** [comment]
@OnsenManju I want to use it as an alarm clock and as an alarm for RescueTime to tell me that I've gone over my allotted time in the TShock slack for the day c:

Very serious about wanting it.

**Comment by tlworks** [comment]
If it wasn't an expensive scam, I would've gotten you it @hakusaro 👍

**Comment by hakusaro** [comment]
@tlworks trust me, it does work. I've seen the reviews. Offer still stands c:

**Comment by WhiteXZ** [comment]
Closing until shank gets a pavlok
¯\_(ツ)_/¯
