### ISSUE TITLE
Wave 0.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1415]
Unsure whether this is a Vanilla or TShock issue. Happens both on SSC and Non-SSC, occasionally the event gets stuck on wave 7 and doesn't progress on non-SSC (possibly due to the eternia stand being underground.)

Wave 0 basically means never-ending wave unless crystal destroyed.

![88fde0bae15e8c998b18cfee52e7f78b](https://cloud.githubusercontent.com/assets/19647337/24323351/9818f4a0-1174-11e7-8c21-14c18fbfdff3.png)

**Comment by OnsenManju** [comment]
It looks like Terraria's issue.
- [Bug in the Old one´s army](https://forums.terraria.org/index.php?threads/bug-in-the-old-one´s-army.51674/)
- [Weird old one's glitch](https://forums.terraria.org/index.php?threads/weird-old-ones-glitch.53013/)
- [(1.3.4.4) Old One's Army event not progressing (multiplayer)](https://forums.terraria.org/index.php?threads/1-3-4-4-old-ones-army-event-not-progressing-multiplayer.53336/)
- https://www.youtube.com/watch?v=PbrLI0a8CdI
- etc.

**Comment by WhiteXZ** [comment]
Thanks @OnsenManju 

Closing unless this does turn out to be a TShock issue
