### ISSUE TITLE
Cannot see levers and switches animate or timers light up once activated

### ISSUE THREAD

**Issue by shortybsd** [NyxStudios/TShock#1421]
In this version of TShock for some reason I cannot see levers or switches animate when I flip them. Same with timers. They will only light up if you have a switch linked to a timer (to properly light up the timer). Switches and levers on another client screen will animate when others flip them. I confirmed this with 10 players so far.

**Comment by ProfessorXZ** [comment]
This is most likely caused by packet 59 which doesn't seem to be handled by TShock.

**Comment by ProfessorXZ** [comment]
Confirmed the above statement.

@shortybsd you can try using https://www.dropbox.com/s/duv3c5jyjpqqzib/TShockAPI.dll?dl=0 if you like, just be sure to test every possible case and test it with multiple clients.

**Comment by shortybsd** [comment]
That file makes it lock up on "Requesting Tile Data".

**Comment by hakusaro** [comment]
@ProfessorXZ got some sauce for that patch?

**Comment by hakusaro** [comment]
@ProfessorXZ dearest professorx, do would you mind sharing the delicious source code to your wonderful build?

**Comment by ProfessorXZ** [comment]
@hakusaro due to the fact that I do not have enough will to work out the reference mess and can't get the solution to build I'll just paste the solution here and ask you nicely to commit it for me:

```
   private static bool HandleHitSwitch(GetDataHandlerArgs args)
   {
       var x = args.Data.ReadInt16();
       var y = args.Data.ReadInt16();

       args.Player.SendTileSquare(x, y);
       return false;
    }
```

**Comment by hakusaro** [comment]
As discussed in #high-charity, can you provide more information on:

* Why doesn't this work in the first place now (e.g., if we don't explicitly block the packet why is it not being sent by vanilla)?

**Comment by mistzzt** [comment]
That's a OTAPI-related issue. @DeathCradle 

![hit-switch](https://cloud.githubusercontent.com/assets/12794966/25572602/33c62230-2e6f-11e7-8914-0655713f87af.png)

**Comment by DeathCradle** [comment]
Thanks @mistzzt.
Please give commit https://github.com/NyxStudios/TShock/commit/edad442ec8b6f0fad1480ec3715371c1bab529d8 a try (https://travis.tshock.co/t-1.3.5/1585/)

**Comment by WhiteXZ** [comment]
https://github.com/NyxStudios/TShock/commit/edad442ec8b6f0fad1480ec3715371c1bab529d8 seems to work
