### ISSUE TITLE
Load failed!

### ISSUE THREAD

**Issue by SodaDudeTx** [NyxStudios/TShock#1433]
So when I'm starting up the world like for example I press 2 to select my 2nd world and it starts loading then at the end it says "Load Failed."

**Comment by tlworks** [comment]
Okay, but we can't really do anything about this without logs/screenshots.

**Comment by hakusaro** [comment]
Please see #support on Discord or post on the forums. Be prepared to provide a copy of your world file and backup if this is an unstable version of TShock and you can reproduce world corruption consistently.

If this is a TShock unstable build and you can recreate this issue under controlled circumstances we will open this issue and fix it with the utmost urgency.

**Comment by hakusaro** [comment]
![screen shot 2017-04-28 at 4 10 50 pm](https://cloud.githubusercontent.com/assets/532647/25549133/4c81be22-2c2d-11e7-9833-ee6cff6465da.png)
