### ISSUE TITLE
recieving tile data stuck 

### ISSUE THREAD

**Issue by TimVNL** [NyxStudios/TShock#1435]
Hi All,

I am busy with my terraria docker container with the latest build:  
https://travis.tshock.co/t-1.3.5/1583/  

With a existing word and loading tile data is stock on 53%  
  
I already updated the plugins etc...

Can someone help?

Dockerfile is here: https://hub.docker.com/r/timvnl/tshock/~/dockerfile/

**Comment by hakusaro** [comment]
That Docker link 404s. How much ram do you have allocated?

**Comment by hakusaro** [comment]
I'm gonna assume this is a RAM issue unless you reply back. Stuck loading tile data can happen if you don't give it enough memory.

**Comment by TimVNL** [comment]
@hakusaro I have 4096MB allocated for the containter this was enough with older versions of tshock.  Here is the github link to the Dockerfile: https://github.com/TimVNL-Dockers/tshock

**Comment by hakusaro** [comment]
Yeah 4gb is definitely enough. Do you mind sharing your world file so we can test this?

**Comment by TimVNL** [comment]
@hakusaro No Problem! But I am not home right now will share as soon as I get home :) Do you need the config.json also?

**Comment by TimVNL** [comment]
Here is the world file and config.json
[san_terraria.zip](https://github.com/NyxStudios/TShock/files/968211/san_terraria.zip)

**Comment by TimVNL** [comment]
@hakusaro Was missimg a package I think added psmisc and net-tools and the 3 May build works :)
