### ISSUE TITLE
ChatAboveHeads causes black magic on non-SSC Servers.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1436]
What other people see when people talk;
https://i.gyazo.com/49ee8398f7c9b968b87d27d34f94a745.png

What you see on your own name when you talk;
https://i.gyazo.com/b0d5d27fc52ef4230c1438eaa2ae1e34.png

Basically when ChatAboveHeads is enabled in an non-SSC Server, your prefixes don't show up in your own Chat. If this works without Plugins (haven't tested myself yet) please let me know or close this issue.

**Comment by tlworks** [comment]
Tested on TShock without Plugins and still occurs.

**Comment by WhiteXZ** [comment]
@tlworks Did you set your ChatAboveHeadsFormat in your config file?
![terraria_2017-05-03_15-17-27](https://cloud.githubusercontent.com/assets/2648373/25649336/a385e858-3013-11e7-852b-4e949c208014.png)
First line is default format (`"{2}"`)
Second line is `"{1}{2}{3}"`

**Comment by tlworks** [comment]
I've set it to;
`  "ChatFormat": "{1}{2}{3} {4}",
  "ChatAboveHeadsFormat": "{1}> {2} <{3}",`
Because it doesn't (or didn't) work otherwise with suffix & prefixes, though it makes no difference since it works on SSC but not on NSSC locally for the player.

**Comment by WhiteXZ** [comment]
My screenshot was non-SSC

**Comment by tlworks** [comment]
So I would have to set `ChatFormat` to `{2}` only?

**Comment by WhiteXZ** [comment]
`ChatFormat` doesn't effect sent chat when ChatAboveHeads is enabled currently. This is an oversight that needs to be fixed

**Comment by WhiteXZ** [comment]
528d9c6 should solve this - awaiting confirmation

**Comment by tlworks** [comment]
Rather than posting it in a comment section;

In case this will be forgotten, this breaks the current (and awesome) way of ChatAboveHeads in SSC (NSSC?) where the Chat also shows above the player themselves, this was a neat and a long awaited feature/fix.

Would be great if this could be added again.

@WhiteXZ

**Comment by ProfessorXZ** [comment]
Closing this as the main issue has been fixed by @QuiCM
