### ISSUE TITLE
Warps database corrupted when swapping worlds

### ISSUE THREAD

**Issue by briman0094** [NyxStudios/TShock#834]
The warps table in the database enters a sort of "corrupted" state if you swap out (or delete and re-generate) worlds in a specific server instance without clearing the "tshock.sqlite" database (or at least the Warps table). For example, say I create a world called "WorldA" and a warp called "test". Then I delete "WorldA" and make another world called "WorldB". If I try to create a warp called "test", it will tell me that I can't because the warp already exists (`INSERT INTO` affects zero rows because the only unique key is WarpName). If I try to delete it, however, it will tell me it cannot find the warp because `WHERE WarpName = @0 AND WorldID = @1` will also affect zero rows due to the current warp named "test" having a different world ID.

The solution I propose is to create an AUTOINCREMENT column for warps that is used as the primary key, and have a separate UNIQUE pair on WarpName and WorldID. This way if two warps in different worlds have the same name, they will function properly and users won't have to manually clear the warp database when generating a new world. I don't know how I should implement the unique pair creation into the SqlTable.cs class as I'm not immediately familiar with the TShock API and its code conventions, but if somebody can point me towards how that should be implemented I'd be happy to fix it.

**Comment by weedy** [comment]
I'm hitting this bug right now.
Swapped from a medium to large world, tried to make a "rightOcean" warp and I'm getting name collisions with the old map.

**Comment by nicatronTg** [comment]
@olink did this issue get resolved in 1c7fe90?

@weedy can you provide exact steps to reproduce?

**Comment by weedy** [comment]
- Play in a med world
- wait this is small
- swap out map for large world
- run to both edges of map to make "leftOcean" and "rightOcean" warps just like on old map
- "warp already exists"

Same as the original reporter

**Comment by Olink** [comment]
Make sure that you are using the latest released version, and not one prior to the fix mentioned above.

**Comment by nicatronTg** [comment]
And leave a note if it still isn't resolved.
