### ISSUE TITLE
Possible bug in RestAPI - missing support for Unicode

### ISSUE THREAD

**Issue by Grandpa-G** [NyxStudios/TShock#858]
My tests indicate that Unicode support is missing when using the RestAPI. For example, if a username has Unicode characters, then they are translated to ? when sent to the requestor.

I believe (and could be easily wrong), line 160 in Rest.cs [ASCII changed to UTF8]
[CODE]e.Response.Body.Write(Encoding.ASCII.GetBytes(str), 0, str.Length);[/CODE]should be changed to
[CODE]e.Response.Body.Write(Encoding.UTF8.GetBytes(str), 0, str.Length);[/CODE]
I haven't tried to make this change but this appears to be the place where the Unicode is being dropped.

**Comment by nicatronTg** [comment]
Well, you could always try to change this and send a pull request if you
want to have it added.

**Comment by Grandpa-G** [comment]
I did some testing and got it to work (for what its worth). I was wrong in the solution, at least on my server. The code that works for me is

[CODE]            e.Response.Body.Write(Encoding.Default.GetBytes(str), 0, str.Length);[/CODE]

The change is Ascii to Default for the Encoding type.

**Comment by nicatronTg** [comment]
This isn't a forum, by the way, to wrap code use three backticks opening and closing. Again, send a pull request and some screenshots showing how you've fixed unicode & how ascii behaves in the same environment.

**Comment by Grandpa-G** [comment]
I apologize for just cutting and pasting from the forum. I just was not careful.

I am just learning git so I have to figure out the pull request et. al. to do what you suggest.
