### ISSUE TITLE
Add a new V4 level for Rest

### ISSUE THREAD

**Issue by Olink** [NyxStudios/TShock#867]
* This should create a V4 route for every single rest command we have, because versioning our rest commands is wacky and we should have some sort of real versioning.
* This should add new routes that have been requested, such as SSC routes, etc.
* This should break the routes into submodule classes, such as Rest/BanRoutes.cs
* This should consider creating a system where if a request goes to an older version that the reply has a warning, and/or the cosole is warned.  This will force developers to update their app for V4.

**Comment by nicatronTg** [comment]
At least one suggestion has been to provide more OS & hardware info in the server status route, seems doable here. I'm working through getting all of the suggestions mapped out, though, so I'll probably have a more concise list of requested routes in a bit.

**Comment by Olink** [comment]
Consider using a real REST API foundamental and allow self exploration via a links section on most responses.  User would have links to SSC, Ban, etc.

**Comment by Grandpa-G** [comment]
You are welcome to use any of the additions I have made (probably could be done better). I have more that I would like to put in, but they are not at the top of my priority list. The source is at
https://github.com/Grandpa-G/TShockRemoteAdmin

**Comment by Olink** [comment]
Documentation generation has been automatted, future rest routes will require the documentation.

**Comment by WhiteXZ** [comment]
https://tshock.co/xf/index.php?threads/add-prefix-suffix-to-rest-v2-groups-update.3720/
"Adding the prefix and suffix to this group update entrypoint would complete all the data for a group..."

**Comment by nicatronTg** [comment]
Not realistically happening because Orion will have a REST API.
