### ISSUE TITLE
Ssc is not working on my calnforge

### ISSUE THREAD

**Issue by twitch-ayrenn** [NyxStudios/TShock#874]
So i have enabled ssc:true and set the sscsave: 5 and when ever i logg in to the clanforge server i still have my items. does this have to d  with loins and other stuff because i want the player to join evry time whit copper tools and no other stuff evry time. the server im making is a minigame one so there not suppose to have any items and if i can remove the copper tools that would even be better so plz help:D AND SRY FOR MY ENGLISH<3

**Comment by Olink** [comment]
This is not a support forum.
