### ISSUE TITLE
Ssc not working on my clanforge server. why?

### ISSUE THREAD

**Issue by twitch-ayrenn** [NyxStudios/TShock#875]
So i have enabled ssc:true and set the sscsave: 5 and when ever i logg in to the clanforge server i still have my items. does this have to d with loins and other stuff because i want the player to join evry time whit copper tools and no other stuff evry time. the server im making is a minigame one so there not suppose to have any items and if i can remove the copper tools that would even be better so plz help:D AND SRY FOR MY ENGLISH<3

**Comment by Enerdy** [comment]
wtf

**Comment by twitch-ayrenn** [comment]
what

**Comment by Olink** [comment]
See #874

**Comment by twitch-ayrenn** [comment]
so what is this forum for beacouse when i go to tshock it sayd isceus here:d

**Comment by Olink** [comment]
Issues are for intelligent people to post intelligent bugs, that aren't user error.  Your issue is user error.  Therefore you should go to the forums and post a help thread like all the other people who seem to understand the concept of help forums.

**Comment by twitch-ayrenn** [comment]
ok sry i just want help:[

**Comment by nicatronTg** [comment]
@twitch-ayrenn when you went to post your issue, it said to read the guidelines before contributing. Go to the forums and post a support thread.

Also, you should ask ClanForge/Multiplay, not us, for help.
