### ISSUE TITLE
This is not a meritocracy.

### ISSUE THREAD

**Issue by Olink** [NyxStudios/TShock#885]
Remove this please, as this is not required in the "Contributing" guidelines and is an intended dig at me.

If not, please provide a reason why this is even remotely relevant in our Contributing Guidelines, has anyone ever expected privilege due to a commit to this repo?

**Comment by Olink** [comment]
http://meerkatapp.co/nicatrontg/42502e7a-756e-49e1-a782-ba95944a0e6c

**Comment by Olink** [comment]
And instead of answering the question, he rants on some live talk.

**Comment by Olink** [comment]
I know

**Comment by Olink** [comment]
Which is my point.

**Comment by Olink** [comment]
Owner acting like an owner.  Instead of replying to this issue, he talks on a private live stream, and then deletes the relevant comments here.

**Comment by nicatronTg** [comment]
Irrelevant comments are not helping this discussion. Arguably, the line isn't needed to explain that this isn't a meritocracy, so I agree that it can be removed fairly trivially.

**Comment by Olink** [comment]
For transparency: This is not what was said in private, and it should be noted that his behavior in regards to this topic was not very mature.
