### ISSUE TITLE
New guideline for every commit is archaic and inadequately defined.

### ISSUE THREAD

**Issue by Olink** [NyxStudios/TShock#886]
How long do we have to wait before people who have the ability to reply before we can move ahead with it.

Do we need a 2/3 or > 50% vote?

Are you intentionally making it impossible for end users to have a say on "new features etc" by including "Consensus is required from at minimum, a majority of contributors present and reachable in the community (plugin authors or commit players) during the last seven days."

Are you applying meritocracy (granting additional permissions to people who have done something) to this with this sentence? This seems to contradict your previous stance on it.

**Comment by rautamiekka** [comment]
I "just came" here, so I dunno, but I know what that sounds like. I'd love to say it, but I'll pass.

**Comment by Olink** [comment]
Reverted the change to contributing guidelines based on the realization that no one, not even devs, visit github.
