### ISSUE TITLE
Add /pos [name] command that reports users x,y tile position or the user with the name specified

### ISSUE THREAD

**Issue by Olink** [NyxStudios/TShock#887]
TShock has TPPos which teleports to a tile x,y.  Since we have that we should provide a way for a user to get their x,y position or that of a user.

Discuss.

**Comment by Enerdy** [comment]
I'm using an incomplete implementation of this at the moment: a /coords command that has the user hit a point and displays that point's coordinates.

Being able to directly check your/others coordinates sounds like a good idea. If this doesn't get implemented into tshock I'll implement it into EssentialsPlus.
