### ISSUE TITLE
When running Tshock, friends can't connect?

### ISSUE THREAD

**Issue by hamsterben5** [NyxStudios/TShock#890]
Alright, so I installed the latest version of TShock onto my Terraria server I'm using with Hamachi. My friends usually play with me on regular Terraria, but I heard about TShock so I thought I'd try it. I loaded up the TShock server and it worked fine, I summoned 200 werewolves for fun and murdered them all. I told my friend my IP, and he couldn't connect. I tried loading a regular server. Worked fine. Any solutions here? I've tried to portforward soo many times, it never works. I always resort to Hamachi.

**Comment by Olink** [comment]
We do not provide solutions for hamachi.  Ensure you are giving him your correct Hamachi ip and port.
You need to port forward if you wish for others to connect to your server normally.  You can try to use https://github.com/WhiteXZ/UPnP-Forwarder-Standalone/raw/master/UPnPForwarder/bin/Release/UPnPForwarder.exe and see if it works, however, we do not provide support for third party tools.

**Comment by nicatronTg** [comment]
At least try Tunngle, or ngrok. Hamachi is junk.

**Comment by HunnySenpai** [comment]
Sorry, I know this is quite late, but the problem is not Hamachi. Assuming he used the same connection for the regular server as he did Tshock, then I would say there's a problem with Tshock. Sorry, just saying that the problem isn't Hamachi. I would also understand if Tshock isn't compatible with Hamachi.

**Comment by nicatronTg** [comment]
@HunnySenpai the problem isn't TShock.
