### ISSUE TITLE
[Bug] /user password reports Command Failed on empty

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#899]
The command "/user password" reports "Command Failed, check logs for details" using the latest version of stable built TShock. Under the following circumstances, the code states that if there are exactly 3 parameters, it should function, otherwise it should report "args.Player.SendErrorMessage("Invalid user password syntax. Try {0}user help.", Specifier);" For some reason, it does not. Here is how to repeat issue:

1. Type /user password
2. Error should appear.

NOTE: Seems as if all other /user sub commands work fine, but only password causes this issue.

ERROR:
2015-04-12 22:34:01 - Command: ERROR: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TShockAPI.Commands.ManageUsers(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)

**Comment by Marcus101RR** [comment]
Further analysis show that it appears to only affect those sub commands that do NOT compare the sub command and at the same time the parameter count in one line. EG: password, group.

This is thrown out because, both of these sub command are trying to pull parameters outside their perspective if statements. See "Password" and "Group", they both try to pull parameters before checking them.

**Comment by nicatronTg** [comment]
I added a check to add; add wouldn't have caused an exception, but for consistency's sake, this is better.
