### ISSUE TITLE
Move all resources to a single folder

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#904]
Currently, we have random .dll files scattered around the project folder. They should be moved to a single ```Resources``` folder at the root and the ```create_release.py``` script should be updated to point to the new folder.

**Comment by Enerdy** [comment]
:+1:

Never understood why were there multiple _Bins folders around.

**Comment by Strinkor** [comment]
:+1: Good idea!

**Comment by WhiteXZ** [comment]
+1, no reason not to
