### ISSUE TITLE
Log more info on automatic player disabling by cheat checks

### ISSUE THREAD

**Issue by Enerdy** [NyxStudios/TShock#909]
Right now, whenever a player gets disabled by one of tshock's cheating checks, such as for using a banned item or wearing a banned armor, the console/log will only inform the host that the player got disabled, but will fail to give them any information regarding which item caused the check to trigger. We should at least add the item id to the informational message, be it on log-only, console, or both.

**Comment by Enerdy** [comment]
To clear things up, the player getting disabled does get informed of which item triggered the disable, it's just the console/logs that are not getting this information.

**Comment by Kromara** [comment]
I'd love to see this get some attention.

**Comment by Enerdy** [comment]
Will do tomorrrow qq.

Unless there are reasons not to.
