### ISSUE TITLE
Change colors in config to be int arrays

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#914]
For some reason, ```BroadcastRGB``` and ```SuperAdminChatRGB``` are defined as arrays of floats, but RGB colors take whole number integers between 0 and 255 for construction.

**Comment by Enerdy** [comment]
Why not simply make it a byte[]? That would have the added bonus of forcing it not to go above 255.

**Comment by nicatronTg** [comment]
@Enerdy you can't serialize a byte array as Json using our library.

**Comment by Enerdy** [comment]
Oh well, that's unfortunate. Alright, :+1: for the ints then.
