### ISSUE TITLE
Name Changing Issue

### ISSUE THREAD

**Issue by popstarfreas** [NyxStudios/TShock#921]
Recently, although apparently it has always been possible, people with modified clients are able to annoy staff and server owners by changing their names.

This is the use of PacketType.ConnectRequest and PacketType.PlayerInfo
Probably the best explanation is just to provide an example of how a modified client might implement it to modify their chat name:

```csharp
NetMessage.SendData(1, -1, -1, "", 0, 0, 0, 0);
NetMessage.SendData(4, -1, -1, FakeName, Main.myPlayer);
NetMessage.SendData(25, -1, -1, Main.chatText, Main.myPlayer, 0f, 0f, 0f, 0);
NetMessage.SendData(1, -1, -1, "", 0, 0, 0, 0);
NetMessage.SendData(4, -1, -1, RealName, Main.myPlayer);
```

The use of RealName on the last line is to change the name back so that when someone for example tries to do "/kick name", it won't work, or it will kick another player.

**Comment by nicatronTg** [comment]
Changing to PR wanted. Something should happen if a player changes their name (maybe a config item to disconnect the player). This is something that should happen relatively soon (not wait for Orion to do).

**Comment by Simon311** [comment]
I do not remember it ever being possible to actually change the name. Am saying this as someone who has experience with developing hacks for Terraria. I will look into this, but the likelihood is that this is either impossible or possible on a misconfigured server

**Comment by ProfessorXZ** [comment]
@Simon311 This most certainly is possible. The code shows it all, and I've already confirmed this in earlier releases.

**Comment by nicatronTg** [comment]
@popstarfreas thanks for reporting this. I know it took an inordinate amount of time to fix, but we greatly appreciate the initial report.
