### ISSUE TITLE
Formal Github Flow Proposal

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#924]
One of the interesting things that we've always had in this repository is the mix between inside and outside contributions as far as code merging goes. I definitely see value in having direct write access to the repository for collaboration (such as working with a team on a separate branch), but at the same time we also have a mantra of allowing outside pull requests.

I think we should really consider moving to Github Flow entirely, where we stop new code being pushed directly onto general-devel, and instead require branching and pull requests for most code. The exception to this is like build scripts and other things that aren't TShock related, but are stored in the repository. For most things, though I don't see why not. A pull request encourages code review, and discourages hastily written commits and untested additions.

The [introduction to Github Flow](https://guides.github.com/introduction/flow/) is a helpful read. If everyone seems to agree with this, I can draft some new contributing guidelines and throw them on #918 for further discussion pertaining to what exactly warrants a branch and what doesn't.

The exception to the normal Flow is that I want to at least keep a separate general-devel branch for the next release, and master for the previous stable. It makes a clear cut marker as to what is pushed and what isn't (and it also makes changelogs easier to parse).

@NyxStudios/tshock what do you guys think?

**Comment by WhiteXZ** [comment]
Good organisation is helpful. I also agree that PRs help encourage well thought out commits

**Comment by MarioE** [comment]
I'm all for it.
