### ISSUE TITLE
Add an ExpandoObject to TSPlayer to contain extra information

### ISSUE THREAD

**Issue by MarioE** [NyxStudios/TShock#930]
Plugins have to do *a lot* to attach extra information to players.

Sometimes this involves creating new player classes, and other times, this involves using a ```ConditionalWeakTable```. We need to just have an ```ExpandoObject``` to contain all this extra information.

**Comment by MarioE** [comment]
This does, however, beg the question as to how we should deal with multiple plugins attempting to use the same name for different information. Any thoughts?

**Comment by MarioE** [comment]
https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicobject(v=vs.100).aspx

This would actually be a better way to implement it.

**Comment by Enerdy** [comment]
:+1:

**Comment by WhiteXZ** [comment]
Done with ConcurrentDictionary
