### ISSUE TITLE
i cant run more than once!!! >:(

### ISSUE THREAD

**Issue by specterzxl** [NyxStudios/TShock#932]
why cant i run more than once it says somthin like

protocal network

(i need how to fix not whats worng)

**Comment by specterzxl** [comment]
its tshock btw

**Comment by Kromara** [comment]
I'm pretty sure that the issue that you're running into is that you're attempting to run two instances of TShock on a single port.
If this is the case, when you're setting up the second instance of TShock, just be sure to assign a different port.

**Comment by specterzxl** [comment]
thanks you :D ill try a differnt port

**Comment by specterzxl** [comment]
thank you soooooooooooooo muc it work on the port 6666 <3 forever in debt

**Comment by Kromara** [comment]
I'm glad that I was able to help.

**Comment by Enerdy** [comment]
These are not the support forums :(.
Please use TShock's Help and Support subforum (https://tshock.co/xf/index.php?forums/help-and-support.11/) for targeted, individual issues like this in the future. You should only open a github issue when reporting a bug included in the latest version.

**Comment by Kromara** [comment]
I knew that this wasn't the correct location, but was unsure where the
correct one was. (I usually just come to you, @Enerdy! :))
