### ISSUE TITLE
Investigate if time Halloween events and Christmas events can be disabled serverside

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#933]
Apparently the client checks for these to be happening in certain conditions, which allows clients to buy Halloween items jpby setting their local times to holidays. I've contacted Yorzi, but I don't know if he'll fix the issue. Can we work around it?

**Comment by WhiteXZ** [comment]
We have commands that disable hallowe'en, Christmas, etc. However these only affect server-side operations such as which mobs spawn. Seeing as the server cannot change shop items, I doubt we can do anything

**Comment by WhiteXZ** [comment]
Needs more investigation now that 1.3 has hit. cc @nicatronTg
