### ISSUE TITLE
found it unstable on Linux with mono

### ISSUE THREAD

**Issue by orangetangerine** [NyxStudios/TShock#939]
I got a Cloud Server, Ubuntu 14, using mono to run TShock for 1.2.4.1
Game Client can connect to the TShock but quickly timed out whthin minutes.
(The Appearance is Server can receive client talking msg, but client can not receive broadcast from server, and client can not achieve anything from digging )
And I format Server to Windows 2008... Everything goes well...

I don't know why, and I come here for help

I've try mono-3.0.10 and mono-4

**Comment by nicatronTg** [comment]
Try 3.12?

**Comment by Ijwu** [comment]
Perhaps a similar issue to #935. Try following some of the discourse in that issue and perhaps some of the things pointed out by @tylerjwatson might help you.

**Comment by rautamiekka** [comment]
It's funny that I have Mono runtime 2.10.8.1-1ubuntu2.3 installed on Ubuntu 12.04.x LTS among a load of other necessary Mono packages and TShock has always run with those.

Seemingly the runtime itself is ancient when the rest of Mono ain't but it's all compatible and functional; haven't tried coding with Mono, just running.

**Comment by orangetangerine** [comment]
@nicatronTg @Ijwu 
I encountered crash sometime running on Mono-4.0.1 too
I'll attach stack here if it happen again.
compiling Mono-3.12 and report later

**Comment by tylerjwatson** [comment]
Mono 2.10 includes a very primitive version of sgen which is not enabled by default on such legacy versions.  Using TShock on mono-2.10 uses the `boehm` GC which is not limited to problems in our scenario.

Mono-3.12 is not going to solve your problems.  You have two workarounds which I have found out so far, I am still a fair bit away from finding out the root cause, so YMMV.

1)  Use boehm with mono > 2.10.  It is slightly slower, however has none of the issues reported with sgen:
```
tshock:$ mono-boehm TerrariaServer.exe
```

Or, 2) tweak sgen's parameters if you're adamant you want to use it:

```
MONO_GC_PARAMS=nursery-size=256m mono TerrariaServer.exe
```

I found this works on a vulnerable environment.

**Comment by orangetangerine** [comment]
@tylerjwatson 
"mono-boehm" works out. No timeout happens so far.
I know nothing about .Net or Mono, so I can't give any help...

I think I can format my Cloud Server and back to Ubuntu finally...

**Comment by orangetangerine** [comment]
well..crash happened
Stacktrace:


Native stacktrace:

	mono-boehm() [0x4b3988]
	mono-boehm() [0x50ac13]
	mono-boehm() [0x42aec2]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f5fb7329340]
	mono-boehm() [0x5ffef7]
	mono-boehm() [0x60e044]
	mono-boehm() [0x60e766]
	mono-boehm() [0x60e20d]
	mono-boehm() [0x601795]
	mono-boehm() [0x60b286]
	[0x403c9fab]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted
orange@ip-172-31-19-53:~/temp/tshock_4$ mono --version
Mono JIT compiler version 3.12.1 (tarball Wed Jun 10 02:31:02 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by fshiori** [comment]
maybe you can try mono:latest docker for tshock.
I use it open dedicated server over 2 weeks on my VPS which running CentOS 6.6.

**Comment by WhiteXZ** [comment]
If this is still an issue with TShock 4.3 for Terraria 1.3, please create a new issue
