### ISSUE TITLE
tShock Lags Like A Melon

### ISSUE THREAD

**Issue by SoSeif890** [NyxStudios/TShock#941]
When I Open tShock With The 127.0.0.1 IP Address It Works Fine I Can Do Anything Lag Free With Nothing Bothering Me. But When I Open It For public it lags when it is starting sometimes even crashes  I don't know why it does that. So any help would be appreciated!

**Comment by WhiteXZ** [comment]
Please create a thread in the [help & support] (https://tshock.co/xf/index.php?forums/help-and-support.11/) forum. Remember to include any logs that may be relevant.

**Comment by SoSeif890** [comment]
@WhiteXZ Okay. Thanks anyway :)!
