### ISSUE TITLE
Load data only if playing

### ISSUE THREAD

**Issue by Schwertspize** [NyxStudios/TShock#942]
Is it possible to load the map into ram when the first player connects and fully unload the map and release that ram space if the last person left? (especially on small private server) this would save much ram...
maybe this can be dun with only launching TerrariaServer.exe if the first person is connecting and supply a wrapper which says "Hey, wait! The server gets started" to the client...

**Comment by Ijwu** [comment]
That's likely not something we can easily implement, from the top of my head. 

I also doubt we'd officially endorse/create a wrapper, but I suppose it's one way of going about this. Especially now while we're getting ready to port 1.3 there likely won't be anyone taking on a project, albeit likely a small project, like this on at the moment,

**Comment by nicatronTg** [comment]
Tagging as pull request wanted but I wouldn't expect this to happen...ever...

**Comment by Simon311** [comment]
Not sure how this can be achieved via TShock. 
I think this issue needs to be closed, since this can only be done with a wrapper. 
Even if we did want this in TShock - there is a 99.99% chance this would require modifications to TSAPI.
