### ISSUE TITLE
Pirate event not triggering properly

### ISSUE THREAD

**Issue by HALive** [NyxStudios/TShock#945]
When I tried to trigger the Pirate Event on a tShock server it did not trigger properly.
After left clicking the item it said "Pirates approacing from West/East" and the progressbar on the bottom right has showed up. Shortly after the progressbar disappeared. 
After a few seconds the message "Pirates have arrived" shows up and the pirates spawn. The event progressbar does not show up. 
After killing the pirates for a bit the event did not end and the Flying Dutchman did not spawn once. Also, the pirates kept on spawning.
I have tried reproducing the issue on a Vanilla server (Using the same map and a simmilar trigger Position), but it did work properly there.

I Used tShock 4.3.0 for 1.3.0.3 (pre 1).

**Comment by Patrikkk** [comment]
Yes, this is a known issue. Thanks for the report! :) We will fix it hopefully soon!
(try avoiding pirate event until then :P )

**Comment by WhiteXZ** [comment]
Fixed in a recent commit
