### ISSUE TITLE
Random string of text on top of screen

### ISSUE THREAD

**Issue by Puremin0rez** [NyxStudios/TShock#948]
Peoples clients are crashing randomly and everyone else who doesn't crash on the server gets a giant string of white text at the top of the screen that goes across it (something like "asdas_____e____234243_____edsa_____")

PR2 running Mono 4.0.2

**Comment by Kromara** [comment]
Those all happen to be characters that are commonly used to move, grapple
and change items on your hotbar. I was thinking it may be related to that.

**Comment by WhiteXZ** [comment]
No more reports received in 10 days
