### ISSUE TITLE
Server Crashed just after verifying.

### ISSUE THREAD

**Issue by hobnob11** [NyxStudios/TShock#950]
Mweeb has joined.
    Mweeb executed: /auth 3213750.
    Mweeb added Account hobnob to group superadmin
    Mweeb authenticated successfully as user: hobnob.
    Mweeb executed: /auth-verify.
    (Admin) Mweeb: waow
    (Admin) Mweeb: lol
    Mweeb executed: /help.
    Stacktrace:

      at <unknown> <0xffffffff>
      at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr)     <0xffffffff>
      at (wrapper alloc) object.AllocVector (intptr,intptr) <0xffffffff>
      at Terraria.Chest.UpdateChestFrames () <0x0002f>
      at Terraria.Main.Update () <0x07afb>
      at Terraria.Main.DedServ () <0x01aef>
      at Terraria.ProgramServer.InnerStart (string[]) <0x00777>
      at Terraria.ProgramServer.Main (string[]) <0x0008b>
      at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object     (object,intptr,intptr,intptr) <0xffffffff>

    Native stacktrace:

            /usr/bin/cli() [0x4b73d8]
            /usr/bin/cli() [0x50f13b]
            /usr/bin/cli() [0x423d22]
            /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f8728d7f340]
            /usr/bin/cli() [0x5d6487]
            /usr/bin/cli() [0x5d93d2]
            /usr/bin/cli() [0x5dd6f3]
            /usr/bin/cli() [0x5de3b9]
            /usr/bin/cli() [0x5f4719]
            /usr/bin/cli() [0x5f4914]
            [0x40b51629]

    Debug info from gdb:

    Could not attach to process.  If your uid matches the uid of the target
    process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
    again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
    ptrace: Operation not permitted.
    No threads.

    =================================================================
    Got a SIGSEGV while executing native code. This usually indicates
    a fatal error in the mono runtime or one of the native libraries
    used by your application.
    =================================================================

    Aborted (core dumped)

Let me know if there is anything else i can provide you with for support.
Amazing work getting a per-release out this fast, keep up the good work.

**Comment by hobnob11** [comment]
Running on an unbuntu dedicated machine

**Comment by tylerjwatson** [comment]
Please run mono with `mono-boehm TerrariaServer.exe`

**Comment by hobnob11** [comment]
Been playing with boehm for about 2 hours now and no major problems.
There is one small glitch where when you click on traders sometimes they teleport to the right most part of there house (might be there spawn point?)

**Comment by hobnob11** [comment]
It appears that any temporary change to the background (rain, solar eclipse, martian invasion etc) does not display on the client, this is only visual though as all of the enemies and special kinds do still spawn as normal.

**Comment by r0bc94** [comment]
I have the same "problem" even with the `mono-boehm` command.
