### ISSUE TITLE
Altars not breakable

### ISSUE THREAD

**Issue by Fortael** [NyxStudios/TShock#951]
Altars not breakable. After killing Wall of flesh

**Comment by tylerjwatson** [comment]
* OS Version
* TShock Version
* Amount of Players
* Expert mode?

**Comment by Fortael** [comment]
* Windows 8.1  x64
* TShock 4.3.0.0
* 3
* Normal

New mobs are spawned.

**Comment by WhiteXZ** [comment]
Fixed in 4ff861634cf416e3fb872551e5f77c8d5a00a03f
