### ISSUE TITLE
Cannot break Crimson Altars

### ISSUE THREAD

**Issue by omni-** [NyxStudios/TShock#957]
Post WoF kill, Pwnhammer will not destroy Crimson Altars, and the player will take damage as if the WoF had not been defeated.

Also NPCs randomly disappear and respawn.

**Comment by omni-** [comment]
In addition, it seems no hardmode ores have been generated.

**Comment by WhiteXZ** [comment]
Fixed in 4ff861634cf416e3fb872551e5f77c8d5a00a03f

**Comment by Munkeywaxx** [comment]
An old post, but I'm having the same issue.

Just Killed WoF, went to take down an altar, killed 3 or 4 and no new ores spawned.
