### ISSUE TITLE
Guide shoots only left

### ISSUE THREAD

**Issue by Chais** [NyxStudios/TShock#958]
Running 4.3.0-pre2 on linux. New character, new world.
I found the guide would only correctly aim at enemies to his left (west?). If an enemy was approaching from his right he would rotate his shot angle by 180°
So for further away enemies he'd have to aim higher and thus shoots right into the ground besides him. As the angle flattens out so does his shot direction.
The bow is aimed correctly, but the arrow flies off in the wrong direction. Looks like a sign error to my unaided eye.
If necessary I can provide screenshots.

**Comment by WhiteXZ** [comment]
This is likely some issue created by the decompiler, or one of the team removing client side code and killing a calculation by accident.
It should be fixable, assuming it's not a flaw of the vanilla, Re-Logic distributed Terraria Server as well

**Comment by Chais** [comment]
At least it works correctly when playing locally and I haven't noticed in when playing on other people's servers either.

**Comment by WhiteXZ** [comment]
I was playing earlier and didn't notice any issues. Can you update to the latest bleeding edge build and try again?

**Comment by Chais** [comment]
I can try. Any hints on how to build TShock? Until now I've only used the releases.

**Comment by WhiteXZ** [comment]
The latest release should work fine: https://github.com/NyxStudios/TShock/releases/tag/v4.3.1

**Comment by nicatronTg** [comment]
@Chais our CI server has artifacts published on every build: http://direct.tshock.co:8085/

**Comment by Chais** [comment]
At least for me the issue remains.
![badaim](https://cloud.githubusercontent.com/assets/1783098/8540466/693858a6-2486-11e5-87a0-bac6874b1a8c.jpg)

**Comment by Puremin0rez** [comment]
I can confirm this on 4.3.1
![lzj8q_07-07-2015](https://cloud.githubusercontent.com/assets/734478/8541322/e84ac036-2452-11e5-9886-d09038c5e3a9.png)

**Comment by Etherealflux** [comment]
Do other NPCs aim correctly? It definitely smells like a sign error.

**Comment by Chais** [comment]
They don't.
