### ISSUE TITLE
Dresser cannot be broken

### ISSUE THREAD

**Issue by WhiteXZ** [NyxStudios/TShock#960]
Can be placed and used as a chest fine, but cannot be removed after placing.

Can be destroyed with explosives

**Comment by Gummin** [comment]
I've noticed that as well.

**Comment by nicatronTg** [comment]
Broken in TShock, not API.

![](https://dl.dropboxusercontent.com/u/1253613/JaexMadeShareX/2015/07/Terraria_What%27s_that_purple_spiked_thing_2015-07-09_23-18-32.png)
