### ISSUE TITLE
Can't use previous world

### ISSUE THREAD

**Issue by shrx** [NyxStudios/TShock#961]
After updating to tshock v4.3.1.0, I can't load my server world anymore. It just gives me an option to create a new world or delete a world.
```
TerrariaAPI Version: 1.18.0.0 (Protocol v1.3.0.3 (149))
TShock 4.3.1.0 (Yoraiz0r R0cks) now running.
AutoSave Enabled
Backups Disabled
Welcome to TShock for Terraria. Initialization complete.
[Server API] Info Plugin TShock v4.3.1.0 (by The TShock Team) initiated.
Terraria Server v1.3.0.3


n               New World
d   <number>    Delete World

Choose World:
```

**Comment by Puremin0rez** [comment]
This is actually an issue with the vanilla game i'm pretty sure - I can't load my 1.2 (and earlier) worlds in my single player anymore either. They just have a red name. They must have made something incompatible between world data or something between updates.

**Comment by Strinkor** [comment]
It's issue in vanilla, not in Tshock.

**Comment by shrx** [comment]
Alright, closing.
