### ISSUE TITLE
Prefixes of items getting wiped on D/C.

### ISSUE THREAD

**Issue by tobiasx** [NyxStudios/TShock#962]
It seems whenever you D/C from a TShock server, any prefixes you had on your weapons disappear. 

E.I A Warding Cloud in a Bottle turns into a normal CIAB.

Sorry if someone already posted this issue, I just want to make sure it gets fixed.

**Comment by Patrikkk** [comment]
Hey there.
We didn't get a report about that before.
I just tested, spawned my self a warding CIAB, left/joined server, and it was still warding. :o
You are able to reproduce the problem every time? Or with other items?

**Comment by Enerdy** [comment]
Did you have ServerSideCharacters toggled on when this happened? If so, then that's normal. SSC is not yet ready for a full release, and some things might be broken. Thanks for reporting anyways.

**Comment by Patrikkk** [comment]
Uh just saw the other report from before. Yeah he definetly had SSC on.
Just tested.

**Comment by WhiteXZ** [comment]
This is a SSC issue, and will hopefully be resolved with the rest of the SSC issues.
https://github.com/NyxStudios/TShock/issues/963
