### ISSUE TITLE
SSC is broken

### ISSUE THREAD

**Issue by WhiteXZ** [NyxStudios/TShock#963]
Collaborators: Please redirect all SSC issues to this one, and close them.

- [x] Prefixes sometimes are not saved - fixed(?) in https://github.com/NyxStudios/TShock/commit/9aa863d62ece779307158faf7b110e4cd29bd94f
- [x] Piggybank and safe are abusable - fixed in https://github.com/NyxStudios/TShock/commit/f5e1b79fbbd4b8fa72949a15e619fed74bb9a065
- [x] No backwards compatibility - fixed in https://github.com/NyxStudios/TShock/commit/23ab14df4fa1326c0ffac967570a78931df058e7
- [x] Demon heart slot does not save - confirmed, being worked on
- [ ] Favourited items are unfavourited - confirmed, being worked on

**Comment by MrPotatoGaming** [comment]
I'm sorry I can't provide a lot of information, but the SSC doesn't seem to always save the players' information. Most of my server hasn't had an issue, but I have one player who's inventory has been reset multiple times. When the player joins about 1/2 of the time, they're loaded with a different starter copper item set. They log in using the /login command, and they also don't lose their rank, so it seems to only be saving issues for them.

**Comment by SmallSansSerif** [comment]
I'm not sure if this is intended behavior but the superuser account consistently gets wiped on each login with SSC enabled.

**Comment by Puremin0rez** [comment]
^ I can confirm that issue too - I've stopped using superuser on my account because most of the time my account would be wiped upon logging in. Not always, however.

**Comment by WhiteXZ** [comment]
@XAAM at this point in time we cannot fix favourited items losing their favourite flag, but hopefully it's something we can get put into the next Terraria update

**Comment by Zinsane** [comment]
SuperAdmin characters periodically lose all character progress.  I think its because its logging you in before the SSC can pull the inventory to your character.  As SuperAdmins's bypass the /login command.

**Comment by cccdfern** [comment]
An interesting thing to point out is that the only thing being wiped is the inventory, all other stats remain unaffected; if you have starting tools and move them around, they will be reverted to their default positions, anything besides those is wiped.

**Comment by Kromara** [comment]
Can verify that prefixes are not being saved in build #510

**Comment by CJKay** [comment]
Can verify that superuser account continuously gets wiped

**Comment by nicatronTg** [comment]
Using the superadmin account by default has all permissions, including that which overrides SSC. Make a privileged account with a different permission set and use that to play rather than the superadmin.

**Comment by MrPotatoGaming** [comment]
Is there a way to get a setup close to a vanilla server?

**Comment by nicatronTg** [comment]
Ask on the forums?

**Comment by MrPotatoGaming** [comment]
Oh, I was asking here so that people who look up this problem would have a walk-around for this. It's bound to happen to others.
