### ISSUE TITLE
Vortex armour stealth mode does not work properly

### ISSUE THREAD

**Issue by WhiteXZ** [NyxStudios/TShock#964]
Needs testing with and without TShock

Vortex armour stealth mode 'flashes' on and off

**Comment by masterbal111** [comment]
I have the same problem when playing on a TShock server, in SP the armor works just fine. (i haven't tested it on the standard dedicated server software yet)

I'm not a 100% sure but i do think the issue causes you to have lower DPS, however i find it hard to test this thanks to the few seconds it takes to stealth combined with the high critical strike chance of most end game weapons.

**Comment by Zoryn4163** [comment]
Can confirm with TShock 4.3.5 for Terraria 1.3.0.5 - it seems to be a TShock-only issue.
And yes, it does cycle the DPS (you can simply mouse over the weapon to see that the damage is cycling quickly)

**Comment by WhiteXZ** [comment]
Still needs confirmation on a Re-Logic provided vanilla server

**Comment by Zoryn4163** [comment]
Can not reproduce in the vanilla server.
![Example](http://i.gyazo.com/d1799c8358d2ffb4439b0cfee601b22e.gif)

**Comment by WhiteXZ** [comment]
Thank you, I'll try and fix this sometime tonight

**Comment by WhiteXZ** [comment]
Could not recreate in build 479. Assuming it got fixed somewhere/somehow

**Comment by Zoryn4163** [comment]
Can reproduce in build 481. Ensure you have another player on the server, and probably on the same screen as you. 
![Example](http://i.gyazo.com/ed9c118f34c6e75d099d381649044e0c.gif)
