### ISSUE TITLE
Clothier freezes after defense

### ISSUE THREAD

**Issue by Chais** [NyxStudios/TShock#966]
If the clothier defends himself with his spell he will be stuck afterwards.
Enemies will ignore him and if they happen to land on him or walk through him he won't take damage.
In this state you can't even butcher him. If you try the server will tell you that you just butcherd 0 NPCs.
I don't know if other NPCs are affected as well. Perhaps other spellcasters might be but the ones shooting projectiles or throwing stuff aren't.

**Comment by Ijwu** [comment]
Is this issue present with the vanilla server? Can you try and see if it happens again without TShock installed, that is.

**Comment by Chais** [comment]
Only in a local game. Running Terraria through Wine, which the official server doesn't like. It crashes immedeately. Similarly with mono. And there I can't just spawn a clothier via command ;)
