### ISSUE TITLE
Offscreen tilekills ignored

### ISSUE THREAD

**Issue by Chais** [NyxStudios/TShock#967]
Offscreen tilekills seem to be ignored completely. I tested with dynamite. This is the result:
![capture 2015-07-07 16_17_39](https://cloud.githubusercontent.com/assets/1783098/8554785/fa351032-24eb-11e5-9e41-d4f4cf1b8533.png)

**Comment by Ijwu** [comment]
Could be an issue with the client but needs investigation.

**Comment by Patrikkk** [comment]
There is a thing in config: `"RangeChecks": true,` (automatically set to true)
Which prevents people from destroying stuff out of their range.
Can someone close this?..

**Comment by Ijwu** [comment]
Trusting @Patrikkk on this.
