### ISSUE TITLE
Crashes immediately during world creation

### ISSUE THREAD

**Issue by Morgrimm** [NyxStudios/TShock#969]
Installed the prerelease on a 64x Fedora server, ran with mono, and about 14% through the resetting game objects portion of world creation the process terminates without warning - every time.

Logs as follows:

[ServerLog.txt](http://pastebin.com/5hWRndcq)
[Log in /tshock](http://pastebin.com/ZQZFfEzK)

The server starts fine, I get into world creation, pick my settings and name, and then this:
![console](https://cloud.githubusercontent.com/assets/3160654/8560458/f3012176-24e5-11e5-835f-18ac94d710f7.png)

No idea why.

**Comment by Puremin0rez** [comment]
"Killed" makes me think something on your system is intentionally killing the process. Do you have something that kills things using too many resources? I've seen this problem plenty with Minecraft servers on VPSs that use too many resources. No idea if this is the same issue.

**Comment by tylerjwatson** [comment]
`Killed` means it was killed by the kernel for taking up too much ram.  Please post the output of `free -h`.

I suspect you don't have enough RAM.

**Comment by Morgrimm** [comment]
Yep, that was it - RAM was restricted for some reason. I gave it 2GB, which seemed to be enough.

**Comment by pachonk** [comment]
This was helpful for me. I snagged a DO 512mb droplet and tried making a large world. Trying 2GB now.
