### ISSUE TITLE
Golem Boss Behavior Problems

### ISSUE THREAD

**Issue by Strackeror** [NyxStudios/TShock#972]
Was Fighting the golem boss with a friend yesterday and there were several weird behaviors...

1. Killing a fist spawned a golem head, you end up with 3 golem heads floating and attacking

2. The death animation of the golem is weird, it seems to do the body explosion effect every frame for a second or so

3. Some fights, the fists were not affected by projectile for the whole battle, where they were supposed to be reset on hit.

On another note, the steampunker npc does not sell steampunk wings after defeating golem, may or may not be related...

**Comment by Gummin** [comment]
My friend saw this happen as well, but personally have experienced it.

**Comment by WhiteXZ** [comment]
Needs testing on TSApi without TShock

**Comment by Gummin** [comment]
I farmed Golem with two of my friends for quite awhile and this never happened for any of us on 4.3.12.

**Comment by WhiteXZ** [comment]
Thanks @Gummin
