### ISSUE TITLE
Protection broken for "furniture" and related

### ISSUE THREAD

**Issue by popstarfreas** [NyxStudios/TShock#975]
This issue is simple, if an area is protected, anyone can still place furniture items and related. Here's the reproducible steps with proof:
As a guest, I check if the block is protected; "Spawn is protected from changes"; yes it is.
http://puu.sh/iRQmM/1206511e47.jpg

As a guest, I place down a Land Mine, but I get no "Spawn is protected from changes":
http://puu.sh/iRQqW/ea08ae88be.jpg

I rejoin to make sure the Land Mine is still there, and I try to destroy it, but "Spawn is protected from changes":
http://puu.sh/iRQxt/309ec597ae.jpg

The same happens with other furniture type items; Check block is protected:
http://puu.sh/iRQEe/030d959721.jpg

And yet I can place work bench:
http://puu.sh/iRQAK/1906ddf604.jpg

The same is true with Regions:
http://puu.sh/iRQQt/29e3168c0b.jpg
http://puu.sh/iRQSz/7461051be8.jpg

**Comment by popstarfreas** [comment]
Just thought I'd post here to update the issue and to just keep the information in one place, although Enerdy has already stated this in update on Slack.
The lack of protection is due to such objects using the PlaceObject packet which is currently not handled in TShock at this time, thus allowed such objects placements to bypass protection.

**Comment by WhiteXZ** [comment]
Should be fixed in next release
