### ISSUE TITLE
Server Freezing Terraria, if two player or more

### ISSUE THREAD

**Issue by Nightreaver** [NyxStudios/TShock#977]
So i've created a new server and changed the port to someting else.

Whenever i am player one in a world... i can join the server and run around, if anyone connects to the server i can not see them, but they can see me.

then when i leave the server, and join after someone else is already online, i can connect, walk around a bit, then my game is freezing
i can try the same over and over, as long as someone else is online, my game is freezing

i've tried different characters and different worlds, doesn't matter

so you can see that the situation is different for both of us, must be two different errors for the same problem?!

-
Mono JIT compiler version 4.0.1 (tarball Tue Apr 28 11:47:58 UTC 2015)
Linux xxx 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux
tshock 4.3.1 pre1
-

i can replicate it over and over but i dont have any errors, crashes or so

any ideas?

**Comment by ronchaine** [comment]
This happened to me once when I had 6 players online, but I am unable to replicate this.

**Comment by WhiteXZ** [comment]
No further reports received in 7 days
