### ISSUE TITLE
OnLootDrop Hook no longer seems to function.

### ISSUE THREAD

**Issue by Pychnight** [NyxStudios/TShock#979]
I was testing out this hook on the lastest tshock build and it seems to be broken (same with Ondeath), I was looking into it further by testing the functionality of this hook to see if it was reached at all and none of the break points where hit in this hook. (maybe, i did something wrong?)

This should be looked into further.

This is most likely a Tshock API issue but,  I will open it here, so the developers can decide where it will go.

**Comment by nicatronTg** [comment]
The hook should definitely be fired. It's just a hook on get data -- it might have bad data, but you're certain that it's not working?

This is the ItemDrop hook right? OnItemDrop?

**Comment by Patrikkk** [comment]
Fixed in latest release. 4.3.6
*pretends to close issue :kappa:
