### ISSUE TITLE
King Slime spawns slimes to mob cap

### ISSUE THREAD

**Issue by Peach774** [NyxStudios/TShock#980]
When the king slime spawns he spawns as many slimes as possible, hitting the mob cap. When he spawned on our server, he spawned 2200 slimes during the fight and bogged the server down.

**Comment by WhiteXZ** [comment]
Fixed in https://github.com/NyxStudios/TerrariaAPI-Server/commit/7170d8c4965b2c03391cf7e0a45ae1f0c6ad5945
