### ISSUE TITLE
Item enchantments dissapear upon reconnect on SSC + Other issues

### ISSUE THREAD

**Issue by XAAAM** [NyxStudios/TShock#982]
* If any of the items you have equiped or have in your inventory while playing SSC have enchantments. The enchantments will all dissappear when disconnecting/reconnecting to the server. (SSC)

* The extra accessory slot unlocked with Demon Heart does not save on SSC either. You have to consume a Demon Heart everytime you reconnect. (SSC)

* Favorited items does not save. (SSC)

**Comment by WhiteXZ** [comment]
https://github.com/NyxStudios/TShock/issues/963
