### ISSUE TITLE
Wormhole potions no longer working

### ISSUE THREAD

**Issue by recon88** [NyxStudios/TShock#984]
Since tShock updated to Terraria 1.3.0.4, Wormhole potions are no longer working on my (Windows) server.
Anyone else experiencing that issue and can confirm that?

**Comment by Stealownz** [comment]
It's still fine on mine.

**Comment by recon88** [comment]
That's weird. We are 3 people and nobody is able to use them after the update.

**Comment by Stealownz** [comment]
Can you confirm that you're in the same party by /p chatting

**Comment by WhiteXZ** [comment]
Cannot recreate in build 477

**Comment by Razorskills** [comment]
I did a fresh install of pre 1.3.0.7 release, and I couldn't use a wormhole potions unless I logged in as admin. it also used up my potion even though I did not actually teleport. I have't done another install and test, but all I did was install mono-complete on my linux machine, then ran the server with it, made a large world, on expert mode. And tada if someone would like me to do more testing, let me know. but for now i might have to give them some sort of permission to be able to teleport..

**Comment by nicatronTg** [comment]
You need tshock.tp.wormhole on the account to use the potion.

**Comment by Razorskills** [comment]
hmmm I il try to find the default permissions group and just add that to it then.. if that is possible. to the wiki!

**Comment by MadeBySaints** [comment]
I have seen a lot of people complaining about this on another server, apparently the tshock.tp.wormhole node isnt well known, and is not on the atlassian page

**Comment by WhiteXZ** [comment]
@MadeBySaints The [commands/permissions list](https://tshock.atlassian.net/wiki/pages/viewpage.action?pageId=3047433)  has now been updated.

**Comment by MadeBySaints** [comment]
Ahh good, Glad i could help :palm_tree:
