### ISSUE TITLE
NPCs teleporting theirselves

### ISSUE THREAD

**Issue by alexaaa789** [NyxStudios/TShock#985]
I am not sure if this is a problem of the map, or a common issue. 

At day, the NPCs seem to teleport back to a place after a while, walking too far from their rooms or when I interact with them. The affected NPCs are completely random. For example, the arms dealer was affected by this issue, but then he stopped teleporting after a while and another NPC (i.e. the merchant) was affected. They teleport to the right side of a room. The clothier NPC living underground just stay in a spot and keep turning his head left and right.

![Animation 0](http://fat.gfycat.com/EasySleepyCoypu.gif)

However, at night, the NPCs reacted in a completely different way. They just stay in the middle of their room and not walking at all (the same as vanilla server), except the angler who lives at the ground floor of my house. He didn't do that in vanilla server, instead he just stay in a spot.

![capture 2015-07-07 20_24_03](https://cloud.githubusercontent.com/assets/13219519/8546219/6590c73a-24e8-11e5-834d-1c5afbda0885.jpg)

After Issue #953 was fixed, the NPCs no longer disappear upon facing an enemy. However they still act strangely at day compared to vanilla servers.

**Comment by Kromara** [comment]
I've experienced this as well in 1.3.0.3 but haven't tested in 1.3.0.4 at
all. Experienced the NPCs disappearing entirely and then spawning again a
few minutes later.

**Comment by Gummin** [comment]
Happens to me too.

**Comment by alexaaa789** [comment]
I found one more issue that the NPCs chat bubble (not the right-click one) doesn't appear when they are talking to other NPCs or a player, while it appears in vanilla servers.
