### ISSUE TITLE
Expert Mode Bosses Treasure Bag Bug

### ISSUE THREAD

**Issue by REltic** [NyxStudios/TShock#987]
- TShock Version 4.3.3

Bosses in Expert mode do not drop treasure bags when killed. All bosses spawned conventionally and through commands do not drop items.

Steps Used

- Spawned Wall of Flesh (w/ doll and w/ commands)
- Slayed boss after 1 min.
- Freaked out because we didn't get any drops...

These steps have been tested with multiple bosses including...
Cultist
Wall of Flesh
The Twins
Eye of Cthulhu

**Comment by thompGIT** [comment]
Can also confirm it happens with King Slime.

**Comment by jtmal0723** [comment]
I can also confirm with the Golem and Plantera summoning/fighting multiple times with the /spawnmob and actually summoning them.

**Comment by WhiteXZ** [comment]
Cannot recreate in build 477
