### ISSUE TITLE
autocreate parameter isn't working

### ISSUE THREAD

**Issue by Kenterfie** [NyxStudios/TShock#989]
We have tried your current build version 4.3.3 on our servers and we have noticed, that paramter "autocreate" is ignored. Currently server isn't starting complete, it stops with a prompt to asked for a world. Is it possible to fix it soon?

we currently run our servers with
terrariaserver.exe -ip <ip> -port <port> -players <player> -autocreate 1 -config tshock_config.txt

![cp896](https://cloud.githubusercontent.com/assets/527694/8630504/da3ee71c-2766-11e5-8603-6dad01f16e71.png)

**Comment by nicatronTg** [comment]
You have to specify a world filename with the -world parameter to
autocreate a world.

**Comment by Kenterfie** [comment]
thanks, it works. good work!
