### ISSUE TITLE
invasion completion meter bug

### ISSUE THREAD

**Issue by sharkbound** [NyxStudios/TShock#991]
tshock version: TShock 4.3.3 (API v1.19) PreRelease for Terraria 1.3.0.4

how to reproduce: make a invasion happen, doesnt matter how the invasion happens from my testing

screenshot: http://imgur.com/JVaZUAO 

more info: it will jump around from low numbers to numbers in the millions, it seems random

**Comment by WhiteXZ** [comment]
This has been fixed and will be in the next release
