### ISSUE TITLE
Architect Gizmo Pack's Paint Sprayer function won't work properly

### ISSUE THREAD

**Issue by MasterYoda69** [NyxStudios/TShock#992]
https://www.youtube.com/watch?v=2LWaLLNwkbM

Was recorded on a Tshock server, could reupload with proof of it if required.

**Comment by WhiteXZ** [comment]
How is it meant to function?

**Comment by MasterYoda69** [comment]
As you can see in the video, it's not painting the blocks I place when I place them when the tooltip says it should.

**Comment by WhiteXZ** [comment]
It painted them while the item was equipped in the accessories slot though?

**Comment by MasterYoda69** [comment]
Particles were going off indicating it was, and the paint was being used, however the tiles were coming off unpainted, they started being painted once I equipped the paint sprayer.

**Comment by WhiteXZ** [comment]
Ah, I see, my bad. I didn't see the tooltip for the gizmo until I watched the video more closely. Will look into this.
