### ISSUE TITLE
Missing method .ctor in assembly Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by Tangeek42** [NyxStudios/TShock#994]
Hi,

I'm not sure if it's related to TShock or something else (I really, **REALLY** don't know what I'm talking about here), but I tried several times to launch the latest release 4.3.3 for Terraria 1.3.0.4 on a Debian system using mono, and I got the following error log. Mono is up to date, I have no idea what I should do. I tried searching on the Internet, but since this release is so young, nobody else already post about it, and I end up with a lot of forum threads talking about a somewhat similar issue but I've no idea what's it about. :/ 

Anyway, heres' the full error log :
	$ mono TerrariaServer.exe
	Missing method .ctor in assembly /root/serveurs/terraria/Newtonsoft.Json.dll, type System.Runtime.CompilerServices.ExtensionAttribute
	Can't find custom attr constructor image: /root/serveurs/terraria/Newtonsoft.Json.dll mtoken: 0x0a000077
	[Server API] Error Server crashed due to an unhandled exception:
	System.TypeInitializationException: An exception was thrown by the type initializer for Terraria.Main ---> System.TypeInitializationException: An exception was thrown by the type initializer for Newtonsoft.Json.JsonSerializerSettings ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'Newtonsoft.Json'.
	  --- End of inner exception stack trace ---
	  at Terraria.IO.Preferences..ctor (System.String path, Boolean parseAllTypes, Boolean useBson) [0x00000] in <filename unknown>:0
	  at Terraria.Main..cctor () [0x00000] in <filename unknown>:0
	  --- End of inner exception stack trace ---
	  at Terraria.ProgramServer.InnerStart (System.String[] args) [0x00000] in <filename unknown>:0

Thanks a lot for your help.

**Comment by nicatronTg** [comment]
Mono 4?

**Comment by Tangeek42** [comment]
$ mono -V
Mono JIT compiler version 2.10.8.1
...
2 < 4...
...
Crap no ! T_T'

I didn't think there was a 4th version. According to Debian's packages system, I am up to date. It didn't cross my mind I was that far off, especially when the other releases of TShock work. I'll try to install Mono 4, and see if it works. Thank you for the tip !

**Comment by nicatronTg** [comment]
@Tangeek42 nope, that's really ancient. Try this, or compile from source: http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

**Comment by Tangeek42** [comment]
Yep, I was just upgrading the packages reading that precise page. ^^ Indeed I am now with Mono 4 and it works !

Thanks a lot ! I feel kind of stupid now. ^^' Sorry to have created a "issue" for nothing.

**Comment by nicatronTg** [comment]
Yep!
