### ISSUE TITLE
Can't toggle Trap Door

### ISSUE THREAD

**Issue by Stealownz** [NyxStudios/TShock#998]
Trap Doors disappear on toggle or exhibit weird behaviors.

Superadmins can toggle fine though.

**Comment by Stealownz** [comment]
Tall Gate also.

**Comment by Stealownz** [comment]
Along with Target Dummy, Vortex Monolith, Nebula Monolith, Stardust Monolith, Solar Monolith

**Comment by Ijwu** [comment]
Likely another issue with our data handlers. I'll take a look.

**Comment by Spazturtle** [comment]
Issue seams to be present in TShock 4.3.11, trap doors cannot be toggled unless the user is super-admin.

**Comment by WhiteXZ** [comment]
@Spazturtle what happens if you give your user the permission `tshock.ignore.sendtilesquare`?
