### ISSUE TITLE
Items disappearing on placement

### ISSUE THREAD

**Issue by Stealownz** [NyxStudios/TShock#999]
Item Frame, Target Dummy, Vortex Monolith, Stardust Monolith, Nebula Monolith, Solar Monolith disappear on placement. 

The disappearance is only to the player who placed it, players around can see it placed properly.

**Comment by Ijwu** [comment]
That's just funny, but possibly another issue with data handlers. Will be taking a look.

**Comment by mitchell-es** [comment]
The patch didn't seem to address target dummies which I can't seem to place properly in 4.3.9.0.
